// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type TeamMembership struct {
	TeamID    string
	UserID    pgtype.UUID
	Role      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
	RemovedAt pgtype.Timestamptz
}
