// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: team.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireTeamAdvisoryLock = `-- name: AcquireTeamAdvisoryLock :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

func (q *Queries) AcquireTeamAdvisoryLock(ctx context.Context, lockKey string) error {
	_, err := q.db.Exec(ctx, acquireTeamAdvisoryLock, lockKey)
	return err
}

const archiveProject = `-- name: ArchiveProject :one
UPDATE canonical_projects
SET state = 'archived', archived_at = COALESCE(archived_at, clock_timestamp()),
    updated_at = CASE WHEN state = 'active' THEN clock_timestamp() ELSE updated_at END
WHERE id = $1 AND state IN ('active', 'archived')
RETURNING id, team_id, name, project_type, state, captured_through,
          created_at, updated_at, archived_at, deleted_at
`

type ArchiveProjectRow struct {
	ID              string
	TeamID          string
	Name            string
	ProjectType     string
	State           string
	CapturedThrough time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
	ArchivedAt      pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

func (q *Queries) ArchiveProject(ctx context.Context, id string) (ArchiveProjectRow, error) {
	row := q.db.QueryRow(ctx, archiveProject, id)
	var i ArchiveProjectRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.ProjectType,
		&i.State,
		&i.CapturedThrough,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
	)
	return i, err
}

const clearJoinCodeAttemptWindow = `-- name: ClearJoinCodeAttemptWindow :exec
DELETE FROM team_join_code_attempt_windows
WHERE user_id = $1 AND window_start = $2
`

type ClearJoinCodeAttemptWindowParams struct {
	UserID      pgtype.UUID
	WindowStart time.Time
}

func (q *Queries) ClearJoinCodeAttemptWindow(ctx context.Context, arg ClearJoinCodeAttemptWindowParams) error {
	_, err := q.db.Exec(ctx, clearJoinCodeAttemptWindow, arg.UserID, arg.WindowStart)
	return err
}

const countOtherActiveOwners = `-- name: CountOtherActiveOwners :one
SELECT COUNT(*)::bigint
FROM team_memberships memberships
JOIN auth_users users ON users.id = memberships.user_id
WHERE memberships.team_id = $1
  AND memberships.status = 'active'
  AND memberships.role = 'owner'
  AND users.status = 'active'
  AND memberships.user_id <> $2
`

type CountOtherActiveOwnersParams struct {
	TeamID string
	UserID pgtype.UUID
}

func (q *Queries) CountOtherActiveOwners(ctx context.Context, arg CountOtherActiveOwnersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOtherActiveOwners, arg.TeamID, arg.UserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const currentJoinCodeForTeamForUpdate = `-- name: CurrentJoinCodeForTeamForUpdate :one
SELECT id, team_id, generation, pepper_key_id, code_digest, status,
       created_at, retired_at, disabled_at
FROM team_join_codes
WHERE team_id = $1 AND status = 'enabled'
FOR UPDATE
`

type CurrentJoinCodeForTeamForUpdateRow struct {
	ID          pgtype.UUID
	TeamID      string
	Generation  int32
	PepperKeyID string
	CodeDigest  []byte
	Status      string
	CreatedAt   time.Time
	RetiredAt   pgtype.Timestamptz
	DisabledAt  pgtype.Timestamptz
}

func (q *Queries) CurrentJoinCodeForTeamForUpdate(ctx context.Context, teamID string) (CurrentJoinCodeForTeamForUpdateRow, error) {
	row := q.db.QueryRow(ctx, currentJoinCodeForTeamForUpdate, teamID)
	var i CurrentJoinCodeForTeamForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Generation,
		&i.PepperKeyID,
		&i.CodeDigest,
		&i.Status,
		&i.CreatedAt,
		&i.RetiredAt,
		&i.DisabledAt,
	)
	return i, err
}

const databaseTime = `-- name: DatabaseTime :one
SELECT clock_timestamp()::timestamptz
`

func (q *Queries) DatabaseTime(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, databaseTime)
	var column_1 time.Time
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteRepositoryAliases = `-- name: DeleteRepositoryAliases :exec
DELETE FROM team_project_repository_aliases
WHERE project_id = $1
`

func (q *Queries) DeleteRepositoryAliases(ctx context.Context, projectID string) error {
	_, err := q.db.Exec(ctx, deleteRepositoryAliases, projectID)
	return err
}

const disableCurrentJoinCode = `-- name: DisableCurrentJoinCode :execrows
UPDATE team_join_codes
SET status = 'disabled', disabled_at = clock_timestamp()
WHERE team_id = $1 AND status = 'enabled'
`

func (q *Queries) DisableCurrentJoinCode(ctx context.Context, teamID string) (int64, error) {
	result, err := q.db.Exec(ctx, disableCurrentJoinCode, teamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findEnabledJoinCode = `-- name: FindEnabledJoinCode :one
SELECT id, team_id, generation, pepper_key_id, code_digest
FROM team_join_codes
WHERE pepper_key_id = $1 AND code_digest = $2 AND status = 'enabled'
`

type FindEnabledJoinCodeParams struct {
	PepperKeyID string
	CodeDigest  []byte
}

type FindEnabledJoinCodeRow struct {
	ID          pgtype.UUID
	TeamID      string
	Generation  int32
	PepperKeyID string
	CodeDigest  []byte
}

func (q *Queries) FindEnabledJoinCode(ctx context.Context, arg FindEnabledJoinCodeParams) (FindEnabledJoinCodeRow, error) {
	row := q.db.QueryRow(ctx, findEnabledJoinCode, arg.PepperKeyID, arg.CodeDigest)
	var i FindEnabledJoinCodeRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Generation,
		&i.PepperKeyID,
		&i.CodeDigest,
	)
	return i, err
}

const findProjectByRepositoryIdentity = `-- name: FindProjectByRepositoryIdentity :one
SELECT projects.id, projects.team_id, projects.name, projects.project_type,
       projects.state, projects.captured_through, projects.created_at,
       projects.updated_at, projects.archived_at, projects.deleted_at,
       current_alias.remote_identity
FROM team_project_repository_aliases matched_alias
JOIN canonical_projects projects ON projects.id = matched_alias.project_id
LEFT JOIN team_project_repository_aliases current_alias
       ON current_alias.project_id = projects.id AND current_alias.current
WHERE matched_alias.team_id = $1
  AND matched_alias.remote_identity = $2
  AND projects.state = 'active'
`

type FindProjectByRepositoryIdentityParams struct {
	TeamID         string
	RemoteIdentity string
}

type FindProjectByRepositoryIdentityRow struct {
	ID              string
	TeamID          string
	Name            string
	ProjectType     string
	State           string
	CapturedThrough time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
	ArchivedAt      pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	RemoteIdentity  *string
}

func (q *Queries) FindProjectByRepositoryIdentity(ctx context.Context, arg FindProjectByRepositoryIdentityParams) (FindProjectByRepositoryIdentityRow, error) {
	row := q.db.QueryRow(ctx, findProjectByRepositoryIdentity, arg.TeamID, arg.RemoteIdentity)
	var i FindProjectByRepositoryIdentityRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.ProjectType,
		&i.State,
		&i.CapturedThrough,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.RemoteIdentity,
	)
	return i, err
}

const getJoinCodeAttemptWindowForUpdate = `-- name: GetJoinCodeAttemptWindowForUpdate :one
SELECT failure_count, blocked_until
FROM team_join_code_attempt_windows
WHERE user_id = $1 AND window_start = $2
FOR UPDATE
`

type GetJoinCodeAttemptWindowForUpdateParams struct {
	UserID      pgtype.UUID
	WindowStart time.Time
}

type GetJoinCodeAttemptWindowForUpdateRow struct {
	FailureCount int32
	BlockedUntil pgtype.Timestamptz
}

func (q *Queries) GetJoinCodeAttemptWindowForUpdate(ctx context.Context, arg GetJoinCodeAttemptWindowForUpdateParams) (GetJoinCodeAttemptWindowForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getJoinCodeAttemptWindowForUpdate, arg.UserID, arg.WindowStart)
	var i GetJoinCodeAttemptWindowForUpdateRow
	err := row.Scan(&i.FailureCount, &i.BlockedUntil)
	return i, err
}

const getJoinCodeByIDForUpdate = `-- name: GetJoinCodeByIDForUpdate :one
SELECT id, team_id, generation, pepper_key_id, code_digest, status,
       created_at, retired_at, disabled_at
FROM team_join_codes
WHERE id = $1
FOR UPDATE
`

type GetJoinCodeByIDForUpdateRow struct {
	ID          pgtype.UUID
	TeamID      string
	Generation  int32
	PepperKeyID string
	CodeDigest  []byte
	Status      string
	CreatedAt   time.Time
	RetiredAt   pgtype.Timestamptz
	DisabledAt  pgtype.Timestamptz
}

func (q *Queries) GetJoinCodeByIDForUpdate(ctx context.Context, id pgtype.UUID) (GetJoinCodeByIDForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getJoinCodeByIDForUpdate, id)
	var i GetJoinCodeByIDForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Generation,
		&i.PepperKeyID,
		&i.CodeDigest,
		&i.Status,
		&i.CreatedAt,
		&i.RetiredAt,
		&i.DisabledAt,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT team_id, user_id, role, status, created_at, updated_at, removed_at
FROM team_memberships
WHERE team_id = $1 AND user_id = $2
`

type GetMembershipParams struct {
	TeamID string
	UserID pgtype.UUID
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.TeamID, arg.UserID)
	var i TeamMembership
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const getMembershipForUpdate = `-- name: GetMembershipForUpdate :one
SELECT team_id, user_id, role, status, created_at, updated_at, removed_at
FROM team_memberships
WHERE team_id = $1 AND user_id = $2
FOR UPDATE
`

type GetMembershipForUpdateParams struct {
	TeamID string
	UserID pgtype.UUID
}

func (q *Queries) GetMembershipForUpdate(ctx context.Context, arg GetMembershipForUpdateParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, getMembershipForUpdate, arg.TeamID, arg.UserID)
	var i TeamMembership
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const getOperationReceiptForUpdate = `-- name: GetOperationReceiptForUpdate :one
SELECT request_digest, resource_id, expires_at
FROM team_operation_receipts
WHERE user_id = $1 AND action = $2 AND operation_key = $3
FOR UPDATE
`

type GetOperationReceiptForUpdateParams struct {
	UserID       pgtype.UUID
	Action       string
	OperationKey string
}

type GetOperationReceiptForUpdateRow struct {
	RequestDigest []byte
	ResourceID    string
	ExpiresAt     time.Time
}

func (q *Queries) GetOperationReceiptForUpdate(ctx context.Context, arg GetOperationReceiptForUpdateParams) (GetOperationReceiptForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getOperationReceiptForUpdate, arg.UserID, arg.Action, arg.OperationKey)
	var i GetOperationReceiptForUpdateRow
	err := row.Scan(&i.RequestDigest, &i.ResourceID, &i.ExpiresAt)
	return i, err
}

const getPrincipalUserForShare = `-- name: GetPrincipalUserForShare :one
SELECT id, status
FROM auth_users
WHERE id = $1
FOR SHARE
`

type GetPrincipalUserForShareRow struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) GetPrincipalUserForShare(ctx context.Context, id pgtype.UUID) (GetPrincipalUserForShareRow, error) {
	row := q.db.QueryRow(ctx, getPrincipalUserForShare, id)
	var i GetPrincipalUserForShareRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT projects.id, projects.team_id, projects.name, projects.project_type,
       projects.state, projects.captured_through, projects.created_at,
       projects.updated_at, projects.archived_at, projects.deleted_at,
       aliases.remote_identity
FROM canonical_projects projects
LEFT JOIN team_project_repository_aliases aliases
       ON aliases.project_id = projects.id AND aliases.current
WHERE projects.id = $1
`

type GetProjectRow struct {
	ID              string
	TeamID          string
	Name            string
	ProjectType     string
	State           string
	CapturedThrough time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
	ArchivedAt      pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	RemoteIdentity  *string
}

func (q *Queries) GetProject(ctx context.Context, id string) (GetProjectRow, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i GetProjectRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.ProjectType,
		&i.State,
		&i.CapturedThrough,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.RemoteIdentity,
	)
	return i, err
}

const getProjectForUpdate = `-- name: GetProjectForUpdate :one
SELECT projects.id, projects.team_id, projects.name, projects.project_type,
       projects.state, projects.captured_through, projects.created_at,
       projects.updated_at, projects.archived_at, projects.deleted_at,
       aliases.remote_identity
FROM canonical_projects projects
LEFT JOIN team_project_repository_aliases aliases
       ON aliases.project_id = projects.id AND aliases.current
WHERE projects.id = $1
FOR UPDATE OF projects
`

type GetProjectForUpdateRow struct {
	ID              string
	TeamID          string
	Name            string
	ProjectType     string
	State           string
	CapturedThrough time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
	ArchivedAt      pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	RemoteIdentity  *string
}

func (q *Queries) GetProjectForUpdate(ctx context.Context, id string) (GetProjectForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getProjectForUpdate, id)
	var i GetProjectForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.ProjectType,
		&i.State,
		&i.CapturedThrough,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.RemoteIdentity,
	)
	return i, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, slug, name, created_at, updated_at
FROM workspace_teams
WHERE id = $1
`

type GetTeamByIDRow struct {
	ID        string
	Slug      *string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetTeamByID(ctx context.Context, id string) (GetTeamByIDRow, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i GetTeamByIDRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamByIDForUpdate = `-- name: GetTeamByIDForUpdate :one
SELECT id, slug, name, created_at, updated_at
FROM workspace_teams
WHERE id = $1
FOR UPDATE
`

type GetTeamByIDForUpdateRow struct {
	ID        string
	Slug      *string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetTeamByIDForUpdate(ctx context.Context, id string) (GetTeamByIDForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getTeamByIDForUpdate, id)
	var i GetTeamByIDForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamBySlug = `-- name: GetTeamBySlug :one
SELECT id, slug, name, created_at, updated_at
FROM workspace_teams
WHERE slug = $1
`

type GetTeamBySlugRow struct {
	ID        string
	Slug      *string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetTeamBySlug(ctx context.Context, slug *string) (GetTeamBySlugRow, error) {
	row := q.db.QueryRow(ctx, getTeamBySlug, slug)
	var i GetTeamBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamBySlugForUpdate = `-- name: GetTeamBySlugForUpdate :one
SELECT id, slug, name, created_at, updated_at
FROM workspace_teams
WHERE slug = $1
FOR UPDATE
`

type GetTeamBySlugForUpdateRow struct {
	ID        string
	Slug      *string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetTeamBySlugForUpdate(ctx context.Context, slug *string) (GetTeamBySlugForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getTeamBySlugForUpdate, slug)
	var i GetTeamBySlugForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertJoinCode = `-- name: InsertJoinCode :one
INSERT INTO team_join_codes (
    id, team_id, generation, pepper_key_id, code_digest, digest_version, status
) VALUES ($1, $2, $3, $4, $5, 'hmac-sha256-v1', 'enabled')
RETURNING id, team_id, generation, pepper_key_id, code_digest, status,
          created_at, retired_at, disabled_at
`

type InsertJoinCodeParams struct {
	ID          pgtype.UUID
	TeamID      string
	Generation  int32
	PepperKeyID string
	CodeDigest  []byte
}

type InsertJoinCodeRow struct {
	ID          pgtype.UUID
	TeamID      string
	Generation  int32
	PepperKeyID string
	CodeDigest  []byte
	Status      string
	CreatedAt   time.Time
	RetiredAt   pgtype.Timestamptz
	DisabledAt  pgtype.Timestamptz
}

func (q *Queries) InsertJoinCode(ctx context.Context, arg InsertJoinCodeParams) (InsertJoinCodeRow, error) {
	row := q.db.QueryRow(ctx, insertJoinCode,
		arg.ID,
		arg.TeamID,
		arg.Generation,
		arg.PepperKeyID,
		arg.CodeDigest,
	)
	var i InsertJoinCodeRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Generation,
		&i.PepperKeyID,
		&i.CodeDigest,
		&i.Status,
		&i.CreatedAt,
		&i.RetiredAt,
		&i.DisabledAt,
	)
	return i, err
}

const insertMemberMembership = `-- name: InsertMemberMembership :one
INSERT INTO team_memberships (team_id, user_id, role, status)
VALUES ($1, $2, 'member', 'active')
RETURNING team_id, user_id, role, status, created_at, updated_at, removed_at
`

type InsertMemberMembershipParams struct {
	TeamID string
	UserID pgtype.UUID
}

func (q *Queries) InsertMemberMembership(ctx context.Context, arg InsertMemberMembershipParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, insertMemberMembership, arg.TeamID, arg.UserID)
	var i TeamMembership
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const insertOperationReceipt = `-- name: InsertOperationReceipt :exec
INSERT INTO team_operation_receipts (
    user_id, action, operation_key, request_digest, resource_id, expires_at
) VALUES (
    $1, $2, $3, $4, $5,
    clock_timestamp() + $6::integer * interval '1 second'
)
`

type InsertOperationReceiptParams struct {
	UserID        pgtype.UUID
	Action        string
	OperationKey  string
	RequestDigest []byte
	ResourceID    string
	TtlSeconds    int32
}

func (q *Queries) InsertOperationReceipt(ctx context.Context, arg InsertOperationReceiptParams) error {
	_, err := q.db.Exec(ctx, insertOperationReceipt,
		arg.UserID,
		arg.Action,
		arg.OperationKey,
		arg.RequestDigest,
		arg.ResourceID,
		arg.TtlSeconds,
	)
	return err
}

const insertOwnerMembership = `-- name: InsertOwnerMembership :one
INSERT INTO team_memberships (team_id, user_id, role, status)
VALUES ($1, $2, 'owner', 'active')
RETURNING team_id, user_id, role, status, created_at, updated_at, removed_at
`

type InsertOwnerMembershipParams struct {
	TeamID string
	UserID pgtype.UUID
}

func (q *Queries) InsertOwnerMembership(ctx context.Context, arg InsertOwnerMembershipParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, insertOwnerMembership, arg.TeamID, arg.UserID)
	var i TeamMembership
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const insertProject = `-- name: InsertProject :one
INSERT INTO canonical_projects (id, team_id, name, project_type, state)
VALUES ($1, $2, $3, $4, 'active')
RETURNING id, team_id, name, project_type, state, captured_through,
          created_at, updated_at, archived_at, deleted_at
`

type InsertProjectParams struct {
	ID          string
	TeamID      string
	Name        string
	ProjectType string
}

type InsertProjectRow struct {
	ID              string
	TeamID          string
	Name            string
	ProjectType     string
	State           string
	CapturedThrough time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
	ArchivedAt      pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) (InsertProjectRow, error) {
	row := q.db.QueryRow(ctx, insertProject,
		arg.ID,
		arg.TeamID,
		arg.Name,
		arg.ProjectType,
	)
	var i InsertProjectRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.ProjectType,
		&i.State,
		&i.CapturedThrough,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertRepositoryAlias = `-- name: InsertRepositoryAlias :exec
INSERT INTO team_project_repository_aliases (
    project_id, team_id, remote_identity, current
) VALUES ($1, $2, $3, $4)
`

type InsertRepositoryAliasParams struct {
	ProjectID      string
	TeamID         string
	RemoteIdentity string
	Current        bool
}

func (q *Queries) InsertRepositoryAlias(ctx context.Context, arg InsertRepositoryAliasParams) error {
	_, err := q.db.Exec(ctx, insertRepositoryAlias,
		arg.ProjectID,
		arg.TeamID,
		arg.RemoteIdentity,
		arg.Current,
	)
	return err
}

const insertSecurityAuditEvent = `-- name: InsertSecurityAuditEvent :exec
INSERT INTO security_audit_events (
    id, initiator_kind, initiator_id, action, target_kind, target_id,
    outcome, reason, request_id, provider_registration_id,
    web_session_id, cli_credential_id, metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, '', $10, $11, $12)
`

type InsertSecurityAuditEventParams struct {
	ID              pgtype.UUID
	InitiatorKind   string
	InitiatorID     string
	Action          string
	TargetKind      string
	TargetID        string
	Outcome         string
	Reason          string
	RequestID       string
	WebSessionID    pgtype.UUID
	CliCredentialID pgtype.UUID
	Metadata        []byte
}

func (q *Queries) InsertSecurityAuditEvent(ctx context.Context, arg InsertSecurityAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertSecurityAuditEvent,
		arg.ID,
		arg.InitiatorKind,
		arg.InitiatorID,
		arg.Action,
		arg.TargetKind,
		arg.TargetID,
		arg.Outcome,
		arg.Reason,
		arg.RequestID,
		arg.WebSessionID,
		arg.CliCredentialID,
		arg.Metadata,
	)
	return err
}

const insertTeam = `-- name: InsertTeam :one
INSERT INTO workspace_teams (id, slug, name, name_reported)
VALUES ($1, $2, $3, TRUE)
RETURNING id, slug, name, created_at, updated_at
`

type InsertTeamParams struct {
	ID   string
	Slug *string
	Name string
}

type InsertTeamRow struct {
	ID        string
	Slug      *string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) InsertTeam(ctx context.Context, arg InsertTeamParams) (InsertTeamRow, error) {
	row := q.db.QueryRow(ctx, insertTeam, arg.ID, arg.Slug, arg.Name)
	var i InsertTeamRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const joinCodeDigestExists = `-- name: JoinCodeDigestExists :one
SELECT EXISTS (
    SELECT 1
    FROM team_join_codes
    WHERE pepper_key_id = $1 AND code_digest = $2
)::boolean
`

type JoinCodeDigestExistsParams struct {
	PepperKeyID string
	CodeDigest  []byte
}

func (q *Queries) JoinCodeDigestExists(ctx context.Context, arg JoinCodeDigestExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, joinCodeDigestExists, arg.PepperKeyID, arg.CodeDigest)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const latestJoinCodeForTeam = `-- name: LatestJoinCodeForTeam :one
SELECT id, team_id, generation, pepper_key_id, code_digest, status,
       created_at, retired_at, disabled_at
FROM team_join_codes
WHERE team_id = $1
ORDER BY generation DESC
LIMIT 1
`

type LatestJoinCodeForTeamRow struct {
	ID          pgtype.UUID
	TeamID      string
	Generation  int32
	PepperKeyID string
	CodeDigest  []byte
	Status      string
	CreatedAt   time.Time
	RetiredAt   pgtype.Timestamptz
	DisabledAt  pgtype.Timestamptz
}

func (q *Queries) LatestJoinCodeForTeam(ctx context.Context, teamID string) (LatestJoinCodeForTeamRow, error) {
	row := q.db.QueryRow(ctx, latestJoinCodeForTeam, teamID)
	var i LatestJoinCodeForTeamRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Generation,
		&i.PepperKeyID,
		&i.CodeDigest,
		&i.Status,
		&i.CreatedAt,
		&i.RetiredAt,
		&i.DisabledAt,
	)
	return i, err
}

const listProjectsForTeam = `-- name: ListProjectsForTeam :many
SELECT projects.id, projects.team_id, projects.name, projects.project_type,
       projects.state, projects.captured_through, projects.created_at,
       projects.updated_at, projects.archived_at, projects.deleted_at,
       aliases.remote_identity
FROM canonical_projects projects
LEFT JOIN team_project_repository_aliases aliases
       ON aliases.project_id = projects.id AND aliases.current
WHERE projects.team_id = $1 AND projects.state <> 'deleted'
ORDER BY lower(projects.name), projects.id
`

type ListProjectsForTeamRow struct {
	ID              string
	TeamID          string
	Name            string
	ProjectType     string
	State           string
	CapturedThrough time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
	ArchivedAt      pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	RemoteIdentity  *string
}

func (q *Queries) ListProjectsForTeam(ctx context.Context, teamID string) ([]ListProjectsForTeamRow, error) {
	rows, err := q.db.Query(ctx, listProjectsForTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsForTeamRow{}
	for rows.Next() {
		var i ListProjectsForTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.ProjectType,
			&i.State,
			&i.CapturedThrough,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.RemoteIdentity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT memberships.team_id, memberships.user_id, memberships.role,
       memberships.created_at, memberships.updated_at,
       users.display_name, users.avatar_url
FROM team_memberships memberships
JOIN auth_users users ON users.id = memberships.user_id
WHERE memberships.team_id = $1
  AND memberships.status = 'active'
  AND users.status = 'active'
ORDER BY lower(users.display_name), memberships.user_id
`

type ListTeamMembersRow struct {
	TeamID      string
	UserID      pgtype.UUID
	Role        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DisplayName string
	AvatarUrl   string
}

func (q *Queries) ListTeamMembers(ctx context.Context, teamID string) ([]ListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamMembersRow{}
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.TeamID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleProjects = `-- name: ListVisibleProjects :many
SELECT projects.id, projects.team_id, projects.name, projects.project_type,
       projects.state, projects.captured_through, projects.created_at,
       projects.updated_at, projects.archived_at, projects.deleted_at,
       aliases.remote_identity
FROM canonical_projects projects
JOIN team_memberships memberships
     ON memberships.team_id = projects.team_id
    AND memberships.user_id = $1
    AND memberships.status = 'active'
LEFT JOIN team_project_repository_aliases aliases
       ON aliases.project_id = projects.id AND aliases.current
WHERE projects.state <> 'deleted'
ORDER BY projects.team_id, lower(projects.name), projects.id
`

type ListVisibleProjectsRow struct {
	ID              string
	TeamID          string
	Name            string
	ProjectType     string
	State           string
	CapturedThrough time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
	ArchivedAt      pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	RemoteIdentity  *string
}

func (q *Queries) ListVisibleProjects(ctx context.Context, userID pgtype.UUID) ([]ListVisibleProjectsRow, error) {
	rows, err := q.db.Query(ctx, listVisibleProjects, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisibleProjectsRow{}
	for rows.Next() {
		var i ListVisibleProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.ProjectType,
			&i.State,
			&i.CapturedThrough,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.RemoteIdentity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleTeams = `-- name: ListVisibleTeams :many
SELECT teams.id, teams.slug, teams.name, teams.created_at, teams.updated_at,
       memberships.role, memberships.created_at AS membership_created_at,
       memberships.updated_at AS membership_updated_at
FROM team_memberships memberships
JOIN workspace_teams teams ON teams.id = memberships.team_id
WHERE memberships.user_id = $1
  AND memberships.status = 'active'
  AND teams.slug IS NOT NULL
ORDER BY lower(teams.name), teams.id
`

type ListVisibleTeamsRow struct {
	ID                  string
	Slug                *string
	Name                string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	Role                string
	MembershipCreatedAt time.Time
	MembershipUpdatedAt time.Time
}

func (q *Queries) ListVisibleTeams(ctx context.Context, userID pgtype.UUID) ([]ListVisibleTeamsRow, error) {
	rows, err := q.db.Query(ctx, listVisibleTeams, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisibleTeamsRow{}
	for rows.Next() {
		var i ListVisibleTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.MembershipCreatedAt,
			&i.MembershipUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const makeRepositoryAliasCurrent = `-- name: MakeRepositoryAliasCurrent :execrows
UPDATE team_project_repository_aliases
SET current = TRUE
WHERE project_id = $1 AND remote_identity = $2
`

type MakeRepositoryAliasCurrentParams struct {
	ProjectID      string
	RemoteIdentity string
}

func (q *Queries) MakeRepositoryAliasCurrent(ctx context.Context, arg MakeRepositoryAliasCurrentParams) (int64, error) {
	result, err := q.db.Exec(ctx, makeRepositoryAliasCurrent, arg.ProjectID, arg.RemoteIdentity)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRepositoryAliasesNonCurrent = `-- name: MarkRepositoryAliasesNonCurrent :exec
UPDATE team_project_repository_aliases
SET current = FALSE
WHERE project_id = $1 AND current
`

func (q *Queries) MarkRepositoryAliasesNonCurrent(ctx context.Context, projectID string) error {
	_, err := q.db.Exec(ctx, markRepositoryAliasesNonCurrent, projectID)
	return err
}

const reactivateMemberMembership = `-- name: ReactivateMemberMembership :one
UPDATE team_memberships
SET role = 'member', status = 'active', updated_at = clock_timestamp(), removed_at = NULL
WHERE team_id = $1 AND user_id = $2 AND status = 'removed'
RETURNING team_id, user_id, role, status, created_at, updated_at, removed_at
`

type ReactivateMemberMembershipParams struct {
	TeamID string
	UserID pgtype.UUID
}

func (q *Queries) ReactivateMemberMembership(ctx context.Context, arg ReactivateMemberMembershipParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, reactivateMemberMembership, arg.TeamID, arg.UserID)
	var i TeamMembership
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const recordJoinCodeFailure = `-- name: RecordJoinCodeFailure :one
INSERT INTO team_join_code_attempt_windows (
    user_id, window_start, failure_count, blocked_until
) VALUES ($1, $2, 1, NULL)
ON CONFLICT (user_id, window_start) DO UPDATE
SET failure_count = team_join_code_attempt_windows.failure_count + 1,
    blocked_until = CASE
        WHEN team_join_code_attempt_windows.failure_count + 1 >= $3::integer
        THEN $4::timestamptz
        ELSE team_join_code_attempt_windows.blocked_until
    END,
    updated_at = clock_timestamp()
RETURNING failure_count, blocked_until
`

type RecordJoinCodeFailureParams struct {
	UserID          pgtype.UUID
	WindowStart     time.Time
	MaximumFailures int32
	WindowEnd       time.Time
}

type RecordJoinCodeFailureRow struct {
	FailureCount int32
	BlockedUntil pgtype.Timestamptz
}

func (q *Queries) RecordJoinCodeFailure(ctx context.Context, arg RecordJoinCodeFailureParams) (RecordJoinCodeFailureRow, error) {
	row := q.db.QueryRow(ctx, recordJoinCodeFailure,
		arg.UserID,
		arg.WindowStart,
		arg.MaximumFailures,
		arg.WindowEnd,
	)
	var i RecordJoinCodeFailureRow
	err := row.Scan(&i.FailureCount, &i.BlockedUntil)
	return i, err
}

const removeMembership = `-- name: RemoveMembership :one
UPDATE team_memberships
SET status = 'removed', updated_at = clock_timestamp(), removed_at = clock_timestamp()
WHERE team_id = $1 AND user_id = $2 AND status = 'active'
RETURNING team_id, user_id, role, status, created_at, updated_at, removed_at
`

type RemoveMembershipParams struct {
	TeamID string
	UserID pgtype.UUID
}

func (q *Queries) RemoveMembership(ctx context.Context, arg RemoveMembershipParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, removeMembership, arg.TeamID, arg.UserID)
	var i TeamMembership
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const renameFolderProject = `-- name: RenameFolderProject :one
UPDATE canonical_projects
SET name = $2, updated_at = clock_timestamp()
WHERE id = $1 AND project_type = 'directory' AND state <> 'deleted'
RETURNING id, team_id, name, project_type, state, captured_through,
          created_at, updated_at, archived_at, deleted_at
`

type RenameFolderProjectParams struct {
	ID   string
	Name string
}

type RenameFolderProjectRow struct {
	ID              string
	TeamID          string
	Name            string
	ProjectType     string
	State           string
	CapturedThrough time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
	ArchivedAt      pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

func (q *Queries) RenameFolderProject(ctx context.Context, arg RenameFolderProjectParams) (RenameFolderProjectRow, error) {
	row := q.db.QueryRow(ctx, renameFolderProject, arg.ID, arg.Name)
	var i RenameFolderProjectRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.ProjectType,
		&i.State,
		&i.CapturedThrough,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
	)
	return i, err
}

const renameGitProject = `-- name: RenameGitProject :exec
UPDATE canonical_projects
SET name = $2, updated_at = clock_timestamp()
WHERE id = $1 AND project_type = 'git' AND state <> 'deleted'
`

type RenameGitProjectParams struct {
	ID   string
	Name string
}

func (q *Queries) RenameGitProject(ctx context.Context, arg RenameGitProjectParams) error {
	_, err := q.db.Exec(ctx, renameGitProject, arg.ID, arg.Name)
	return err
}

const retireCurrentJoinCode = `-- name: RetireCurrentJoinCode :execrows
UPDATE team_join_codes
SET status = 'retired', retired_at = clock_timestamp()
WHERE team_id = $1 AND status = 'enabled'
`

func (q *Queries) RetireCurrentJoinCode(ctx context.Context, teamID string) (int64, error) {
	result, err := q.db.Exec(ctx, retireCurrentJoinCode, teamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMembershipRole = `-- name: SetMembershipRole :one
UPDATE team_memberships
SET role = $3, updated_at = clock_timestamp()
WHERE team_id = $1 AND user_id = $2 AND status = 'active'
RETURNING team_id, user_id, role, status, created_at, updated_at, removed_at
`

type SetMembershipRoleParams struct {
	TeamID string
	UserID pgtype.UUID
	Role   string
}

func (q *Queries) SetMembershipRole(ctx context.Context, arg SetMembershipRoleParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, setMembershipRole, arg.TeamID, arg.UserID, arg.Role)
	var i TeamMembership
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const softDeleteProject = `-- name: SoftDeleteProject :one
UPDATE canonical_projects
SET state = 'deleted', deleted_at = COALESCE(deleted_at, clock_timestamp()),
    updated_at = CASE WHEN state <> 'deleted' THEN clock_timestamp() ELSE updated_at END
WHERE id = $1
RETURNING id, team_id, name, project_type, state, captured_through,
          created_at, updated_at, archived_at, deleted_at
`

type SoftDeleteProjectRow struct {
	ID              string
	TeamID          string
	Name            string
	ProjectType     string
	State           string
	CapturedThrough time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
	ArchivedAt      pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

func (q *Queries) SoftDeleteProject(ctx context.Context, id string) (SoftDeleteProjectRow, error) {
	row := q.db.QueryRow(ctx, softDeleteProject, id)
	var i SoftDeleteProjectRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.ProjectType,
		&i.State,
		&i.CapturedThrough,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTeamDisplayName = `-- name: UpdateTeamDisplayName :one
UPDATE workspace_teams
SET name = $2, updated_at = clock_timestamp()
WHERE id = $1
RETURNING id, slug, name, created_at, updated_at
`

type UpdateTeamDisplayNameParams struct {
	ID   string
	Name string
}

type UpdateTeamDisplayNameRow struct {
	ID        string
	Slug      *string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpdateTeamDisplayName(ctx context.Context, arg UpdateTeamDisplayNameParams) (UpdateTeamDisplayNameRow, error) {
	row := q.db.QueryRow(ctx, updateTeamDisplayName, arg.ID, arg.Name)
	var i UpdateTeamDisplayNameRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
