import { expect, test } from "@playwright/test"

test.beforeEach(async ({ context, request }) => {
  await request.post("http://127.0.0.1:8080/__fixture/reset")
  await context.addCookies([{ name: "fixture_session", value: "1", url: "http://127.0.0.1:4187" }])
})
test("lands on Team Overview, exposes cache, drills down and restores navigation", async ({ page }) => {
  await page.goto("/")
  await expect(page).toHaveURL(/\/teams\/team-id$/)
  await expect(page.getByRole("heading", { name: "Overview", exact: true })).toBeVisible()
  await expect(page.locator(".overview-metric")).toHaveCount(6)
  await expect(page.locator(".overview-metrics").getByText("Cache read", { exact: true })).toBeVisible()
  await expect(page.getByRole("region", { name: "Overview filters" })).toHaveCount(0)
  await page.getByLabel("Time range", { exact: true }).selectOption("7")
  await page.getByRole("button", { name: /^Filters/ }).click()
  await page.getByLabel("Model", { exact: true }).selectOption("model-a")
  await expect(page).toHaveURL(/model=model-a/)
  await page.getByRole("button", { name: /^Filters/ }).click()
  await expect(page.getByRole("region", { name: "Overview filters" })).toHaveCount(0)
  await page.getByRole("button", { name: "Open sessions", exact: true }).click()
  await expect(page.getByRole("heading", { name: "Sessions", exact: true })).toBeVisible()
  await page.evaluate(() => window.scrollTo(0, 450))
  const priorScroll = await page.evaluate(() => window.scrollY)
  await page.getByRole("button", { name: "Conversation hierarchy", exact: true }).first().click()
  await expect(page).toHaveURL(/sessions\/session-reader/)
  await page.goBack()
  await expect(page.getByRole("button", { name: "Remove model filter: model-a" })).toBeVisible()
  await expect(page.getByRole("heading", { name: "Sessions", exact: true })).toBeVisible()
  await expect.poll(() => page.evaluate(() => window.scrollY)).toBe(priorScroll)
  await page.getByRole("button", { name: "Next", exact: true }).click()
  await expect(page.getByText("24 sessions · Page 2")).toBeVisible()
  await page.reload()
  await expect(page.getByText("24 sessions · Page 2")).toBeVisible()
  await page.getByRole("button", { name: "Remove model filter: model-a" }).click()
  await expect(page).not.toHaveURL(/model=model-a/)
  await expect(page.getByText("24 sessions · Page 1")).toBeVisible()
})
test("updates conversation cards on manual refresh and retains successful data on failure", async ({ page, request }) => {
  await page.goto("/teams/team-id")
  await expect(page.locator(".overview-session").first()).toContainText("Conversation hierarchy")
  await page.clock.install()
  await request.post("http://127.0.0.1:8080/__fixture/overview?revision=1")
  await page.clock.fastForward(60_000)
  await expect(page.locator(".overview-session").first()).toContainText("Conversation hierarchy")
  await page.getByRole("button", { name: "Refresh", exact: true }).click()
  await expect(page.locator(".overview-session").first()).toContainText("New conversation arrived")
  await request.post("http://127.0.0.1:8080/__fixture/overview?fail=1")
  await page.getByRole("button", { name: "Refresh", exact: true }).click()
  await expect(page.getByRole("alert")).toContainText("last successful update")
  await expect(page.locator(".overview-metric")).toHaveCount(6)
})
test("remains readable without document overflow at supported widths", async ({ page }) => {
  await page.goto("/teams/team-id")
  await expect(page.getByRole("heading", { name: "Overview", exact: true })).toBeVisible()
  for (const width of [375, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: 1000 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
    await expect(page.locator(".overview-metrics").getByText("Cache write", { exact: true })).toBeVisible()
  }
  await page.getByLabel("Chart metric").selectOption("tokens")
  await page.getByText("View exact chart values").click()
  const first = page.locator(".overview-chart-data tbody button").first()
  await first.focus()
  await page.keyboard.press("Enter")
  await expect(page.getByRole("heading", { name: "Sessions", exact: true })).toBeVisible()
})

test("clears the previous dashboard when Team access is revoked", async ({ page }) => {
  await page.goto("/teams/team-id")
  await expect(page.locator(".overview-metric")).toHaveCount(6)
  await page.route("**/api/v1/teams/team-id/overview*", route => route.fulfill({ status: 403, json: { code: "forbidden", message: "Team access was revoked." } }))
  await page.getByRole("button", { name: "Refresh", exact: true }).click()
  await expect(page.getByRole("alert")).toBeVisible()
  await expect(page.locator(".overview-metric")).toHaveCount(0)
  await expect(page.locator(".overview-session")).toHaveCount(0)
})
