import { readFileSync,statSync } from "node:fs"
import { mkdtemp,rm } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { DatabaseSync } from "node:sqlite"
import { Effect,Layer } from "effect"
import { CaptureJournal,PublicationTransport,PublicationError,beginPublicationCapture,preparePublicationCanonical,deliverPublicationCapture,makeSecretRedactorLayer } from "capacity-application"
import { PublicationProtocol,PublicationTargetProfile } from "capacity-domain"
import { openOpenCodeCapture } from "capacity-source-capture"
import { openCodeOriginKey } from "capacity-source-origin"
import { makeCaptureJournalLayer } from "capacity-journal"
const [mode="clean"]=process.argv.slice(2),count=10000,rawEnabled=true
const dir=await mkdtemp(join(tmpdir(),"atape-retention-case-")),sourcePath=join(dir,"source.sqlite"),journalPath=join(dir,"journal.sqlite")
const MiB=1024*1024,at="2026-09-11T00:00:00Z"
const sourceLimits={rowBytes:MiB,pageBytes:4*MiB,pageRows:100,records:100000,threads:20,durationMs:115000}
const projection={events:20000,usage:20000,pageItems:100,pageBytes:4*MiB}
const journalLimits={unitBytes:5*MiB,targetBytes:128*MiB,pendingBytes:256*MiB,unitsPerTarget:4096,recordsPerTarget:100000,metadataEntries:110000}
const rawLimits={objectBytes:3*MiB,wireBytes:5*MiB,targetBytes:96*MiB,units:4096}
const binding={instanceOrigin:"https://capacity.example.test",userId:"synthetic-user",installationId:"synthetic-installation"}
const native=JSON.parse(readFileSync(new URL("./native-fixture.json",import.meta.url),"utf8"))
const root=native.rows.session.find((v:any)=>v.id===native.rootID),creation=native.rows.event.find((v:any)=>v.aggregate_id===native.rootID)
const scope={projectId:"synthetic-project",adapterId:"opencode",sourceSessionId:native.rootID,originKey:openCodeOriginKey(native.rootID,creation.id)}
const errorInfo=(e:any)=>({_tag:e?._tag,reason:e?.reason,message:e?.message})
const size=(p:string)=>{try{return statSync(p).size}catch{return 0}}
const files=()=>({db:size(journalPath),wal:size(journalPath+"-wal"),shm:size(journalPath+"-shm")})
const stats=()=>{const d=new DatabaseSync(journalPath,{readOnly:true});try{return{files:files(),account:d.prepare("SELECT retained_bytes,metadata_entries FROM binding").get(),tables:Object.fromEntries(["scopes","captures","units","source_record_versions","capture_records"].map(t=>[t,d.prepare(`SELECT count(*) n FROM ${t}`).get().n])),units:d.prepare("SELECT kind,count(*) units,sum(byte_count) bytes FROM units GROUP BY kind").all()}}finally{d.close()}}
function populate(n:number){const db=new DatabaseSync(sourcePath);try{if(n===1&&mode==="target-limit"||!db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='session'").get()){db.exec("PRAGMA foreign_keys=OFF");for(const ddl of native.ddl)db.exec(ddl);for(const row of native.rows.project??[])insert(db,"project",row);insert(db,"session",{...root,revert:null,time_updated:root.time_created+count+1000});insert(db,"event",creation)}db.exec("BEGIN");db.exec("DELETE FROM part;DELETE FROM message");const m=db.prepare("INSERT INTO message(id,session_id,time_created,time_updated,data) VALUES(?,?,?,?,?)"),p=db.prepare("INSERT INTO part(id,message_id,session_id,time_created,time_updated,data) VALUES(?,?,?,?,?,?)");for(let i=0;i<n;i++){const id="msg_capacity_"+String(i).padStart(8,"0"),part="prt_capacity_"+String(i).padStart(8,"0"),time=root.time_created+100+i;const prefix=`观察 ${String(i).padStart(8,"0")} 🚀 `;const text=prefix+"x".repeat(1024-Buffer.byteLength(prefix));m.run(id,native.rootID,time,time,JSON.stringify({role:"user",time:{created:time},agent:"build",model:{providerID:"synthetic",modelID:"capacity"}}));p.run(part,id,native.rootID,time,time,JSON.stringify({type:"text",text,metadata:{capacityFixture:true}}))}db.exec("COMMIT")}finally{db.close()}}
function insert(db:any,t:string,row:any){const k=Object.keys(row);db.prepare(`INSERT INTO ${t} (${k.map(x=>`"${x}"`).join(",")}) VALUES (${k.map(()=>"?").join(",")})`).run(...Object.values(row))}
const caps:any={protocol:PublicationProtocol,targetProfile:PublicationTargetProfile,limits:{partBytes:4*MiB,targetBytes:128*MiB,userPendingBytes:256*MiB,parts:4096,reservations:10,reservationLifetimeMs:60000,leaseLifetimeMs:60000},statusPageSize:100,reclaimPageSize:32}
let serial=0,attempt:any,contentTransportCalls=0
const remote=Layer.succeed(PublicationTransport,PublicationTransport.of({capabilities:()=>Effect.succeed(caps),reserve:()=>Effect.sync(()=>({id:"attempt-"+(++serial),sessionId:"synthetic-session",expiresAt:at})),begin:(_:any,b:any)=>Effect.sync(()=>{attempt={...b,id:b.reservationId,sessionId:"synthetic-session",fence:serial,leaseUntil:at,expiresAt:at,state:"open",parts:0,retainedBytes:0,seal:null,validatedParts:0,candidateEvents:0,candidateUsage:0,activation:null};return structuredClone(attempt)}),status:()=>Effect.succeed(structuredClone(attempt)),renew:()=>Effect.succeed(structuredClone(attempt)),put:(_:any,_id:any,part:any)=>Effect.sync(()=>{contentTransportCalls++;attempt.parts++;attempt.retainedBytes+=part.bytes;return part}),seal:(_:any,_id:any,manifest:any)=>Effect.sync(()=>{contentTransportCalls++;attempt.state="sealed";attempt.seal=manifest;return structuredClone(attempt)}),validate:()=>Effect.sync(()=>{contentTransportCalls++;attempt.validatedParts=attempt.parts;attempt.state="validated";return structuredClone(attempt)}),activate:()=>Effect.sync(()=>{contentTransportCalls++;const receipt={head:attempt.id,sessionId:attempt.sessionId,captureId:attempt.captureId,baseHead:attempt.baseHead,fence:attempt.fence,transformVersion:attempt.transformVersion,manifest:attempt.seal,activatedAt:at};attempt.state="activated";attempt.activation=receipt;return receipt}),reject:()=>Effect.fail(new PublicationError({reason:"unavailable",message:"unexpected reject in capacity fixture"}))}))
const source=()=>openOpenCodeCapture({path:sourcePath,sessionId:native.rootID,rawEnabled,limits:sourceLimits,projection})
const authority={protocol:"atape.raw-publication.v1",teamRevision:1,userRevision:1} as const

const assert=(value:unknown,message:string)=>{if(!value)throw new Error(message)}
const ledger=()=>{const d=new DatabaseSync(journalPath,{readOnly:true});try{const s=stats();const entries=Object.values(s.tables).reduce((a:any,b:any)=>a+b,0);assert(entries===s.account.metadata_entries,"metadata ledger does not match actual rows");const captures=d.prepare("SELECT id,state,records_retired,retained_records,record_count,retained_bytes FROM captures ORDER BY id").all();assert(captures.reduce((a:any,c:any)=>a+c.retained_records,0)===s.tables.capture_records,"retained membership ledger mismatch");return{...s,verifiedMetadataRows:entries,captures,pendingUnits:d.prepare("SELECT count(*) n FROM units WHERE disposition='pending'").get().n,retainedUnits:d.prepare("SELECT count(*) n FROM units WHERE body IS NOT NULL").get().n,rssBytes:process.memoryUsage().rss,processMaxRSSKiB:process.resourceUsage().maxRSS}}finally{d.close()}}
function mutate(round:number){const d=new DatabaseSync(sourcePath);try{const row:any=d.prepare("SELECT data FROM part WHERE id=?").get("prt_capacity_00000000");const data=JSON.parse(row.data);data.text=data.text.slice(0,-1)+String(round);assert(Buffer.byteLength(data.text)===1024,"mutation changes text size");d.prepare("UPDATE part SET data=? WHERE id=?").run(JSON.stringify(data),"prt_capacity_00000000")}finally{d.close()}}
const startTotal=performance.now();const output:any={mode,baseline:JSON.parse(readFileSync(new URL("./build-provenance.json",import.meta.url),"utf8")).checkoutCommit,dir,count,rawEnabled,textBytes:1024,node:process.version,platform:process.platform,arch:process.arch,limits:{source:sourceLimits,projection,journal:journalLimits,raw:rawLimits,remote:caps.limits},receiptEvidence:"Canonical PublicationTransport TestAdapter; Raw public journal RawAcknowledged contract settlement. No HTTP or real remote ACK.",rounds:[]}
console.log(JSON.stringify({type:"start",...output}));populate(count)
try{await Effect.runPromise(Effect.gen(function*(){const j=yield* CaptureJournal;let owner=yield* j.claim(scope);let previous=new Map<string,any>();let initial=new Map<string,any>();let changedKey:string|undefined;let baseHead="";
for(let round=1;round<=(mode==="clean"?5:3);round++){
 if(round>1)yield* Effect.sync(()=>mutate(round));const id="capture-"+round;const item:any={round,id};output.rounds.push(item);
 yield* beginPublicationCapture(owner,{captureId:id,baseHead,transformVersion:"capacity-v1",rawEnabled:true,trackRecords:true,rawAuthority:authority});const t=performance.now();
 const prep=yield* preparePublicationCanonical(owner,id,{adapterVersion:"0.0.0",observedAt:at,nextCheckpoint:"round-"+round,source:source(),rawLimits}).pipe(Effect.match({onSuccess:value=>({ok:true,value}),onFailure:error=>({ok:false,error:errorInfo(error)})}));item.preparationMs=performance.now()-t;item.prepared=prep;item.afterPreparation=yield* Effect.sync(ledger);
 if(!prep.ok){const cap=(yield* j.inspect(owner,id,{kind:"canonical",limit:1})).capture;item.failedCapture={state:cap.state,seal:cap.seal,activationReceipt:cap.activationReceipt};item.coverage=yield* j.coverage(owner);assert(mode==="control"&&round===3&&prep.error.reason==="capacity","unexpected preparation failure");assert(cap.state==="preparing"&&cap.seal===null&&cap.activationReceipt===null,"capacity failure exposed new candidate");assert(item.coverage.canonicalCaptureId==="capture-2","capacity failure moved current head");output.expectedControlFailure=true;console.log(JSON.stringify({type:"round",...item}));break}
 const current=new Map<string,any>();let afterKey:string|undefined;while(true){const page=yield* j.records(owner,id,{kind:"event",limit:100,...(afterKey?{afterKey}:{})});if(page.length===0)break;for(const v of page)current.set(v.key,{fingerprint:v.fingerprint,revision:v.revision,rawReference:v.rawReference});afterKey=page.at(-1)!.key}
 assert(current.size===10000,"current Event membership incomplete");let changed=0,stableRefs=0;for(const [key,v]of current){assert(v.rawReference?._tag==="object","Event has no Raw object ref");if(round===1)continue;const prev=previous.get(key);assert(prev,"Event key changed");if(v.fingerprint!==prev.fingerprint){changed++;if(changedKey===undefined)changedKey=key;assert(key===changedKey,"another Event changed");assert(v.revision===prev.revision+1,"changed version not monotonic")}else{assert(v.revision===prev.revision,"unchanged version changed");assert(JSON.stringify(v.rawReference)===JSON.stringify(prev.rawReference),"unchanged Raw ref changed");stableRefs++}if(key!==changedKey){assert(JSON.stringify(v.rawReference)===JSON.stringify(initial.get(key)?.rawReference),"original Raw ref lost")}}
 if(round>1)assert(changed===1&&stableRefs===9999,"expected exactly one changed Event");else initial=current;previous=current;item.currentEventCount=current.size;item.changedEvents=changed;item.stableOriginalRawRefs=round===1?10000:stableRefs;
 const cleanupStart=performance.now();const delivery=yield* deliverPublicationCapture(owner,id,64);item.delivery=delivery;const activated=(yield* j.inspect(owner,id,{kind:"canonical",limit:1})).capture;assert(activated.activationReceipt!==null,"TestAdapter did not activate");baseHead=JSON.parse(activated.activationReceipt!).head;
 let rawSettled=0;while(true){const page=yield* j.inspect(owner,id,{kind:"raw",pendingOnly:true,limit:100});if(page.units.length===0)break;for(const unit of page.units){yield* j.settle(owner,id,{_tag:"RawAcknowledged",ordinal:unit.ordinal,receiptJson:JSON.stringify({fixture:"SIMULATED-MODULE-ACK-NOT-HTTP",captureId:id,ordinal:unit.ordinal})});rawSettled++}}
 let reclaimed=0;while(true){const n=yield* j.reclaim(owner,id,32);assert(n<=32,"reclaim exceeded bound");if(n===0)break;reclaimed+=n}item.rawUnitsSimulatedAcknowledged=rawSettled;item.payloadUnitsReclaimed=reclaimed;item.beforePrune=yield* Effect.sync(ledger);let pruned=0,maxBatch=0,batches=0;const pruneStart=performance.now();if(mode==="clean")while(true){const n=yield* j.pruneRecords(owner,100);assert(n<=100,"prune exceeded 100");if(n===0)break;pruned+=n;maxBatch=Math.max(maxBatch,n);batches++}item.pruneMs=performance.now()-pruneStart;item.cleanupMs=performance.now()-cleanupStart;item.prunedRecords=pruned;item.pruneBatches=batches;item.maxPruneBatch=maxBatch;item.afterCleanup=yield* Effect.sync(ledger);
 assert(item.beforePrune.account.metadata_entries-item.afterCleanup.account.metadata_entries===pruned,"metadata credit wrong");assert(item.afterCleanup.account.retained_bytes===0&&item.afterCleanup.retainedUnits===0&&item.afterCleanup.pendingUnits===0,"payload not fully settled/reclaimed");assert(item.afterCleanup.tables.source_record_versions===30003,"latest source version keys changed");if(mode==="clean"){assert(pruned===(round===1?0:30003),"unexpected pruned membership");assert(item.afterCleanup.tables.capture_records===30003,"current complete membership not retained")}
 item.coverage=yield* j.coverage(owner);assert(Object.values(item.coverage).every(v=>v===id),"current coverage moved unexpectedly");const oldUnits=(yield* j.inspect(owner,"capture-1",{kind:"raw",limit:100})).units;assert(oldUnits.length===100&&oldUnits.every(u=>u.disposition==="acknowledged"&&!u.retained&&u.receiptJson!==null),"old Raw identity/receipt proof lost");item.oldRawProofsChecked=oldUnits.length;owner=yield* j.claim(scope);assert(owner.checkpoint==="round-"+round,"checkpoint incorrect");item.checkpoint=owner.checkpoint;console.log(JSON.stringify({type:"round",...item}));
}
}).pipe(Effect.provide(Layer.mergeAll(remote,makeSecretRedactorLayer(),makeCaptureJournalLayer({path:journalPath,mode:"create",binding,limits:journalLimits})))));output.ok=true}catch(e){output.ok=false;output.error={...errorInfo(e),stack:String(e)}}
output.elapsedMs=performance.now()-startTotal;output.afterClose=files();output.resources=process.resourceUsage();console.log(JSON.stringify({type:"final",...output}));if(!output.ok)process.exitCode=1
