// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: authorization.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSessionBatchReceipts = `-- name: DeleteSessionBatchReceipts :exec
DELETE FROM canonical_batch_receipts WHERE session_id = $1
`

func (q *Queries) DeleteSessionBatchReceipts(ctx context.Context, sessionID string) error {
	_, err := q.db.Exec(ctx, deleteSessionBatchReceipts, sessionID)
	return err
}

const deleteSessionProjectionChanges = `-- name: DeleteSessionProjectionChanges :exec
DELETE FROM canonical_projection_changes
WHERE event_id IN (SELECT id FROM canonical_events WHERE session_id = $1)
`

func (q *Queries) DeleteSessionProjectionChanges(ctx context.Context, sessionID string) error {
	_, err := q.db.Exec(ctx, deleteSessionProjectionChanges, sessionID)
	return err
}

const deleteSessionSearchDocuments = `-- name: DeleteSessionSearchDocuments :exec
DELETE FROM project_search_documents WHERE session_id = $1
`

func (q *Queries) DeleteSessionSearchDocuments(ctx context.Context, sessionID string) error {
	_, err := q.db.Exec(ctx, deleteSessionSearchDocuments, sessionID)
	return err
}

const insertResourceSecurityAuditEvent = `-- name: InsertResourceSecurityAuditEvent :exec
INSERT INTO security_audit_events (
    id, initiator_kind, initiator_id, action, target_kind, target_id,
    outcome, reason, request_id, web_session_id, cli_credential_id, metadata
) VALUES (
    $1, 'principal', $2, $3, $4, $5,
    'succeeded', $6, $7, $8, $9, '{}'::jsonb
)
`

type InsertResourceSecurityAuditEventParams struct {
	ID              pgtype.UUID
	InitiatorID     string
	Action          string
	TargetKind      string
	TargetID        string
	Reason          string
	RequestID       string
	WebSessionID    pgtype.UUID
	CliCredentialID pgtype.UUID
}

func (q *Queries) InsertResourceSecurityAuditEvent(ctx context.Context, arg InsertResourceSecurityAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertResourceSecurityAuditEvent,
		arg.ID,
		arg.InitiatorID,
		arg.Action,
		arg.TargetKind,
		arg.TargetID,
		arg.Reason,
		arg.RequestID,
		arg.WebSessionID,
		arg.CliCredentialID,
	)
	return err
}

const resolveCapturedSessionDeleteForUpdate = `-- name: ResolveCapturedSessionDeleteForUpdate :one
SELECT sessions.id, sessions.project_id, sessions.captured_by_user_id, sessions.record_state,
       projects.team_id, projects.state,
       membership.user_id, membership.role, membership.status
FROM canonical_sessions sessions
JOIN canonical_projects projects ON projects.id = sessions.project_id
JOIN team_memberships membership
  ON membership.team_id = projects.team_id
 AND membership.user_id = $1
JOIN auth_users users
  ON users.id = membership.user_id
 AND users.status = 'active'
WHERE sessions.id = $2
  AND projects.state <> 'deleted'
FOR UPDATE OF sessions, projects
FOR SHARE OF membership, users
`

type ResolveCapturedSessionDeleteForUpdateParams struct {
	UserID    pgtype.UUID
	SessionID string
}

type ResolveCapturedSessionDeleteForUpdateRow struct {
	ID               string
	ProjectID        string
	CapturedByUserID pgtype.UUID
	RecordState      string
	TeamID           string
	State            string
	UserID           pgtype.UUID
	Role             string
	Status           string
}

func (q *Queries) ResolveCapturedSessionDeleteForUpdate(ctx context.Context, arg ResolveCapturedSessionDeleteForUpdateParams) (ResolveCapturedSessionDeleteForUpdateRow, error) {
	row := q.db.QueryRow(ctx, resolveCapturedSessionDeleteForUpdate, arg.UserID, arg.SessionID)
	var i ResolveCapturedSessionDeleteForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CapturedByUserID,
		&i.RecordState,
		&i.TeamID,
		&i.State,
		&i.UserID,
		&i.Role,
		&i.Status,
	)
	return i, err
}

const resolveProjectAccess = `-- name: ResolveProjectAccess :one

SELECT projects.id, projects.team_id, projects.name, projects.project_type,
       projects.state, projects.captured_through,
       membership.user_id, membership.role, membership.status
FROM canonical_projects projects
JOIN team_memberships membership
  ON membership.team_id = projects.team_id
 AND membership.user_id = $1
JOIN auth_users users
  ON users.id = membership.user_id
 AND users.status = 'active'
WHERE projects.id = $2
  AND projects.state <> 'deleted'
`

type ResolveProjectAccessParams struct {
	UserID    pgtype.UUID
	ProjectID string
}

type ResolveProjectAccessRow struct {
	ID              string
	TeamID          string
	Name            string
	ProjectType     string
	State           string
	CapturedThrough time.Time
	UserID          pgtype.UUID
	Role            string
	Status          string
}

// Resource authorization queries deliberately join the current Membership.
// A missing resource and a resource outside the Principal's visible Teams
// therefore have the same no-row result.
func (q *Queries) ResolveProjectAccess(ctx context.Context, arg ResolveProjectAccessParams) (ResolveProjectAccessRow, error) {
	row := q.db.QueryRow(ctx, resolveProjectAccess, arg.UserID, arg.ProjectID)
	var i ResolveProjectAccessRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.ProjectType,
		&i.State,
		&i.CapturedThrough,
		&i.UserID,
		&i.Role,
		&i.Status,
	)
	return i, err
}

const resolveProjectAccessForIngest = `-- name: ResolveProjectAccessForIngest :one
SELECT projects.id, projects.team_id, projects.name, projects.project_type,
       projects.state, projects.captured_through,
       membership.user_id, membership.role, membership.status
FROM canonical_projects projects
JOIN team_memberships membership
  ON membership.team_id = projects.team_id
 AND membership.user_id = $1
JOIN auth_users users
  ON users.id = membership.user_id
 AND users.status = 'active'
WHERE projects.id = $2
  AND projects.state <> 'deleted'
FOR UPDATE OF projects
FOR SHARE OF membership, users
`

type ResolveProjectAccessForIngestParams struct {
	UserID    pgtype.UUID
	ProjectID string
}

type ResolveProjectAccessForIngestRow struct {
	ID              string
	TeamID          string
	Name            string
	ProjectType     string
	State           string
	CapturedThrough time.Time
	UserID          pgtype.UUID
	Role            string
	Status          string
}

func (q *Queries) ResolveProjectAccessForIngest(ctx context.Context, arg ResolveProjectAccessForIngestParams) (ResolveProjectAccessForIngestRow, error) {
	row := q.db.QueryRow(ctx, resolveProjectAccessForIngest, arg.UserID, arg.ProjectID)
	var i ResolveProjectAccessForIngestRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.ProjectType,
		&i.State,
		&i.CapturedThrough,
		&i.UserID,
		&i.Role,
		&i.Status,
	)
	return i, err
}

const resolveRawObjectAccess = `-- name: ResolveRawObjectAccess :one
SELECT objects.id, objects.project_id, objects.session_id,
       sessions.captured_by_user_id, projects.team_id, projects.state,
       membership.user_id, membership.role, membership.status
FROM raw_objects objects
JOIN canonical_sessions sessions ON sessions.id = objects.session_id
JOIN canonical_projects projects ON projects.id = objects.project_id
JOIN team_memberships membership
  ON membership.team_id = projects.team_id
 AND membership.user_id = $1
JOIN auth_users users
  ON users.id = membership.user_id
 AND users.status = 'active'
WHERE objects.id = $2
  AND sessions.record_state = 'active'
  AND projects.state <> 'deleted'
`

type ResolveRawObjectAccessParams struct {
	UserID   pgtype.UUID
	ObjectID string
}

type ResolveRawObjectAccessRow struct {
	ID               string
	ProjectID        string
	SessionID        string
	CapturedByUserID pgtype.UUID
	TeamID           string
	State            string
	UserID           pgtype.UUID
	Role             string
	Status           string
}

func (q *Queries) ResolveRawObjectAccess(ctx context.Context, arg ResolveRawObjectAccessParams) (ResolveRawObjectAccessRow, error) {
	row := q.db.QueryRow(ctx, resolveRawObjectAccess, arg.UserID, arg.ObjectID)
	var i ResolveRawObjectAccessRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SessionID,
		&i.CapturedByUserID,
		&i.TeamID,
		&i.State,
		&i.UserID,
		&i.Role,
		&i.Status,
	)
	return i, err
}

const resolveSessionAccess = `-- name: ResolveSessionAccess :one
SELECT sessions.id, sessions.project_id, sessions.captured_by_user_id,
       projects.team_id, projects.state,
       membership.user_id, membership.role, membership.status
FROM canonical_sessions sessions
JOIN canonical_projects projects ON projects.id = sessions.project_id
JOIN team_memberships membership
  ON membership.team_id = projects.team_id
 AND membership.user_id = $1
JOIN auth_users users
  ON users.id = membership.user_id
 AND users.status = 'active'
WHERE sessions.id = $2
  AND sessions.record_state = 'active'
  AND projects.state <> 'deleted'
`

type ResolveSessionAccessParams struct {
	UserID    pgtype.UUID
	SessionID string
}

type ResolveSessionAccessRow struct {
	ID               string
	ProjectID        string
	CapturedByUserID pgtype.UUID
	TeamID           string
	State            string
	UserID           pgtype.UUID
	Role             string
	Status           string
}

func (q *Queries) ResolveSessionAccess(ctx context.Context, arg ResolveSessionAccessParams) (ResolveSessionAccessRow, error) {
	row := q.db.QueryRow(ctx, resolveSessionAccess, arg.UserID, arg.SessionID)
	var i ResolveSessionAccessRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CapturedByUserID,
		&i.TeamID,
		&i.State,
		&i.UserID,
		&i.Role,
		&i.Status,
	)
	return i, err
}

const resolveSessionAccessForShare = `-- name: ResolveSessionAccessForShare :one
SELECT sessions.id, sessions.project_id, sessions.captured_by_user_id,
       projects.team_id, projects.state,
       membership.user_id, membership.role, membership.status
FROM canonical_sessions sessions
JOIN canonical_projects projects ON projects.id = sessions.project_id
JOIN team_memberships membership
  ON membership.team_id = projects.team_id
 AND membership.user_id = $1
JOIN auth_users users
  ON users.id = membership.user_id
 AND users.status = 'active'
WHERE sessions.id = $2
  AND sessions.record_state = 'active'
  AND projects.state <> 'deleted'
FOR SHARE OF sessions, projects, membership, users
`

type ResolveSessionAccessForShareParams struct {
	UserID    pgtype.UUID
	SessionID string
}

type ResolveSessionAccessForShareRow struct {
	ID               string
	ProjectID        string
	CapturedByUserID pgtype.UUID
	TeamID           string
	State            string
	UserID           pgtype.UUID
	Role             string
	Status           string
}

func (q *Queries) ResolveSessionAccessForShare(ctx context.Context, arg ResolveSessionAccessForShareParams) (ResolveSessionAccessForShareRow, error) {
	row := q.db.QueryRow(ctx, resolveSessionAccessForShare, arg.UserID, arg.SessionID)
	var i ResolveSessionAccessForShareRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CapturedByUserID,
		&i.TeamID,
		&i.State,
		&i.UserID,
		&i.Role,
		&i.Status,
	)
	return i, err
}

const tombstoneCapturedSession = `-- name: TombstoneCapturedSession :execrows
UPDATE canonical_sessions
SET record_state = 'deleted', deleted_at = clock_timestamp(), deleted_by_user_id = $2
WHERE id = $1 AND record_state = 'active'
`

type TombstoneCapturedSessionParams struct {
	ID              string
	DeletedByUserID pgtype.UUID
}

func (q *Queries) TombstoneCapturedSession(ctx context.Context, arg TombstoneCapturedSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, tombstoneCapturedSession, arg.ID, arg.DeletedByUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
