// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: canonical.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireCanonicalLock = `-- name: AcquireCanonicalLock :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

func (q *Queries) AcquireCanonicalLock(ctx context.Context, lockKey string) error {
	_, err := q.db.Exec(ctx, acquireCanonicalLock, lockKey)
	return err
}

const advanceProjectCapture = `-- name: AdvanceProjectCapture :exec
UPDATE canonical_projects
SET captured_through = GREATEST(captured_through, $1::timestamptz)
WHERE id = $2
`

type AdvanceProjectCaptureParams struct {
	ObservedAt time.Time
	ProjectID  string
}

func (q *Queries) AdvanceProjectCapture(ctx context.Context, arg AdvanceProjectCaptureParams) error {
	_, err := q.db.Exec(ctx, advanceProjectCapture, arg.ObservedAt, arg.ProjectID)
	return err
}

const getBatchReceipt = `-- name: GetBatchReceipt :one
SELECT batch_key, digest, session_id, session_created, inserted_events,
       updated_events, unchanged_events, stale_events
FROM canonical_batch_receipts
WHERE batch_key = $1
`

type GetBatchReceiptRow struct {
	BatchKey        string
	Digest          string
	SessionID       string
	SessionCreated  bool
	InsertedEvents  int32
	UpdatedEvents   int32
	UnchangedEvents int32
	StaleEvents     int32
}

func (q *Queries) GetBatchReceipt(ctx context.Context, batchKey string) (GetBatchReceiptRow, error) {
	row := q.db.QueryRow(ctx, getBatchReceipt, batchKey)
	var i GetBatchReceiptRow
	err := row.Scan(
		&i.BatchKey,
		&i.Digest,
		&i.SessionID,
		&i.SessionCreated,
		&i.InsertedEvents,
		&i.UpdatedEvents,
		&i.UnchangedEvents,
		&i.StaleEvents,
	)
	return i, err
}

const getEventByIDForUpdate = `-- name: GetEventByIDForUpdate :one
SELECT id, session_id, thread_id, source_key, revision, projection_revision,
       digest, source_order, event_index, order_fidelity, fidelity, raw_ref,
       adapter_version, schema_version, observed_at, received_at, ingest_seq,
       kind, author, occurred_at, text, tool_label, child_thread_id
FROM canonical_events
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetEventByIDForUpdate(ctx context.Context, id string) (CanonicalEvent, error) {
	row := q.db.QueryRow(ctx, getEventByIDForUpdate, id)
	var i CanonicalEvent
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ThreadID,
		&i.SourceKey,
		&i.Revision,
		&i.ProjectionRevision,
		&i.Digest,
		&i.SourceOrder,
		&i.EventIndex,
		&i.OrderFidelity,
		&i.Fidelity,
		&i.RawRef,
		&i.AdapterVersion,
		&i.SchemaVersion,
		&i.ObservedAt,
		&i.ReceivedAt,
		&i.IngestSeq,
		&i.Kind,
		&i.Author,
		&i.OccurredAt,
		&i.Text,
		&i.ToolLabel,
		&i.ChildThreadID,
	)
	return i, err
}

const getEventBySourceForUpdate = `-- name: GetEventBySourceForUpdate :one
SELECT id, session_id, thread_id, source_key, revision, projection_revision,
       digest, source_order, event_index, order_fidelity, fidelity, raw_ref,
       adapter_version, schema_version, observed_at, received_at, ingest_seq,
       kind, author, occurred_at, text, tool_label, child_thread_id
FROM canonical_events
WHERE source_key = $1
FOR UPDATE
`

func (q *Queries) GetEventBySourceForUpdate(ctx context.Context, sourceKey string) (CanonicalEvent, error) {
	row := q.db.QueryRow(ctx, getEventBySourceForUpdate, sourceKey)
	var i CanonicalEvent
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ThreadID,
		&i.SourceKey,
		&i.Revision,
		&i.ProjectionRevision,
		&i.Digest,
		&i.SourceOrder,
		&i.EventIndex,
		&i.OrderFidelity,
		&i.Fidelity,
		&i.RawRef,
		&i.AdapterVersion,
		&i.SchemaVersion,
		&i.ObservedAt,
		&i.ReceivedAt,
		&i.IngestSeq,
		&i.Kind,
		&i.Author,
		&i.OccurredAt,
		&i.Text,
		&i.ToolLabel,
		&i.ChildThreadID,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, team_id, name, captured_through, project_type
FROM canonical_projects
WHERE id = $1
`

type GetProjectRow struct {
	ID              string
	TeamID          string
	Name            string
	CapturedThrough time.Time
	ProjectType     string
}

func (q *Queries) GetProject(ctx context.Context, id string) (GetProjectRow, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i GetProjectRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.CapturedThrough,
		&i.ProjectType,
	)
	return i, err
}

const getProjectForRead = `-- name: GetProjectForRead :one
SELECT id, team_id, name, captured_through, project_type, state
FROM canonical_projects
WHERE id = $1
`

type GetProjectForReadRow struct {
	ID              string
	TeamID          string
	Name            string
	CapturedThrough time.Time
	ProjectType     string
	State           string
}

func (q *Queries) GetProjectForRead(ctx context.Context, id string) (GetProjectForReadRow, error) {
	row := q.db.QueryRow(ctx, getProjectForRead, id)
	var i GetProjectForReadRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.CapturedThrough,
		&i.ProjectType,
		&i.State,
	)
	return i, err
}

const getSessionForRead = `-- name: GetSessionForRead :one
SELECT id, project_id, source_key, revision, digest, title, summary, insight,
       actor_name, actor_harness, branch, status, capture_status, updated_at,
       reported_event_count, captured_by_user_id
FROM canonical_sessions
WHERE id = $1
`

func (q *Queries) GetSessionForRead(ctx context.Context, id string) (CanonicalSession, error) {
	row := q.db.QueryRow(ctx, getSessionForRead, id)
	var i CanonicalSession
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceKey,
		&i.Revision,
		&i.Digest,
		&i.Title,
		&i.Summary,
		&i.Insight,
		&i.ActorName,
		&i.ActorHarness,
		&i.Branch,
		&i.Status,
		&i.CaptureStatus,
		&i.UpdatedAt,
		&i.ReportedEventCount,
		&i.CapturedByUserID,
	)
	return i, err
}

const getSessionForUpdate = `-- name: GetSessionForUpdate :one
SELECT id, project_id, source_key, revision, digest, title, summary, insight,
       actor_name, actor_harness, branch, status, capture_status, updated_at,
       reported_event_count, captured_by_user_id
FROM canonical_sessions
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetSessionForUpdate(ctx context.Context, id string) (CanonicalSession, error) {
	row := q.db.QueryRow(ctx, getSessionForUpdate, id)
	var i CanonicalSession
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceKey,
		&i.Revision,
		&i.Digest,
		&i.Title,
		&i.Summary,
		&i.Insight,
		&i.ActorName,
		&i.ActorHarness,
		&i.Branch,
		&i.Status,
		&i.CaptureStatus,
		&i.UpdatedAt,
		&i.ReportedEventCount,
		&i.CapturedByUserID,
	)
	return i, err
}

const getTeam = `-- name: GetTeam :one
SELECT id, name
FROM workspace_teams
WHERE id = $1
`

type GetTeamRow struct {
	ID   string
	Name string
}

func (q *Queries) GetTeam(ctx context.Context, id string) (GetTeamRow, error) {
	row := q.db.QueryRow(ctx, getTeam, id)
	var i GetTeamRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getThreadForRead = `-- name: GetThreadForRead :one
SELECT session_id, id, source_key, revision, digest, label, summary,
       parent_thread_id, capture_status
FROM canonical_threads
WHERE session_id = $1 AND id = $2
`

type GetThreadForReadParams struct {
	SessionID string
	ID        string
}

func (q *Queries) GetThreadForRead(ctx context.Context, arg GetThreadForReadParams) (CanonicalThread, error) {
	row := q.db.QueryRow(ctx, getThreadForRead, arg.SessionID, arg.ID)
	var i CanonicalThread
	err := row.Scan(
		&i.SessionID,
		&i.ID,
		&i.SourceKey,
		&i.Revision,
		&i.Digest,
		&i.Label,
		&i.Summary,
		&i.ParentThreadID,
		&i.CaptureStatus,
	)
	return i, err
}

const getThreadForUpdate = `-- name: GetThreadForUpdate :one
SELECT session_id, id, source_key, revision, digest, label, summary,
       parent_thread_id, capture_status
FROM canonical_threads
WHERE session_id = $1 AND id = $2
FOR UPDATE
`

type GetThreadForUpdateParams struct {
	SessionID string
	ID        string
}

func (q *Queries) GetThreadForUpdate(ctx context.Context, arg GetThreadForUpdateParams) (CanonicalThread, error) {
	row := q.db.QueryRow(ctx, getThreadForUpdate, arg.SessionID, arg.ID)
	var i CanonicalThread
	err := row.Scan(
		&i.SessionID,
		&i.ID,
		&i.SourceKey,
		&i.Revision,
		&i.Digest,
		&i.Label,
		&i.Summary,
		&i.ParentThreadID,
		&i.CaptureStatus,
	)
	return i, err
}

const insertBatchReceipt = `-- name: InsertBatchReceipt :exec
INSERT INTO canonical_batch_receipts (
    batch_key, digest, session_id, session_created, inserted_events,
    updated_events, unchanged_events, stale_events
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertBatchReceiptParams struct {
	BatchKey        string
	Digest          string
	SessionID       string
	SessionCreated  bool
	InsertedEvents  int32
	UpdatedEvents   int32
	UnchangedEvents int32
	StaleEvents     int32
}

func (q *Queries) InsertBatchReceipt(ctx context.Context, arg InsertBatchReceiptParams) error {
	_, err := q.db.Exec(ctx, insertBatchReceipt,
		arg.BatchKey,
		arg.Digest,
		arg.SessionID,
		arg.SessionCreated,
		arg.InsertedEvents,
		arg.UpdatedEvents,
		arg.UnchangedEvents,
		arg.StaleEvents,
	)
	return err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO canonical_events (
    id, session_id, thread_id, source_key, revision, projection_revision,
    digest, source_order, event_index, order_fidelity, fidelity, raw_ref,
    adapter_version, schema_version, observed_at, received_at, ingest_seq,
    kind, author, occurred_at, text, tool_label, child_thread_id
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17,
    $18, $19, $20, $21, $22, $23
)
`

type InsertEventParams struct {
	ID                 string
	SessionID          string
	ThreadID           string
	SourceKey          string
	Revision           int64
	ProjectionRevision int64
	Digest             string
	SourceOrder        int64
	EventIndex         int64
	OrderFidelity      string
	Fidelity           string
	RawRef             string
	AdapterVersion     string
	SchemaVersion      string
	ObservedAt         time.Time
	ReceivedAt         time.Time
	IngestSeq          int64
	Kind               string
	Author             string
	OccurredAt         time.Time
	Text               string
	ToolLabel          string
	ChildThreadID      *string
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.ID,
		arg.SessionID,
		arg.ThreadID,
		arg.SourceKey,
		arg.Revision,
		arg.ProjectionRevision,
		arg.Digest,
		arg.SourceOrder,
		arg.EventIndex,
		arg.OrderFidelity,
		arg.Fidelity,
		arg.RawRef,
		arg.AdapterVersion,
		arg.SchemaVersion,
		arg.ObservedAt,
		arg.ReceivedAt,
		arg.IngestSeq,
		arg.Kind,
		arg.Author,
		arg.OccurredAt,
		arg.Text,
		arg.ToolLabel,
		arg.ChildThreadID,
	)
	return err
}

const insertEventVersion = `-- name: InsertEventVersion :exec
INSERT INTO canonical_event_versions (
    source_key, projection_revision, revision, event_id, session_id, thread_id,
    digest, source_order, event_index, order_fidelity, fidelity, raw_ref,
    adapter_version, schema_version, observed_at, received_at, ingest_seq,
    kind, author, occurred_at, text, tool_label, child_thread_id
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17,
    $18, $19, $20, $21, $22, $23
)
`

type InsertEventVersionParams struct {
	SourceKey          string
	ProjectionRevision int64
	Revision           int64
	EventID            string
	SessionID          string
	ThreadID           string
	Digest             string
	SourceOrder        int64
	EventIndex         int64
	OrderFidelity      string
	Fidelity           string
	RawRef             string
	AdapterVersion     string
	SchemaVersion      string
	ObservedAt         time.Time
	ReceivedAt         time.Time
	IngestSeq          int64
	Kind               string
	Author             string
	OccurredAt         time.Time
	Text               string
	ToolLabel          string
	ChildThreadID      *string
}

func (q *Queries) InsertEventVersion(ctx context.Context, arg InsertEventVersionParams) error {
	_, err := q.db.Exec(ctx, insertEventVersion,
		arg.SourceKey,
		arg.ProjectionRevision,
		arg.Revision,
		arg.EventID,
		arg.SessionID,
		arg.ThreadID,
		arg.Digest,
		arg.SourceOrder,
		arg.EventIndex,
		arg.OrderFidelity,
		arg.Fidelity,
		arg.RawRef,
		arg.AdapterVersion,
		arg.SchemaVersion,
		arg.ObservedAt,
		arg.ReceivedAt,
		arg.IngestSeq,
		arg.Kind,
		arg.Author,
		arg.OccurredAt,
		arg.Text,
		arg.ToolLabel,
		arg.ChildThreadID,
	)
	return err
}

const insertProject = `-- name: InsertProject :exec
INSERT INTO canonical_projects (id, team_id, name, project_type)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO NOTHING
`

type InsertProjectParams struct {
	ID          string
	TeamID      string
	Name        string
	ProjectType string
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) error {
	_, err := q.db.Exec(ctx, insertProject,
		arg.ID,
		arg.TeamID,
		arg.Name,
		arg.ProjectType,
	)
	return err
}

const insertProjectionChange = `-- name: InsertProjectionChange :exec
INSERT INTO canonical_projection_changes (event_id, event_ingest_seq, observed_at)
VALUES ($1, $2, $3)
`

type InsertProjectionChangeParams struct {
	EventID        string
	EventIngestSeq int64
	ObservedAt     time.Time
}

func (q *Queries) InsertProjectionChange(ctx context.Context, arg InsertProjectionChangeParams) error {
	_, err := q.db.Exec(ctx, insertProjectionChange, arg.EventID, arg.EventIngestSeq, arg.ObservedAt)
	return err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO canonical_sessions (
    id, project_id, source_key, revision, digest, title, summary, insight,
    actor_name, actor_harness, branch, status, capture_status, updated_at,
    reported_event_count, captured_by_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13, $14, $15, $16
)
`

type InsertSessionParams struct {
	ID                 string
	ProjectID          string
	SourceKey          string
	Revision           int64
	Digest             string
	Title              string
	Summary            string
	Insight            string
	ActorName          string
	ActorHarness       string
	Branch             string
	Status             string
	CaptureStatus      string
	UpdatedAt          time.Time
	ReportedEventCount int64
	CapturedByUserID   pgtype.UUID
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.ID,
		arg.ProjectID,
		arg.SourceKey,
		arg.Revision,
		arg.Digest,
		arg.Title,
		arg.Summary,
		arg.Insight,
		arg.ActorName,
		arg.ActorHarness,
		arg.Branch,
		arg.Status,
		arg.CaptureStatus,
		arg.UpdatedAt,
		arg.ReportedEventCount,
		arg.CapturedByUserID,
	)
	return err
}

const insertThread = `-- name: InsertThread :exec
INSERT INTO canonical_threads (
    session_id, id, source_key, revision, digest, label, summary,
    parent_thread_id, capture_status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertThreadParams struct {
	SessionID      string
	ID             string
	SourceKey      string
	Revision       int64
	Digest         string
	Label          string
	Summary        string
	ParentThreadID *string
	CaptureStatus  string
}

func (q *Queries) InsertThread(ctx context.Context, arg InsertThreadParams) error {
	_, err := q.db.Exec(ctx, insertThread,
		arg.SessionID,
		arg.ID,
		arg.SourceKey,
		arg.Revision,
		arg.Digest,
		arg.Label,
		arg.Summary,
		arg.ParentThreadID,
		arg.CaptureStatus,
	)
	return err
}

const listProjectSessions = `-- name: ListProjectSessions :many
SELECT s.id, s.project_id, s.source_key, s.revision, s.digest, s.title,
       s.summary, s.insight, s.actor_name, s.actor_harness, s.branch,
       s.status, s.capture_status, s.updated_at, s.reported_event_count,
       s.captured_by_user_id,
       GREATEST(
           s.reported_event_count,
           (SELECT COUNT(*) FROM canonical_events e WHERE e.session_id = s.id)
       )::bigint AS event_count,
       (
           SELECT COUNT(*)
           FROM canonical_threads child
           WHERE child.session_id = s.id AND child.parent_thread_id IS NOT NULL
       )::bigint AS child_thread_count
FROM canonical_sessions s
WHERE s.project_id = $1
ORDER BY s.updated_at DESC, s.id
`

type ListProjectSessionsRow struct {
	ID                 string
	ProjectID          string
	SourceKey          string
	Revision           int64
	Digest             string
	Title              string
	Summary            string
	Insight            string
	ActorName          string
	ActorHarness       string
	Branch             string
	Status             string
	CaptureStatus      string
	UpdatedAt          time.Time
	ReportedEventCount int64
	CapturedByUserID   pgtype.UUID
	EventCount         int64
	ChildThreadCount   int64
}

func (q *Queries) ListProjectSessions(ctx context.Context, projectID string) ([]ListProjectSessionsRow, error) {
	rows, err := q.db.Query(ctx, listProjectSessions, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectSessionsRow{}
	for rows.Next() {
		var i ListProjectSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourceKey,
			&i.Revision,
			&i.Digest,
			&i.Title,
			&i.Summary,
			&i.Insight,
			&i.ActorName,
			&i.ActorHarness,
			&i.Branch,
			&i.Status,
			&i.CaptureStatus,
			&i.UpdatedAt,
			&i.ReportedEventCount,
			&i.CapturedByUserID,
			&i.EventCount,
			&i.ChildThreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionThreads = `-- name: ListSessionThreads :many
SELECT t.session_id, t.id, t.source_key, t.revision, t.digest, t.label,
       t.summary, t.parent_thread_id, t.capture_status,
       COUNT(e.id)::bigint AS event_count
FROM canonical_threads t
LEFT JOIN canonical_events e
       ON e.session_id = t.session_id AND e.thread_id = t.id
WHERE t.session_id = $1
GROUP BY t.session_id, t.id
ORDER BY t.id
`

type ListSessionThreadsRow struct {
	SessionID      string
	ID             string
	SourceKey      string
	Revision       int64
	Digest         string
	Label          string
	Summary        string
	ParentThreadID *string
	CaptureStatus  string
	EventCount     int64
}

func (q *Queries) ListSessionThreads(ctx context.Context, sessionID string) ([]ListSessionThreadsRow, error) {
	rows, err := q.db.Query(ctx, listSessionThreads, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionThreadsRow{}
	for rows.Next() {
		var i ListSessionThreadsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.ID,
			&i.SourceKey,
			&i.Revision,
			&i.Digest,
			&i.Label,
			&i.Summary,
			&i.ParentThreadID,
			&i.CaptureStatus,
			&i.EventCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadEvents = `-- name: ListThreadEvents :many
SELECT id, session_id, thread_id, source_key, revision, projection_revision,
       digest, source_order, event_index, order_fidelity, fidelity, raw_ref,
       adapter_version, schema_version, observed_at, received_at, ingest_seq,
       kind, author, occurred_at, text, tool_label, child_thread_id
FROM canonical_events
WHERE session_id = $1 AND thread_id = $2
ORDER BY source_order, event_index, id
`

type ListThreadEventsParams struct {
	SessionID string
	ThreadID  string
}

func (q *Queries) ListThreadEvents(ctx context.Context, arg ListThreadEventsParams) ([]CanonicalEvent, error) {
	rows, err := q.db.Query(ctx, listThreadEvents, arg.SessionID, arg.ThreadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CanonicalEvent{}
	for rows.Next() {
		var i CanonicalEvent
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ThreadID,
			&i.SourceKey,
			&i.Revision,
			&i.ProjectionRevision,
			&i.Digest,
			&i.SourceOrder,
			&i.EventIndex,
			&i.OrderFidelity,
			&i.Fidelity,
			&i.RawRef,
			&i.AdapterVersion,
			&i.SchemaVersion,
			&i.ObservedAt,
			&i.ReceivedAt,
			&i.IngestSeq,
			&i.Kind,
			&i.Author,
			&i.OccurredAt,
			&i.Text,
			&i.ToolLabel,
			&i.ChildThreadID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextIngestMetadata = `-- name: NextIngestMetadata :one
SELECT nextval('canonical_ingest_seq')::bigint AS ingest_seq,
       clock_timestamp()::timestamptz AS received_at
`

type NextIngestMetadataRow struct {
	IngestSeq  int64
	ReceivedAt time.Time
}

func (q *Queries) NextIngestMetadata(ctx context.Context) (NextIngestMetadataRow, error) {
	row := q.db.QueryRow(ctx, nextIngestMetadata)
	var i NextIngestMetadataRow
	err := row.Scan(&i.IngestSeq, &i.ReceivedAt)
	return i, err
}

const registerTeam = `-- name: RegisterTeam :exec
INSERT INTO workspace_teams (id, name, name_reported)
VALUES ($1, $2, TRUE)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    name_reported = TRUE
WHERE workspace_teams.name_reported = FALSE
`

type RegisterTeamParams struct {
	ID   string
	Name string
}

func (q *Queries) RegisterTeam(ctx context.Context, arg RegisterTeamParams) error {
	_, err := q.db.Exec(ctx, registerTeam, arg.ID, arg.Name)
	return err
}

const updateEvent = `-- name: UpdateEvent :exec
UPDATE canonical_events
SET revision = $2,
    projection_revision = $3,
    digest = $4,
    source_order = $5,
    event_index = $6,
    order_fidelity = $7,
    fidelity = $8,
    raw_ref = $9,
    adapter_version = $10,
    schema_version = $11,
    observed_at = $12,
    received_at = $13,
    ingest_seq = $14,
    kind = $15,
    author = $16,
    occurred_at = $17,
    text = $18,
    tool_label = $19,
    child_thread_id = $20
WHERE id = $1
`

type UpdateEventParams struct {
	ID                 string
	Revision           int64
	ProjectionRevision int64
	Digest             string
	SourceOrder        int64
	EventIndex         int64
	OrderFidelity      string
	Fidelity           string
	RawRef             string
	AdapterVersion     string
	SchemaVersion      string
	ObservedAt         time.Time
	ReceivedAt         time.Time
	IngestSeq          int64
	Kind               string
	Author             string
	OccurredAt         time.Time
	Text               string
	ToolLabel          string
	ChildThreadID      *string
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) error {
	_, err := q.db.Exec(ctx, updateEvent,
		arg.ID,
		arg.Revision,
		arg.ProjectionRevision,
		arg.Digest,
		arg.SourceOrder,
		arg.EventIndex,
		arg.OrderFidelity,
		arg.Fidelity,
		arg.RawRef,
		arg.AdapterVersion,
		arg.SchemaVersion,
		arg.ObservedAt,
		arg.ReceivedAt,
		arg.IngestSeq,
		arg.Kind,
		arg.Author,
		arg.OccurredAt,
		arg.Text,
		arg.ToolLabel,
		arg.ChildThreadID,
	)
	return err
}

const updateSession = `-- name: UpdateSession :exec
UPDATE canonical_sessions
SET revision = $2,
    digest = $3,
    title = $4,
    summary = $5,
    insight = $6,
    actor_name = $7,
    actor_harness = $8,
    branch = $9,
    status = $10,
    capture_status = $11,
    updated_at = $12,
    reported_event_count = $13
WHERE id = $1 AND revision < $2
`

type UpdateSessionParams struct {
	ID                 string
	Revision           int64
	Digest             string
	Title              string
	Summary            string
	Insight            string
	ActorName          string
	ActorHarness       string
	Branch             string
	Status             string
	CaptureStatus      string
	UpdatedAt          time.Time
	ReportedEventCount int64
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.Exec(ctx, updateSession,
		arg.ID,
		arg.Revision,
		arg.Digest,
		arg.Title,
		arg.Summary,
		arg.Insight,
		arg.ActorName,
		arg.ActorHarness,
		arg.Branch,
		arg.Status,
		arg.CaptureStatus,
		arg.UpdatedAt,
		arg.ReportedEventCount,
	)
	return err
}

const updateThread = `-- name: UpdateThread :exec
UPDATE canonical_threads
SET revision = $3,
    digest = $4,
    label = $5,
    summary = $6,
    capture_status = $7
WHERE session_id = $1 AND id = $2 AND revision < $3
`

type UpdateThreadParams struct {
	SessionID     string
	ID            string
	Revision      int64
	Digest        string
	Label         string
	Summary       string
	CaptureStatus string
}

func (q *Queries) UpdateThread(ctx context.Context, arg UpdateThreadParams) error {
	_, err := q.db.Exec(ctx, updateThread,
		arg.SessionID,
		arg.ID,
		arg.Revision,
		arg.Digest,
		arg.Label,
		arg.Summary,
		arg.CaptureStatus,
	)
	return err
}
