// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCopyOverviewMessages implements pgx.CopyFromSource.
type iteratorForCopyOverviewMessages struct {
	rows                 []CopyOverviewMessagesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCopyOverviewMessages) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCopyOverviewMessages) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].AttemptID,
		r.rows[0].PartOrdinal,
		r.rows[0].EntryIndex,
		r.rows[0].EventID,
		r.rows[0].ThreadID,
		r.rows[0].OccurredAt,
		r.rows[0].Author,
		r.rows[0].Root,
		r.rows[0].SourceOrder,
		r.rows[0].EventIndex,
	}, nil
}

func (r iteratorForCopyOverviewMessages) Err() error {
	return nil
}

func (q *Queries) CopyOverviewMessages(ctx context.Context, arg []CopyOverviewMessagesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"overview_publication_messages"}, []string{"attempt_id", "part_ordinal", "entry_index", "event_id", "thread_id", "occurred_at", "author", "root", "source_order", "event_index"}, &iteratorForCopyOverviewMessages{rows: arg})
}

// iteratorForCopyOverviewUsage implements pgx.CopyFromSource.
type iteratorForCopyOverviewUsage struct {
	rows                 []CopyOverviewUsageParams
	skippedFirstNextCall bool
}

func (r *iteratorForCopyOverviewUsage) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCopyOverviewUsage) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].AttemptID,
		r.rows[0].PartOrdinal,
		r.rows[0].EntryIndex,
		r.rows[0].SourceKey,
		r.rows[0].ThreadID,
		r.rows[0].OccurredAt,
		r.rows[0].Model,
		r.rows[0].InputTokens,
		r.rows[0].OutputTokens,
		r.rows[0].CacheReadTokens,
		r.rows[0].CacheWriteTokens,
	}, nil
}

func (r iteratorForCopyOverviewUsage) Err() error {
	return nil
}

func (q *Queries) CopyOverviewUsage(ctx context.Context, arg []CopyOverviewUsageParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"overview_publication_usage"}, []string{"attempt_id", "part_ordinal", "entry_index", "source_key", "thread_id", "occurred_at", "model", "input_tokens", "output_tokens", "cache_read_tokens", "cache_write_tokens"}, &iteratorForCopyOverviewUsage{rows: arg})
}
