// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type CanonicalEvent struct {
	ID                 string
	SessionID          string
	ThreadID           string
	SourceKey          string
	Revision           int64
	ProjectionRevision int64
	Digest             string
	SourceOrder        int64
	EventIndex         int64
	OrderFidelity      string
	Fidelity           string
	RawRef             string
	AdapterVersion     string
	SchemaVersion      string
	ObservedAt         time.Time
	ReceivedAt         time.Time
	IngestSeq          int64
	Kind               string
	Author             string
	OccurredAt         time.Time
	Text               string
	ToolLabel          string
	ChildThreadID      *string
}

type CanonicalThread struct {
	SessionID      string
	ID             string
	SourceKey      string
	Revision       int64
	Digest         string
	Label          string
	Summary        string
	ParentThreadID *string
	CaptureStatus  string
}
