// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type CanonicalEvent struct {
	ID                 string
	SessionID          string
	ThreadID           string
	SourceKey          string
	Revision           int64
	ProjectionRevision int64
	Digest             string
	SourceOrder        int64
	EventIndex         int64
	OrderFidelity      string
	Fidelity           string
	RawRef             string
	AdapterVersion     string
	SchemaVersion      string
	ObservedAt         time.Time
	ReceivedAt         time.Time
	IngestSeq          int64
	Kind               string
	Author             string
	OccurredAt         time.Time
	Text               string
	ToolLabel          string
	ChildThreadID      *string
	ToolUpdateJson     string
}

type CanonicalPublicationAttempt struct {
	ID               pgtype.UUID
	SessionID        string
	CaptureID        string
	BaseHead         *string
	TransformVersion string
	Fence            int64
	LeaseUntil       time.Time
	State            string
	PartCount        int32
	RetainedBytes    int64
	SealJson         *string
}

type CanonicalPublicationReservation struct {
	ID        pgtype.UUID
	SessionID string
	ExpiresAt time.Time
}

type CanonicalPublicationSource struct {
	SessionID        string
	SourceKey        string
	ProjectID        string
	CapturedByUserID pgtype.UUID
	InstallationID   string
	AdapterID        string
	SourceSessionID  string
	OriginKey        string
	WriterFence      int64
	CurrentHead      *string
}

type CanonicalSession struct {
	ID                 string
	ProjectID          string
	SourceKey          string
	Revision           int64
	Digest             string
	Title              string
	Summary            string
	Insight            string
	ActorName          string
	ActorHarness       string
	Branch             string
	Status             string
	CaptureStatus      string
	UpdatedAt          time.Time
	ReportedEventCount int64
	CapturedByUserID   pgtype.UUID
	RecordState        string
	DeletedAt          pgtype.Timestamptz
	DeletedByUserID    pgtype.UUID
	CaptureLineage     string
}

type CanonicalThread struct {
	SessionID      string
	ID             string
	SourceKey      string
	Revision       int64
	Digest         string
	Label          string
	Summary        string
	ParentThreadID *string
	CaptureStatus  string
}

type CanonicalUsage struct {
	SourceKey        string
	SessionID        string
	ThreadID         string
	Revision         int64
	Digest           string
	OccurredAt       time.Time
	Model            string
	InputTokens      *int64
	OutputTokens     *int64
	CacheReadTokens  *int64
	CacheWriteTokens *int64
}
