// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: overview.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const overviewEvents = `-- name: OverviewEvents :many
SELECT e.session_id,e.thread_id,e.author,
CASE WHEN e.author=s.actor_name THEN left(e.text,1500) ELSE right(e.text,1500) END::text AS text,
e.occurred_at,e.source_order,e.event_index,(t.parent_thread_id IS NULL)::boolean AS root
FROM canonical_events e JOIN canonical_sessions s ON s.id=e.session_id
JOIN canonical_projects p ON p.id=s.project_id
JOIN canonical_threads t ON t.session_id=e.session_id AND t.id=e.thread_id
WHERE p.team_id=$1 AND p.state<>'deleted' AND s.record_state='active' AND e.kind='message'
AND e.occurred_at>=$2::timestamptz AND e.occurred_at<$3::timestamptz
ORDER BY e.session_id,e.source_order,e.event_index,e.id LIMIT 100001
`

type OverviewEventsParams struct {
	TeamID    string
	FromTime  time.Time
	UntilTime time.Time
}

type OverviewEventsRow struct {
	SessionID   string
	ThreadID    string
	Author      string
	Text        string
	OccurredAt  time.Time
	SourceOrder int64
	EventIndex  int64
	Root        bool
}

func (q *Queries) OverviewEvents(ctx context.Context, arg OverviewEventsParams) ([]OverviewEventsRow, error) {
	rows, err := q.db.Query(ctx, overviewEvents, arg.TeamID, arg.FromTime, arg.UntilTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OverviewEventsRow{}
	for rows.Next() {
		var i OverviewEventsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.ThreadID,
			&i.Author,
			&i.Text,
			&i.OccurredAt,
			&i.SourceOrder,
			&i.EventIndex,
			&i.Root,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const overviewMembers = `-- name: OverviewMembers :many
SELECT m.user_id::text AS id,u.display_name AS name,(m.status='active')::boolean AS current
FROM team_memberships m JOIN auth_users u ON u.id=m.user_id
WHERE m.team_id=$1 ORDER BY u.display_name,m.user_id LIMIT 100001
`

type OverviewMembersRow struct {
	ID      string
	Name    string
	Current bool
}

func (q *Queries) OverviewMembers(ctx context.Context, teamID string) ([]OverviewMembersRow, error) {
	rows, err := q.db.Query(ctx, overviewMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OverviewMembersRow{}
	for rows.Next() {
		var i OverviewMembersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Current); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const overviewProjects = `-- name: OverviewProjects :many
SELECT id,team_id,name,project_type,state FROM canonical_projects WHERE team_id=$1 AND state<>'deleted' ORDER BY name,id LIMIT 100001
`

type OverviewProjectsRow struct {
	ID          string
	TeamID      string
	Name        string
	ProjectType string
	State       string
}

func (q *Queries) OverviewProjects(ctx context.Context, teamID string) ([]OverviewProjectsRow, error) {
	rows, err := q.db.Query(ctx, overviewProjects, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OverviewProjectsRow{}
	for rows.Next() {
		var i OverviewProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.ProjectType,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const overviewSessions = `-- name: OverviewSessions :many
SELECT s.id, s.project_id, s.source_key, s.revision, s.digest, s.title, s.summary, s.insight, s.actor_name, s.actor_harness, s.branch, s.status, s.capture_status, s.updated_at, s.reported_event_count, s.captured_by_user_id, s.record_state, s.deleted_at, s.deleted_by_user_id, s.capture_lineage FROM canonical_sessions s JOIN canonical_projects p ON p.id=s.project_id
WHERE p.team_id=$1 AND p.state<>'deleted' AND s.record_state='active' ORDER BY s.id LIMIT 100001
`

func (q *Queries) OverviewSessions(ctx context.Context, teamID string) ([]CanonicalSession, error) {
	rows, err := q.db.Query(ctx, overviewSessions, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CanonicalSession{}
	for rows.Next() {
		var i CanonicalSession
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourceKey,
			&i.Revision,
			&i.Digest,
			&i.Title,
			&i.Summary,
			&i.Insight,
			&i.ActorName,
			&i.ActorHarness,
			&i.Branch,
			&i.Status,
			&i.CaptureStatus,
			&i.UpdatedAt,
			&i.ReportedEventCount,
			&i.CapturedByUserID,
			&i.RecordState,
			&i.DeletedAt,
			&i.DeletedByUserID,
			&i.CaptureLineage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const overviewTeam = `-- name: OverviewTeam :one
SELECT t.id,t.name,COALESCE(m.role,'')::text AS role,COALESCE(m.status,'')::text AS membership_status
FROM workspace_teams t LEFT JOIN team_memberships m ON m.team_id=t.id AND m.user_id=$1
WHERE t.id=$2
`

type OverviewTeamParams struct {
	UserID pgtype.UUID
	TeamID string
}

type OverviewTeamRow struct {
	ID               string
	Name             string
	Role             string
	MembershipStatus string
}

func (q *Queries) OverviewTeam(ctx context.Context, arg OverviewTeamParams) (OverviewTeamRow, error) {
	row := q.db.QueryRow(ctx, overviewTeam, arg.UserID, arg.TeamID)
	var i OverviewTeamRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.MembershipStatus,
	)
	return i, err
}

const overviewUnknownTimes = `-- name: OverviewUnknownTimes :one
SELECT count(DISTINCT e.session_id)::bigint FROM canonical_events e
JOIN canonical_sessions s ON s.id=e.session_id JOIN canonical_projects p ON p.id=s.project_id
WHERE p.team_id=$1 AND p.state<>'deleted' AND s.record_state='active' AND e.kind='message' AND e.occurred_at<'2000-01-01'::timestamptz
`

func (q *Queries) OverviewUnknownTimes(ctx context.Context, teamID string) (int64, error) {
	row := q.db.QueryRow(ctx, overviewUnknownTimes, teamID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const overviewUsage = `-- name: OverviewUsage :many
SELECT u.source_key, u.session_id, u.thread_id, u.revision, u.digest, u.occurred_at, u.model, u.input_tokens, u.output_tokens, u.cache_read_tokens, u.cache_write_tokens FROM canonical_usage u JOIN canonical_sessions s ON s.id=u.session_id
JOIN canonical_projects p ON p.id=s.project_id
WHERE p.team_id=$1 AND p.state<>'deleted' AND s.record_state='active'
AND u.occurred_at>=$2::timestamptz AND u.occurred_at<$3::timestamptz
ORDER BY u.session_id,u.occurred_at,u.source_key LIMIT 100001
`

type OverviewUsageParams struct {
	TeamID    string
	FromTime  time.Time
	UntilTime time.Time
}

func (q *Queries) OverviewUsage(ctx context.Context, arg OverviewUsageParams) ([]CanonicalUsage, error) {
	rows, err := q.db.Query(ctx, overviewUsage, arg.TeamID, arg.FromTime, arg.UntilTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CanonicalUsage{}
	for rows.Next() {
		var i CanonicalUsage
		if err := rows.Scan(
			&i.SourceKey,
			&i.SessionID,
			&i.ThreadID,
			&i.Revision,
			&i.Digest,
			&i.OccurredAt,
			&i.Model,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
