// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: overview_facts.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimOverviewBackfillPart = `-- name: ClaimOverviewBackfillPart :one
SELECT attempt_id,ordinal,stored_bytes FROM canonical_publication_parts
WHERE format_version=1 AND overview_version IS DISTINCT FROM 1
ORDER BY attempt_id,ordinal LIMIT 1 FOR UPDATE SKIP LOCKED
`

type ClaimOverviewBackfillPartRow struct {
	AttemptID   pgtype.UUID
	Ordinal     int32
	StoredBytes int64
}

// Lock only a part; never acquire an account, source or attempt lock afterward.
// This cannot invert validation/reclamation's existing lock order.
func (q *Queries) ClaimOverviewBackfillPart(ctx context.Context) (ClaimOverviewBackfillPartRow, error) {
	row := q.db.QueryRow(ctx, claimOverviewBackfillPart)
	var i ClaimOverviewBackfillPartRow
	err := row.Scan(&i.AttemptID, &i.Ordinal, &i.StoredBytes)
	return i, err
}

const completeOverviewPart = `-- name: CompleteOverviewPart :execrows
UPDATE canonical_publication_parts SET overview_version=1
WHERE attempt_id=$1 AND ordinal=$2 AND format_version=1 AND overview_version IS DISTINCT FROM 1
`

type CompleteOverviewPartParams struct {
	AttemptID pgtype.UUID
	Ordinal   int32
}

func (q *Queries) CompleteOverviewPart(ctx context.Context, arg CompleteOverviewPartParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeOverviewPart, arg.AttemptID, arg.Ordinal)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

type CopyOverviewMessagesParams struct {
	AttemptID   pgtype.UUID
	PartOrdinal int32
	EntryIndex  int32
	EventID     string
	ThreadID    string
	OccurredAt  time.Time
	Author      string
	Root        bool
	SourceOrder int64
	EventIndex  int64
}

type CopyOverviewUsageParams struct {
	AttemptID        pgtype.UUID
	PartOrdinal      int32
	EntryIndex       int32
	SourceKey        string
	ThreadID         string
	OccurredAt       time.Time
	Model            string
	InputTokens      *int64
	OutputTokens     *int64
	CacheReadTokens  *int64
	CacheWriteTokens *int64
}

const overviewFactCoverage = `-- name: OverviewFactCoverage :one
SELECT count(*)::bigint AS retained_parts,
 count(*) FILTER(WHERE p.overview_version IS DISTINCT FROM 1)::bigint AS missing_parts,
 count(*) FILTER(WHERE p.overview_version IS DISTINCT FROM 1 AND s.current_head=p.attempt_id::text)::bigint AS current_head_missing_parts
FROM canonical_publication_parts p
JOIN canonical_publication_attempts a ON a.id=p.attempt_id
JOIN canonical_publication_sources s ON s.session_id=a.session_id
WHERE p.format_version=1
`

type OverviewFactCoverageRow struct {
	RetainedParts           int64
	MissingParts            int64
	CurrentHeadMissingParts int64
}

func (q *Queries) OverviewFactCoverage(ctx context.Context) (OverviewFactCoverageRow, error) {
	row := q.db.QueryRow(ctx, overviewFactCoverage)
	var i OverviewFactCoverageRow
	err := row.Scan(&i.RetainedParts, &i.MissingParts, &i.CurrentHeadMissingParts)
	return i, err
}
