// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: publication.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPublicationBytes = `-- name: AddPublicationBytes :exec
UPDATE canonical_publication_attempts SET retained_bytes=retained_bytes+$2,part_count=part_count+1 WHERE id=$1
`

type AddPublicationBytesParams struct {
	ID            pgtype.UUID
	RetainedBytes int64
}

func (q *Queries) AddPublicationBytes(ctx context.Context, arg AddPublicationBytesParams) error {
	_, err := q.db.Exec(ctx, addPublicationBytes, arg.ID, arg.RetainedBytes)
	return err
}

const createPublicationAttempt = `-- name: CreatePublicationAttempt :one
INSERT INTO canonical_publication_attempts(id,session_id,capture_id,base_head,transform_version,fence,lease_until)
SELECT $1,$2,$3,$4,$5,$6,LEAST($7::timestamptz,clock_timestamp()+$8::bigint*interval '1 millisecond')
WHERE $7::timestamptz>clock_timestamp()
RETURNING id, session_id, capture_id, base_head, transform_version, fence, lease_until, state, part_count, retained_bytes, seal_json
`

type CreatePublicationAttemptParams struct {
	ID               pgtype.UUID
	SessionID        string
	CaptureID        string
	BaseHead         *string
	TransformVersion string
	Fence            int64
	ExpiresAt        time.Time
	LeaseMs          int64
}

func (q *Queries) CreatePublicationAttempt(ctx context.Context, arg CreatePublicationAttemptParams) (CanonicalPublicationAttempt, error) {
	row := q.db.QueryRow(ctx, createPublicationAttempt,
		arg.ID,
		arg.SessionID,
		arg.CaptureID,
		arg.BaseHead,
		arg.TransformVersion,
		arg.Fence,
		arg.ExpiresAt,
		arg.LeaseMs,
	)
	var i CanonicalPublicationAttempt
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CaptureID,
		&i.BaseHead,
		&i.TransformVersion,
		&i.Fence,
		&i.LeaseUntil,
		&i.State,
		&i.PartCount,
		&i.RetainedBytes,
		&i.SealJson,
	)
	return i, err
}

const createPublicationReservation = `-- name: CreatePublicationReservation :one
INSERT INTO canonical_publication_reservations(id,session_id,expires_at)
VALUES($1,$2,clock_timestamp()+$3::bigint*interval '1 millisecond')
RETURNING id, session_id, expires_at
`

type CreatePublicationReservationParams struct {
	ID         pgtype.UUID
	SessionID  string
	LifetimeMs int64
}

func (q *Queries) CreatePublicationReservation(ctx context.Context, arg CreatePublicationReservationParams) (CanonicalPublicationReservation, error) {
	row := q.db.QueryRow(ctx, createPublicationReservation, arg.ID, arg.SessionID, arg.LifetimeMs)
	var i CanonicalPublicationReservation
	err := row.Scan(&i.ID, &i.SessionID, &i.ExpiresAt)
	return i, err
}

const deleteExpiredPublicationReservations = `-- name: DeleteExpiredPublicationReservations :many
DELETE FROM canonical_publication_reservations WHERE id IN (
 SELECT r.id FROM canonical_publication_reservations r
 JOIN canonical_publication_sources s ON s.session_id=r.session_id
 LEFT JOIN canonical_publication_attempts a ON a.id=r.id
 WHERE s.captured_by_user_id=$1 AND r.expires_at<=clock_timestamp()
 AND (a.id IS NULL OR a.part_count=0)
 ORDER BY r.id LIMIT $2
) RETURNING id
`

type DeleteExpiredPublicationReservationsParams struct {
	CapturedByUserID pgtype.UUID
	PageLimit        int32
}

func (q *Queries) DeleteExpiredPublicationReservations(ctx context.Context, arg DeleteExpiredPublicationReservationsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, deleteExpiredPublicationReservations, arg.CapturedByUserID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePublicationPart = `-- name: DeletePublicationPart :exec
DELETE FROM canonical_publication_parts WHERE attempt_id=$1 AND ordinal=$2
`

type DeletePublicationPartParams struct {
	AttemptID pgtype.UUID
	Ordinal   int32
}

func (q *Queries) DeletePublicationPart(ctx context.Context, arg DeletePublicationPartParams) error {
	_, err := q.db.Exec(ctx, deletePublicationPart, arg.AttemptID, arg.Ordinal)
	return err
}

const getPublicationAttempt = `-- name: GetPublicationAttempt :one
SELECT a.id, a.session_id, a.capture_id, a.base_head, a.transform_version, a.fence, a.lease_until, a.state, a.part_count, a.retained_bytes, a.seal_json,r.expires_at,
 CASE WHEN a.state='rejected' THEN 'rejected'
 WHEN a.fence<>s.writer_fence OR a.base_head IS DISTINCT FROM s.current_head THEN 'superseded'
 WHEN a.lease_until<=clock_timestamp() OR r.expires_at<=clock_timestamp() THEN 'expired'
 ELSE a.state END::text AS effective_state
FROM canonical_publication_attempts a
JOIN canonical_publication_reservations r ON r.id=a.id
JOIN canonical_publication_sources s ON s.session_id=a.session_id
WHERE a.id=$1
`

type GetPublicationAttemptRow struct {
	ID               pgtype.UUID
	SessionID        string
	CaptureID        string
	BaseHead         *string
	TransformVersion string
	Fence            int64
	LeaseUntil       time.Time
	State            string
	PartCount        int32
	RetainedBytes    int64
	SealJson         *string
	ExpiresAt        time.Time
	EffectiveState   string
}

func (q *Queries) GetPublicationAttempt(ctx context.Context, id pgtype.UUID) (GetPublicationAttemptRow, error) {
	row := q.db.QueryRow(ctx, getPublicationAttempt, id)
	var i GetPublicationAttemptRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CaptureID,
		&i.BaseHead,
		&i.TransformVersion,
		&i.Fence,
		&i.LeaseUntil,
		&i.State,
		&i.PartCount,
		&i.RetainedBytes,
		&i.SealJson,
		&i.ExpiresAt,
		&i.EffectiveState,
	)
	return i, err
}

const getPublicationPart = `-- name: GetPublicationPart :one
SELECT ordinal,digest,byte_count FROM canonical_publication_parts WHERE attempt_id=$1 AND ordinal=$2
`

type GetPublicationPartParams struct {
	AttemptID pgtype.UUID
	Ordinal   int32
}

type GetPublicationPartRow struct {
	Ordinal   int32
	Digest    string
	ByteCount int64
}

func (q *Queries) GetPublicationPart(ctx context.Context, arg GetPublicationPartParams) (GetPublicationPartRow, error) {
	row := q.db.QueryRow(ctx, getPublicationPart, arg.AttemptID, arg.Ordinal)
	var i GetPublicationPartRow
	err := row.Scan(&i.Ordinal, &i.Digest, &i.ByteCount)
	return i, err
}

const getPublicationReservation = `-- name: GetPublicationReservation :one
SELECT r.id,r.session_id,r.expires_at,r.expires_at>clock_timestamp() AS valid
FROM canonical_publication_reservations r WHERE r.id=$1
`

type GetPublicationReservationRow struct {
	ID        pgtype.UUID
	SessionID string
	ExpiresAt time.Time
	Valid     bool
}

func (q *Queries) GetPublicationReservation(ctx context.Context, id pgtype.UUID) (GetPublicationReservationRow, error) {
	row := q.db.QueryRow(ctx, getPublicationReservation, id)
	var i GetPublicationReservationRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ExpiresAt,
		&i.Valid,
	)
	return i, err
}

const getPublicationSource = `-- name: GetPublicationSource :one
SELECT session_id, source_key, project_id, captured_by_user_id, installation_id, adapter_id, source_session_id, origin_key, writer_fence, current_head FROM canonical_publication_sources WHERE session_id=$1
`

func (q *Queries) GetPublicationSource(ctx context.Context, sessionID string) (CanonicalPublicationSource, error) {
	row := q.db.QueryRow(ctx, getPublicationSource, sessionID)
	var i CanonicalPublicationSource
	err := row.Scan(
		&i.SessionID,
		&i.SourceKey,
		&i.ProjectID,
		&i.CapturedByUserID,
		&i.InstallationID,
		&i.AdapterID,
		&i.SourceSessionID,
		&i.OriginKey,
		&i.WriterFence,
		&i.CurrentHead,
	)
	return i, err
}

const insertPublicationPart = `-- name: InsertPublicationPart :exec
INSERT INTO canonical_publication_parts(attempt_id,ordinal,digest,byte_count,body) VALUES($1,$2,$3,$4,$5)
`

type InsertPublicationPartParams struct {
	AttemptID pgtype.UUID
	Ordinal   int32
	Digest    string
	ByteCount int64
	Body      []byte
}

func (q *Queries) InsertPublicationPart(ctx context.Context, arg InsertPublicationPartParams) error {
	_, err := q.db.Exec(ctx, insertPublicationPart,
		arg.AttemptID,
		arg.Ordinal,
		arg.Digest,
		arg.ByteCount,
		arg.Body,
	)
	return err
}

const insertPublicationSource = `-- name: InsertPublicationSource :exec
INSERT INTO canonical_publication_sources(session_id,source_key,project_id,captured_by_user_id,installation_id,adapter_id,source_session_id,origin_key)
VALUES($1,$2,$3,$4,$5,$6,$7,$8)
`

type InsertPublicationSourceParams struct {
	SessionID        string
	SourceKey        string
	ProjectID        string
	CapturedByUserID pgtype.UUID
	InstallationID   string
	AdapterID        string
	SourceSessionID  string
	OriginKey        string
}

func (q *Queries) InsertPublicationSource(ctx context.Context, arg InsertPublicationSourceParams) error {
	_, err := q.db.Exec(ctx, insertPublicationSource,
		arg.SessionID,
		arg.SourceKey,
		arg.ProjectID,
		arg.CapturedByUserID,
		arg.InstallationID,
		arg.AdapterID,
		arg.SourceSessionID,
		arg.OriginKey,
	)
	return err
}

const listPublicationParts = `-- name: ListPublicationParts :many
SELECT ordinal,digest,byte_count FROM canonical_publication_parts
WHERE attempt_id=$1 AND ordinal>$2 ORDER BY ordinal LIMIT $3
`

type ListPublicationPartsParams struct {
	AttemptID    pgtype.UUID
	AfterOrdinal int32
	PageLimit    int32
}

type ListPublicationPartsRow struct {
	Ordinal   int32
	Digest    string
	ByteCount int64
}

func (q *Queries) ListPublicationParts(ctx context.Context, arg ListPublicationPartsParams) ([]ListPublicationPartsRow, error) {
	rows, err := q.db.Query(ctx, listPublicationParts, arg.AttemptID, arg.AfterOrdinal, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicationPartsRow{}
	for rows.Next() {
		var i ListPublicationPartsRow
		if err := rows.Scan(&i.Ordinal, &i.Digest, &i.ByteCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextPublicationFence = `-- name: NextPublicationFence :one
UPDATE canonical_publication_sources SET writer_fence=writer_fence+1
WHERE session_id=$1 RETURNING writer_fence
`

func (q *Queries) NextPublicationFence(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRow(ctx, nextPublicationFence, sessionID)
	var writer_fence int64
	err := row.Scan(&writer_fence)
	return writer_fence, err
}

const publicationReclaimParts = `-- name: PublicationReclaimParts :many
SELECT p.attempt_id,p.ordinal,p.byte_count FROM canonical_publication_parts p
JOIN canonical_publication_attempts a ON a.id=p.attempt_id
JOIN canonical_publication_reservations r ON r.id=a.id
JOIN canonical_publication_sources s ON s.session_id=a.session_id
WHERE s.captured_by_user_id=$1 AND (a.state='rejected' OR a.fence<>s.writer_fence
 OR a.base_head IS DISTINCT FROM s.current_head OR a.lease_until<=clock_timestamp() OR r.expires_at<=clock_timestamp())
ORDER BY p.attempt_id,p.ordinal LIMIT $2
`

type PublicationReclaimPartsParams struct {
	CapturedByUserID pgtype.UUID
	PageLimit        int32
}

type PublicationReclaimPartsRow struct {
	AttemptID pgtype.UUID
	Ordinal   int32
	ByteCount int64
}

func (q *Queries) PublicationReclaimParts(ctx context.Context, arg PublicationReclaimPartsParams) ([]PublicationReclaimPartsRow, error) {
	rows, err := q.db.Query(ctx, publicationReclaimParts, arg.CapturedByUserID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublicationReclaimPartsRow{}
	for rows.Next() {
		var i PublicationReclaimPartsRow
		if err := rows.Scan(&i.AttemptID, &i.Ordinal, &i.ByteCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publicationUsage = `-- name: PublicationUsage :one
SELECT (SELECT count(*) FROM canonical_publication_reservations r
 JOIN canonical_publication_sources s ON s.session_id=r.session_id
 WHERE s.captured_by_user_id=$1 AND r.expires_at>clock_timestamp())::bigint AS reservations,
 (SELECT coalesce(sum(a.retained_bytes),0)::bigint FROM canonical_publication_attempts a
 JOIN canonical_publication_sources s ON s.session_id=a.session_id
 WHERE s.captured_by_user_id=$1)::bigint AS retained_bytes
`

type PublicationUsageRow struct {
	Reservations  int64
	RetainedBytes int64
}

func (q *Queries) PublicationUsage(ctx context.Context, capturedByUserID pgtype.UUID) (PublicationUsageRow, error) {
	row := q.db.QueryRow(ctx, publicationUsage, capturedByUserID)
	var i PublicationUsageRow
	err := row.Scan(&i.Reservations, &i.RetainedBytes)
	return i, err
}

const rejectPublicationAttempt = `-- name: RejectPublicationAttempt :exec
UPDATE canonical_publication_attempts SET state='rejected' WHERE id=$1
`

func (q *Queries) RejectPublicationAttempt(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, rejectPublicationAttempt, id)
	return err
}

const renewPublicationAttempt = `-- name: RenewPublicationAttempt :one
UPDATE canonical_publication_attempts SET lease_until=GREATEST(lease_until,
 LEAST($2::timestamptz,clock_timestamp()+$3::bigint*interval '1 millisecond'))
WHERE id=$1 AND lease_until>clock_timestamp() AND $2::timestamptz>clock_timestamp()
RETURNING lease_until
`

type RenewPublicationAttemptParams struct {
	ID        pgtype.UUID
	ExpiresAt time.Time
	LeaseMs   int64
}

func (q *Queries) RenewPublicationAttempt(ctx context.Context, arg RenewPublicationAttemptParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, renewPublicationAttempt, arg.ID, arg.ExpiresAt, arg.LeaseMs)
	var lease_until time.Time
	err := row.Scan(&lease_until)
	return lease_until, err
}

const sealPublicationAttempt = `-- name: SealPublicationAttempt :exec
UPDATE canonical_publication_attempts SET state='sealed',seal_json=$2 WHERE id=$1
`

type SealPublicationAttemptParams struct {
	ID       pgtype.UUID
	SealJson *string
}

func (q *Queries) SealPublicationAttempt(ctx context.Context, arg SealPublicationAttemptParams) error {
	_, err := q.db.Exec(ctx, sealPublicationAttempt, arg.ID, arg.SealJson)
	return err
}

const subtractPublicationBytes = `-- name: SubtractPublicationBytes :exec
UPDATE canonical_publication_attempts SET retained_bytes=retained_bytes-$2,part_count=part_count-1 WHERE id=$1
`

type SubtractPublicationBytesParams struct {
	ID            pgtype.UUID
	RetainedBytes int64
}

func (q *Queries) SubtractPublicationBytes(ctx context.Context, arg SubtractPublicationBytesParams) error {
	_, err := q.db.Exec(ctx, subtractPublicationBytes, arg.ID, arg.RetainedBytes)
	return err
}
