// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: publication.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const ackPublicationProjectionChanges = `-- name: AckPublicationProjectionChanges :exec
UPDATE canonical_publication_projection_changes SET processed_at=clock_timestamp(),lease_owner=NULL,lease_until=NULL
WHERE id=ANY($1::bigint[]) AND lease_owner=$2
`

type AckPublicationProjectionChangesParams struct {
	ChangeIds  []int64
	LeaseOwner *string
}

func (q *Queries) AckPublicationProjectionChanges(ctx context.Context, arg AckPublicationProjectionChangesParams) error {
	_, err := q.db.Exec(ctx, ackPublicationProjectionChanges, arg.ChangeIds, arg.LeaseOwner)
	return err
}

const activatePublicationSource = `-- name: ActivatePublicationSource :execrows
UPDATE canonical_publication_sources s SET current_head=$1
FROM canonical_publication_attempts a JOIN canonical_publication_reservations r ON r.id=a.id
WHERE a.id=$2 AND s.session_id=a.session_id AND a.state='activated'
 AND a.validated_parts=a.part_count AND a.fence=s.writer_fence
 AND a.base_head IS NOT DISTINCT FROM s.current_head
 AND a.lease_until>clock_timestamp() AND r.expires_at>clock_timestamp()
`

type ActivatePublicationSourceParams struct {
	Head      *string
	AttemptID pgtype.UUID
}

func (q *Queries) ActivatePublicationSource(ctx context.Context, arg ActivatePublicationSourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, activatePublicationSource, arg.Head, arg.AttemptID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const addPublicationBytes = `-- name: AddPublicationBytes :exec
UPDATE canonical_publication_attempts SET retained_bytes=retained_bytes+$2,part_count=part_count+1 WHERE id=$1
`

type AddPublicationBytesParams struct {
	ID            pgtype.UUID
	RetainedBytes int64
}

func (q *Queries) AddPublicationBytes(ctx context.Context, arg AddPublicationBytesParams) error {
	_, err := q.db.Exec(ctx, addPublicationBytes, arg.ID, arg.RetainedBytes)
	return err
}

const advancePublicationValidation = `-- name: AdvancePublicationValidation :exec
UPDATE canonical_publication_attempts SET validated_parts=validated_parts+1,
 candidate_events=candidate_events+$1,candidate_usage=candidate_usage+$2,
 retained_bytes=retained_bytes+$3,header_digest=$4,target_json=$5,state=$6
WHERE id=$7
`

type AdvancePublicationValidationParams struct {
	Events       int32
	Usage        int32
	ByteDelta    int64
	HeaderDigest *string
	TargetJson   *string
	State        string
	ID           pgtype.UUID
}

func (q *Queries) AdvancePublicationValidation(ctx context.Context, arg AdvancePublicationValidationParams) error {
	_, err := q.db.Exec(ctx, advancePublicationValidation,
		arg.Events,
		arg.Usage,
		arg.ByteDelta,
		arg.HeaderDigest,
		arg.TargetJson,
		arg.State,
		arg.ID,
	)
	return err
}

const claimPublicationProjectionChanges = `-- name: ClaimPublicationProjectionChanges :many
WITH candidates AS (
 SELECT c.id FROM canonical_publication_projection_changes c
 JOIN canonical_publication_attempts a ON a.id=c.attempt_id AND a.state='activated'
 JOIN canonical_publication_sources s ON s.session_id=a.session_id AND s.current_head::uuid=c.attempt_id
 JOIN canonical_sessions cs ON cs.id=s.session_id AND cs.record_state='active'
 WHERE c.processed_at IS NULL AND (c.lease_until IS NULL OR c.lease_until<=clock_timestamp())
 ORDER BY c.id LIMIT $1 FOR UPDATE OF c SKIP LOCKED
), claimed AS (
 UPDATE canonical_publication_projection_changes c SET lease_owner=$2,lease_until=$3
 FROM candidates WHERE c.id=candidates.id RETURNING c.id, c.attempt_id, c.event_id, c.kind, c.lease_owner, c.lease_until, c.processed_at
)
SELECT c.id,c.attempt_id,c.event_id,m.part_ordinal,m.entry_index,m.search_descriptor
FROM claimed c JOIN canonical_publication_members m ON m.attempt_id=c.attempt_id AND m.kind='event' AND m.record_id=c.event_id
ORDER BY c.id
`

type ClaimPublicationProjectionChangesParams struct {
	BatchLimit int32
	LeaseOwner *string
	LeaseUntil pgtype.Timestamptz
}

type ClaimPublicationProjectionChangesRow struct {
	ID               int64
	AttemptID        pgtype.UUID
	EventID          string
	PartOrdinal      int32
	EntryIndex       int32
	SearchDescriptor string
}

func (q *Queries) ClaimPublicationProjectionChanges(ctx context.Context, arg ClaimPublicationProjectionChangesParams) ([]ClaimPublicationProjectionChangesRow, error) {
	rows, err := q.db.Query(ctx, claimPublicationProjectionChanges, arg.BatchLimit, arg.LeaseOwner, arg.LeaseUntil)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimPublicationProjectionChangesRow{}
	for rows.Next() {
		var i ClaimPublicationProjectionChangesRow
		if err := rows.Scan(
			&i.ID,
			&i.AttemptID,
			&i.EventID,
			&i.PartOrdinal,
			&i.EntryIndex,
			&i.SearchDescriptor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const confirmPublicationActivationAuthority = `-- name: ConfirmPublicationActivationAuthority :one
SELECT a.lease_until>clock_timestamp() AND r.expires_at>clock_timestamp()
 AND a.fence=s.writer_fence AND s.current_head=a.id::text AS valid
FROM canonical_publication_attempts a JOIN canonical_publication_reservations r ON r.id=a.id
JOIN canonical_publication_sources s ON s.session_id=a.session_id WHERE a.id=$1
`

func (q *Queries) ConfirmPublicationActivationAuthority(ctx context.Context, id pgtype.UUID) (*bool, error) {
	row := q.db.QueryRow(ctx, confirmPublicationActivationAuthority, id)
	var valid *bool
	err := row.Scan(&valid)
	return valid, err
}

const createPublicationAttempt = `-- name: CreatePublicationAttempt :one
INSERT INTO canonical_publication_attempts(id,session_id,capture_id,base_head,transform_version,fence,lease_until)
SELECT $1,$2,$3,$4,$5,$6,LEAST($7::timestamptz,clock_timestamp()+$8::bigint*interval '1 millisecond')
WHERE $7::timestamptz>clock_timestamp()
RETURNING id, session_id, capture_id, base_head, transform_version, fence, lease_until, state, part_count, retained_bytes, seal_json, validated_parts, candidate_events, candidate_usage, header_digest, target_json, activation_json, published_observed_at
`

type CreatePublicationAttemptParams struct {
	ID               pgtype.UUID
	SessionID        string
	CaptureID        string
	BaseHead         *string
	TransformVersion string
	Fence            int64
	ExpiresAt        time.Time
	LeaseMs          int64
}

func (q *Queries) CreatePublicationAttempt(ctx context.Context, arg CreatePublicationAttemptParams) (CanonicalPublicationAttempt, error) {
	row := q.db.QueryRow(ctx, createPublicationAttempt,
		arg.ID,
		arg.SessionID,
		arg.CaptureID,
		arg.BaseHead,
		arg.TransformVersion,
		arg.Fence,
		arg.ExpiresAt,
		arg.LeaseMs,
	)
	var i CanonicalPublicationAttempt
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CaptureID,
		&i.BaseHead,
		&i.TransformVersion,
		&i.Fence,
		&i.LeaseUntil,
		&i.State,
		&i.PartCount,
		&i.RetainedBytes,
		&i.SealJson,
		&i.ValidatedParts,
		&i.CandidateEvents,
		&i.CandidateUsage,
		&i.HeaderDigest,
		&i.TargetJson,
		&i.ActivationJson,
		&i.PublishedObservedAt,
	)
	return i, err
}

const createPublicationReservation = `-- name: CreatePublicationReservation :one
INSERT INTO canonical_publication_reservations(id,session_id,expires_at)
VALUES($1,$2,clock_timestamp()+$3::bigint*interval '1 millisecond')
RETURNING id, session_id, expires_at
`

type CreatePublicationReservationParams struct {
	ID         pgtype.UUID
	SessionID  string
	LifetimeMs int64
}

func (q *Queries) CreatePublicationReservation(ctx context.Context, arg CreatePublicationReservationParams) (CanonicalPublicationReservation, error) {
	row := q.db.QueryRow(ctx, createPublicationReservation, arg.ID, arg.SessionID, arg.LifetimeMs)
	var i CanonicalPublicationReservation
	err := row.Scan(&i.ID, &i.SessionID, &i.ExpiresAt)
	return i, err
}

const deleteExpiredPublicationReservations = `-- name: DeleteExpiredPublicationReservations :many
DELETE FROM canonical_publication_reservations WHERE id IN (
 SELECT r.id FROM canonical_publication_reservations r
 JOIN canonical_publication_sources s ON s.session_id=r.session_id
 LEFT JOIN canonical_publication_attempts a ON a.id=r.id
 WHERE s.captured_by_user_id=$1 AND r.expires_at<=clock_timestamp()
 AND (a.id IS NULL OR (a.part_count=0 AND a.state<>'activated'))
 ORDER BY r.id LIMIT $2
) RETURNING id
`

type DeleteExpiredPublicationReservationsParams struct {
	CapturedByUserID pgtype.UUID
	PageLimit        int32
}

func (q *Queries) DeleteExpiredPublicationReservations(ctx context.Context, arg DeleteExpiredPublicationReservationsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, deleteExpiredPublicationReservations, arg.CapturedByUserID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePublicationPart = `-- name: DeletePublicationPart :exec
DELETE FROM canonical_publication_parts WHERE attempt_id=$1 AND ordinal=$2
`

type DeletePublicationPartParams struct {
	AttemptID pgtype.UUID
	Ordinal   int32
}

func (q *Queries) DeletePublicationPart(ctx context.Context, arg DeletePublicationPartParams) error {
	_, err := q.db.Exec(ctx, deletePublicationPart, arg.AttemptID, arg.Ordinal)
	return err
}

const getPublicationAttempt = `-- name: GetPublicationAttempt :one
SELECT a.id, a.session_id, a.capture_id, a.base_head, a.transform_version, a.fence, a.lease_until, a.state, a.part_count, a.retained_bytes, a.seal_json, a.validated_parts, a.candidate_events, a.candidate_usage, a.header_digest, a.target_json, a.activation_json, a.published_observed_at,r.expires_at,
 CASE WHEN a.state='activated' THEN 'activated'
 WHEN a.state='rejected' THEN 'rejected'
 WHEN a.fence<>s.writer_fence OR a.base_head IS DISTINCT FROM s.current_head THEN 'superseded'
 WHEN a.lease_until<=clock_timestamp() OR r.expires_at<=clock_timestamp() THEN 'expired'
 ELSE a.state END::text AS effective_state
FROM canonical_publication_attempts a
JOIN canonical_publication_reservations r ON r.id=a.id
JOIN canonical_publication_sources s ON s.session_id=a.session_id
WHERE a.id=$1
`

type GetPublicationAttemptRow struct {
	ID                  pgtype.UUID
	SessionID           string
	CaptureID           string
	BaseHead            *string
	TransformVersion    string
	Fence               int64
	LeaseUntil          time.Time
	State               string
	PartCount           int32
	RetainedBytes       int64
	SealJson            *string
	ValidatedParts      int32
	CandidateEvents     int32
	CandidateUsage      int32
	HeaderDigest        *string
	TargetJson          *string
	ActivationJson      *string
	PublishedObservedAt pgtype.Timestamptz
	ExpiresAt           time.Time
	EffectiveState      string
}

func (q *Queries) GetPublicationAttempt(ctx context.Context, id pgtype.UUID) (GetPublicationAttemptRow, error) {
	row := q.db.QueryRow(ctx, getPublicationAttempt, id)
	var i GetPublicationAttemptRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CaptureID,
		&i.BaseHead,
		&i.TransformVersion,
		&i.Fence,
		&i.LeaseUntil,
		&i.State,
		&i.PartCount,
		&i.RetainedBytes,
		&i.SealJson,
		&i.ValidatedParts,
		&i.CandidateEvents,
		&i.CandidateUsage,
		&i.HeaderDigest,
		&i.TargetJson,
		&i.ActivationJson,
		&i.PublishedObservedAt,
		&i.ExpiresAt,
		&i.EffectiveState,
	)
	return i, err
}

const getPublicationEventPosition = `-- name: GetPublicationEventPosition :one
SELECT source_order,event_index,record_id FROM canonical_publication_members
WHERE attempt_id=$1 AND kind='event' AND thread_id=$2 AND record_id=$3
`

type GetPublicationEventPositionParams struct {
	AttemptID pgtype.UUID
	ThreadID  string
	RecordID  string
}

type GetPublicationEventPositionRow struct {
	SourceOrder int64
	EventIndex  int64
	RecordID    string
}

func (q *Queries) GetPublicationEventPosition(ctx context.Context, arg GetPublicationEventPositionParams) (GetPublicationEventPositionRow, error) {
	row := q.db.QueryRow(ctx, getPublicationEventPosition, arg.AttemptID, arg.ThreadID, arg.RecordID)
	var i GetPublicationEventPositionRow
	err := row.Scan(&i.SourceOrder, &i.EventIndex, &i.RecordID)
	return i, err
}

const getPublicationMember = `-- name: GetPublicationMember :one
SELECT source_key FROM canonical_publication_members WHERE attempt_id=$1 AND kind=$2 AND record_id=$3
`

type GetPublicationMemberParams struct {
	AttemptID pgtype.UUID
	Kind      string
	RecordID  string
}

func (q *Queries) GetPublicationMember(ctx context.Context, arg GetPublicationMemberParams) (string, error) {
	row := q.db.QueryRow(ctx, getPublicationMember, arg.AttemptID, arg.Kind, arg.RecordID)
	var source_key string
	err := row.Scan(&source_key)
	return source_key, err
}

const getPublicationPart = `-- name: GetPublicationPart :one
SELECT ordinal,digest,byte_count FROM canonical_publication_parts WHERE attempt_id=$1 AND ordinal=$2
`

type GetPublicationPartParams struct {
	AttemptID pgtype.UUID
	Ordinal   int32
}

type GetPublicationPartRow struct {
	Ordinal   int32
	Digest    string
	ByteCount int64
}

func (q *Queries) GetPublicationPart(ctx context.Context, arg GetPublicationPartParams) (GetPublicationPartRow, error) {
	row := q.db.QueryRow(ctx, getPublicationPart, arg.AttemptID, arg.Ordinal)
	var i GetPublicationPartRow
	err := row.Scan(&i.Ordinal, &i.Digest, &i.ByteCount)
	return i, err
}

const getPublicationPartBody = `-- name: GetPublicationPartBody :one
SELECT body,validated_body,format_version,stored_bytes FROM canonical_publication_parts WHERE attempt_id=$1 AND ordinal=$2
`

type GetPublicationPartBodyParams struct {
	AttemptID pgtype.UUID
	Ordinal   int32
}

type GetPublicationPartBodyRow struct {
	Body          []byte
	ValidatedBody []byte
	FormatVersion *int32
	StoredBytes   int64
}

func (q *Queries) GetPublicationPartBody(ctx context.Context, arg GetPublicationPartBodyParams) (GetPublicationPartBodyRow, error) {
	row := q.db.QueryRow(ctx, getPublicationPartBody, arg.AttemptID, arg.Ordinal)
	var i GetPublicationPartBodyRow
	err := row.Scan(
		&i.Body,
		&i.ValidatedBody,
		&i.FormatVersion,
		&i.StoredBytes,
	)
	return i, err
}

const getPublicationPartStorage = `-- name: GetPublicationPartStorage :one
SELECT stored_bytes,format_version FROM canonical_publication_parts WHERE attempt_id=$1 AND ordinal=$2
`

type GetPublicationPartStorageParams struct {
	AttemptID pgtype.UUID
	Ordinal   int32
}

type GetPublicationPartStorageRow struct {
	StoredBytes   int64
	FormatVersion *int32
}

func (q *Queries) GetPublicationPartStorage(ctx context.Context, arg GetPublicationPartStorageParams) (GetPublicationPartStorageRow, error) {
	row := q.db.QueryRow(ctx, getPublicationPartStorage, arg.AttemptID, arg.Ordinal)
	var i GetPublicationPartStorageRow
	err := row.Scan(&i.StoredBytes, &i.FormatVersion)
	return i, err
}

const getPublicationRecordIdentity = `-- name: GetPublicationRecordIdentity :one
SELECT source_key,thread_id FROM canonical_publication_record_versions WHERE session_id=$1 AND kind=$2 AND record_id=$3 LIMIT 1
`

type GetPublicationRecordIdentityParams struct {
	SessionID string
	Kind      string
	RecordID  string
}

type GetPublicationRecordIdentityRow struct {
	SourceKey string
	ThreadID  string
}

func (q *Queries) GetPublicationRecordIdentity(ctx context.Context, arg GetPublicationRecordIdentityParams) (GetPublicationRecordIdentityRow, error) {
	row := q.db.QueryRow(ctx, getPublicationRecordIdentity, arg.SessionID, arg.Kind, arg.RecordID)
	var i GetPublicationRecordIdentityRow
	err := row.Scan(&i.SourceKey, &i.ThreadID)
	return i, err
}

const getPublicationRecordVersion = `-- name: GetPublicationRecordVersion :one
SELECT fingerprint FROM canonical_publication_record_versions WHERE kind=$1 AND source_key=$2 AND projection_revision=$3 AND revision=$4
`

type GetPublicationRecordVersionParams struct {
	Kind               string
	SourceKey          string
	ProjectionRevision int64
	Revision           int64
}

func (q *Queries) GetPublicationRecordVersion(ctx context.Context, arg GetPublicationRecordVersionParams) (string, error) {
	row := q.db.QueryRow(ctx, getPublicationRecordVersion,
		arg.Kind,
		arg.SourceKey,
		arg.ProjectionRevision,
		arg.Revision,
	)
	var fingerprint string
	err := row.Scan(&fingerprint)
	return fingerprint, err
}

const getPublicationReservation = `-- name: GetPublicationReservation :one
SELECT r.id,r.session_id,r.expires_at,r.expires_at>clock_timestamp() AS valid
FROM canonical_publication_reservations r WHERE r.id=$1
`

type GetPublicationReservationRow struct {
	ID        pgtype.UUID
	SessionID string
	ExpiresAt time.Time
	Valid     bool
}

func (q *Queries) GetPublicationReservation(ctx context.Context, id pgtype.UUID) (GetPublicationReservationRow, error) {
	row := q.db.QueryRow(ctx, getPublicationReservation, id)
	var i GetPublicationReservationRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ExpiresAt,
		&i.Valid,
	)
	return i, err
}

const getPublicationSource = `-- name: GetPublicationSource :one
SELECT session_id, source_key, project_id, captured_by_user_id, installation_id, adapter_id, source_session_id, origin_key, writer_fence, current_head FROM canonical_publication_sources WHERE session_id=$1
`

func (q *Queries) GetPublicationSource(ctx context.Context, sessionID string) (CanonicalPublicationSource, error) {
	row := q.db.QueryRow(ctx, getPublicationSource, sessionID)
	var i CanonicalPublicationSource
	err := row.Scan(
		&i.SessionID,
		&i.SourceKey,
		&i.ProjectID,
		&i.CapturedByUserID,
		&i.InstallationID,
		&i.AdapterID,
		&i.SourceSessionID,
		&i.OriginKey,
		&i.WriterFence,
		&i.CurrentHead,
	)
	return i, err
}

const insertPublicationMember = `-- name: InsertPublicationMember :exec
INSERT INTO canonical_publication_members(attempt_id,kind,record_id,source_key,part_ordinal,entry_index,thread_id,source_order,event_index,search_descriptor)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
`

type InsertPublicationMemberParams struct {
	AttemptID        pgtype.UUID
	Kind             string
	RecordID         string
	SourceKey        string
	PartOrdinal      int32
	EntryIndex       int32
	ThreadID         string
	SourceOrder      int64
	EventIndex       int64
	SearchDescriptor string
}

func (q *Queries) InsertPublicationMember(ctx context.Context, arg InsertPublicationMemberParams) error {
	_, err := q.db.Exec(ctx, insertPublicationMember,
		arg.AttemptID,
		arg.Kind,
		arg.RecordID,
		arg.SourceKey,
		arg.PartOrdinal,
		arg.EntryIndex,
		arg.ThreadID,
		arg.SourceOrder,
		arg.EventIndex,
		arg.SearchDescriptor,
	)
	return err
}

const insertPublicationPart = `-- name: InsertPublicationPart :exec
INSERT INTO canonical_publication_parts(attempt_id,ordinal,digest,byte_count,body) VALUES($1,$2,$3,$4,$5)
`

type InsertPublicationPartParams struct {
	AttemptID pgtype.UUID
	Ordinal   int32
	Digest    string
	ByteCount int64
	Body      []byte
}

func (q *Queries) InsertPublicationPart(ctx context.Context, arg InsertPublicationPartParams) error {
	_, err := q.db.Exec(ctx, insertPublicationPart,
		arg.AttemptID,
		arg.Ordinal,
		arg.Digest,
		arg.ByteCount,
		arg.Body,
	)
	return err
}

const insertPublicationProjectionChange = `-- name: InsertPublicationProjectionChange :exec
INSERT INTO canonical_publication_projection_changes(attempt_id,event_id) VALUES($1,$2)
`

type InsertPublicationProjectionChangeParams struct {
	AttemptID pgtype.UUID
	EventID   string
}

func (q *Queries) InsertPublicationProjectionChange(ctx context.Context, arg InsertPublicationProjectionChangeParams) error {
	_, err := q.db.Exec(ctx, insertPublicationProjectionChange, arg.AttemptID, arg.EventID)
	return err
}

const insertPublicationRecordVersion = `-- name: InsertPublicationRecordVersion :exec
INSERT INTO canonical_publication_record_versions(session_id,kind,source_key,record_id,thread_id,projection_revision,revision,fingerprint)
VALUES($1,$2,$3,$4,$5,$6,$7,$8)
`

type InsertPublicationRecordVersionParams struct {
	SessionID          string
	Kind               string
	SourceKey          string
	RecordID           string
	ThreadID           string
	ProjectionRevision int64
	Revision           int64
	Fingerprint        string
}

func (q *Queries) InsertPublicationRecordVersion(ctx context.Context, arg InsertPublicationRecordVersionParams) error {
	_, err := q.db.Exec(ctx, insertPublicationRecordVersion,
		arg.SessionID,
		arg.Kind,
		arg.SourceKey,
		arg.RecordID,
		arg.ThreadID,
		arg.ProjectionRevision,
		arg.Revision,
		arg.Fingerprint,
	)
	return err
}

const insertPublicationSource = `-- name: InsertPublicationSource :exec
INSERT INTO canonical_publication_sources(session_id,source_key,project_id,captured_by_user_id,installation_id,adapter_id,source_session_id,origin_key)
VALUES($1,$2,$3,$4,$5,$6,$7,$8)
`

type InsertPublicationSourceParams struct {
	SessionID        string
	SourceKey        string
	ProjectID        string
	CapturedByUserID pgtype.UUID
	InstallationID   string
	AdapterID        string
	SourceSessionID  string
	OriginKey        string
}

func (q *Queries) InsertPublicationSource(ctx context.Context, arg InsertPublicationSourceParams) error {
	_, err := q.db.Exec(ctx, insertPublicationSource,
		arg.SessionID,
		arg.SourceKey,
		arg.ProjectID,
		arg.CapturedByUserID,
		arg.InstallationID,
		arg.AdapterID,
		arg.SourceSessionID,
		arg.OriginKey,
	)
	return err
}

const listPublicationParts = `-- name: ListPublicationParts :many
SELECT ordinal,digest,byte_count FROM canonical_publication_parts
WHERE attempt_id=$1 AND ordinal>$2 ORDER BY ordinal LIMIT $3
`

type ListPublicationPartsParams struct {
	AttemptID    pgtype.UUID
	AfterOrdinal int32
	PageLimit    int32
}

type ListPublicationPartsRow struct {
	Ordinal   int32
	Digest    string
	ByteCount int64
}

func (q *Queries) ListPublicationParts(ctx context.Context, arg ListPublicationPartsParams) ([]ListPublicationPartsRow, error) {
	rows, err := q.db.Query(ctx, listPublicationParts, arg.AttemptID, arg.AfterOrdinal, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicationPartsRow{}
	for rows.Next() {
		var i ListPublicationPartsRow
		if err := rows.Scan(&i.Ordinal, &i.Digest, &i.ByteCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicationThreadMembers = `-- name: ListPublicationThreadMembers :many
SELECT record_id,part_ordinal,entry_index FROM canonical_publication_members
WHERE attempt_id=$1 AND kind='event' AND thread_id=$2
 AND (NOT $3::boolean OR (source_order,event_index,record_id)>($4::bigint,$5::bigint,$6::text))
ORDER BY source_order,event_index,record_id LIMIT $7
`

type ListPublicationThreadMembersParams struct {
	AttemptID  pgtype.UUID
	ThreadID   string
	HasAfter   bool
	AfterOrder int64
	AfterIndex int64
	AfterID    string
	PageLimit  int32
}

type ListPublicationThreadMembersRow struct {
	RecordID    string
	PartOrdinal int32
	EntryIndex  int32
}

func (q *Queries) ListPublicationThreadMembers(ctx context.Context, arg ListPublicationThreadMembersParams) ([]ListPublicationThreadMembersRow, error) {
	rows, err := q.db.Query(ctx, listPublicationThreadMembers,
		arg.AttemptID,
		arg.ThreadID,
		arg.HasAfter,
		arg.AfterOrder,
		arg.AfterIndex,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicationThreadMembersRow{}
	for rows.Next() {
		var i ListPublicationThreadMembersRow
		if err := rows.Scan(&i.RecordID, &i.PartOrdinal, &i.EntryIndex); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextPublicationFence = `-- name: NextPublicationFence :one
UPDATE canonical_publication_sources SET writer_fence=writer_fence+1
WHERE session_id=$1 RETURNING writer_fence
`

func (q *Queries) NextPublicationFence(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRow(ctx, nextPublicationFence, sessionID)
	var writer_fence int64
	err := row.Scan(&writer_fence)
	return writer_fence, err
}

const publicationReclaimParts = `-- name: PublicationReclaimParts :many
SELECT p.attempt_id,p.ordinal,p.stored_bytes AS byte_count FROM canonical_publication_parts p
JOIN canonical_publication_attempts a ON a.id=p.attempt_id
JOIN canonical_publication_reservations r ON r.id=a.id
JOIN canonical_publication_sources s ON s.session_id=a.session_id
WHERE s.captured_by_user_id=$1 AND (
 (a.state='activated' AND s.current_head IS DISTINCT FROM a.id::text)
 OR (a.state<>'activated' AND (a.state='rejected' OR a.fence<>s.writer_fence
 OR a.base_head IS DISTINCT FROM s.current_head OR a.lease_until<=clock_timestamp() OR r.expires_at<=clock_timestamp())))
ORDER BY p.attempt_id,p.ordinal LIMIT $2
`

type PublicationReclaimPartsParams struct {
	CapturedByUserID pgtype.UUID
	PageLimit        int32
}

type PublicationReclaimPartsRow struct {
	AttemptID pgtype.UUID
	Ordinal   int32
	ByteCount int64
}

func (q *Queries) PublicationReclaimParts(ctx context.Context, arg PublicationReclaimPartsParams) ([]PublicationReclaimPartsRow, error) {
	rows, err := q.db.Query(ctx, publicationReclaimParts, arg.CapturedByUserID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublicationReclaimPartsRow{}
	for rows.Next() {
		var i PublicationReclaimPartsRow
		if err := rows.Scan(&i.AttemptID, &i.Ordinal, &i.ByteCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publicationUsage = `-- name: PublicationUsage :one
SELECT (SELECT count(*) FROM canonical_publication_reservations r
 JOIN canonical_publication_sources s ON s.session_id=r.session_id
 WHERE s.captured_by_user_id=$1 AND r.expires_at>clock_timestamp())::bigint AS reservations,
 (SELECT coalesce(sum(a.retained_bytes),0)::bigint FROM canonical_publication_attempts a
 JOIN canonical_publication_sources s ON s.session_id=a.session_id
 WHERE s.captured_by_user_id=$1 AND a.state<>'activated')::bigint AS retained_bytes
`

type PublicationUsageRow struct {
	Reservations  int64
	RetainedBytes int64
}

func (q *Queries) PublicationUsage(ctx context.Context, capturedByUserID pgtype.UUID) (PublicationUsageRow, error) {
	row := q.db.QueryRow(ctx, publicationUsage, capturedByUserID)
	var i PublicationUsageRow
	err := row.Scan(&i.Reservations, &i.RetainedBytes)
	return i, err
}

const recordPublicationActivation = `-- name: RecordPublicationActivation :exec
UPDATE canonical_publication_attempts SET state='activated',activation_json=$2,published_observed_at=$3 WHERE id=$1
`

type RecordPublicationActivationParams struct {
	ID                  pgtype.UUID
	ActivationJson      *string
	PublishedObservedAt pgtype.Timestamptz
}

func (q *Queries) RecordPublicationActivation(ctx context.Context, arg RecordPublicationActivationParams) error {
	_, err := q.db.Exec(ctx, recordPublicationActivation, arg.ID, arg.ActivationJson, arg.PublishedObservedAt)
	return err
}

const rejectPublicationAttempt = `-- name: RejectPublicationAttempt :exec
UPDATE canonical_publication_attempts SET state='rejected' WHERE id=$1
`

func (q *Queries) RejectPublicationAttempt(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, rejectPublicationAttempt, id)
	return err
}

const renewPublicationAttempt = `-- name: RenewPublicationAttempt :one
UPDATE canonical_publication_attempts SET lease_until=GREATEST(lease_until,
 LEAST($2::timestamptz,clock_timestamp()+$3::bigint*interval '1 millisecond'))
WHERE id=$1 AND lease_until>clock_timestamp() AND $2::timestamptz>clock_timestamp()
RETURNING lease_until
`

type RenewPublicationAttemptParams struct {
	ID        pgtype.UUID
	ExpiresAt time.Time
	LeaseMs   int64
}

func (q *Queries) RenewPublicationAttempt(ctx context.Context, arg RenewPublicationAttemptParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, renewPublicationAttempt, arg.ID, arg.ExpiresAt, arg.LeaseMs)
	var lease_until time.Time
	err := row.Scan(&lease_until)
	return lease_until, err
}

const sealPublicationAttempt = `-- name: SealPublicationAttempt :exec
UPDATE canonical_publication_attempts SET state='sealed',seal_json=$2 WHERE id=$1
`

type SealPublicationAttemptParams struct {
	ID       pgtype.UUID
	SealJson *string
}

func (q *Queries) SealPublicationAttempt(ctx context.Context, arg SealPublicationAttemptParams) error {
	_, err := q.db.Exec(ctx, sealPublicationAttempt, arg.ID, arg.SealJson)
	return err
}

const storeValidatedPublicationPart = `-- name: StoreValidatedPublicationPart :exec
UPDATE canonical_publication_parts SET body=NULL,validated_body=$3,format_version=1 WHERE attempt_id=$1 AND ordinal=$2
`

type StoreValidatedPublicationPartParams struct {
	AttemptID     pgtype.UUID
	Ordinal       int32
	ValidatedBody []byte
}

func (q *Queries) StoreValidatedPublicationPart(ctx context.Context, arg StoreValidatedPublicationPartParams) error {
	_, err := q.db.Exec(ctx, storeValidatedPublicationPart, arg.AttemptID, arg.Ordinal, arg.ValidatedBody)
	return err
}

const subtractPublicationBytes = `-- name: SubtractPublicationBytes :exec
UPDATE canonical_publication_attempts SET retained_bytes=retained_bytes-$2,part_count=part_count-1 WHERE id=$1
`

type SubtractPublicationBytesParams struct {
	ID            pgtype.UUID
	RetainedBytes int64
}

func (q *Queries) SubtractPublicationBytes(ctx context.Context, arg SubtractPublicationBytesParams) error {
	_, err := q.db.Exec(ctx, subtractPublicationBytes, arg.ID, arg.RetainedBytes)
	return err
}
