// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: raw.sql

package db

import (
	"context"
	"time"
)

const acquireRawLock = `-- name: AcquireRawLock :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 1))
`

func (q *Queries) AcquireRawLock(ctx context.Context, lockKey string) error {
	_, err := q.db.Exec(ctx, acquireRawLock, lockKey)
	return err
}

const commitRawGeneration = `-- name: CommitRawGeneration :exec
UPDATE raw_generations
SET size_bytes = $1,
    chunk_count = $2,
    finalized = $3,
    updated_at = clock_timestamp()
WHERE object_id = $4 AND generation = $5
`

type CommitRawGenerationParams struct {
	SizeBytes  int64
	ChunkCount int64
	Finalized  bool
	ObjectID   string
	Generation int64
}

func (q *Queries) CommitRawGeneration(ctx context.Context, arg CommitRawGenerationParams) error {
	_, err := q.db.Exec(ctx, commitRawGeneration,
		arg.SizeBytes,
		arg.ChunkCount,
		arg.Finalized,
		arg.ObjectID,
		arg.Generation,
	)
	return err
}

const commitRawObject = `-- name: CommitRawObject :exec
UPDATE raw_objects
SET adapter_version = $1,
    captured_at = GREATEST(captured_at, $2::timestamptz),
    current_generation = $3,
    generation_count = $4,
    updated_at = clock_timestamp()
WHERE id = $5
`

type CommitRawObjectParams struct {
	AdapterVersion    string
	CapturedAt        time.Time
	CurrentGeneration int64
	GenerationCount   int64
	ID                string
}

func (q *Queries) CommitRawObject(ctx context.Context, arg CommitRawObjectParams) error {
	_, err := q.db.Exec(ctx, commitRawObject,
		arg.AdapterVersion,
		arg.CapturedAt,
		arg.CurrentGeneration,
		arg.GenerationCount,
		arg.ID,
	)
	return err
}

const getRawCanonicalSessionProject = `-- name: GetRawCanonicalSessionProject :one
SELECT project_id
FROM canonical_sessions
WHERE id = $1 AND record_state = 'active'
`

func (q *Queries) GetRawCanonicalSessionProject(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getRawCanonicalSessionProject, id)
	var project_id string
	err := row.Scan(&project_id)
	return project_id, err
}

const getRawChunkForReplay = `-- name: GetRawChunkForReplay :one
SELECT c.chunk_id, c.object_id, c.generation, c.ordinal, c.byte_offset,
       c.size_bytes, c.adapter_version AS chunk_adapter_version,
       c.captured_at AS chunk_captured_at, c.final, c.sha256, c.storage_key,
       o.project_id, o.session_id, o.source_name, o.media_type, o.adapter_id,
       o.client_redacted
FROM raw_chunks c
JOIN raw_objects o ON o.id = c.object_id
WHERE c.chunk_id = $1
`

type GetRawChunkForReplayRow struct {
	ChunkID             string
	ObjectID            string
	Generation          int64
	Ordinal             int64
	ByteOffset          int64
	SizeBytes           int64
	ChunkAdapterVersion string
	ChunkCapturedAt     time.Time
	Final               bool
	Sha256              string
	StorageKey          string
	ProjectID           string
	SessionID           string
	SourceName          string
	MediaType           string
	AdapterID           string
	ClientRedacted      bool
}

func (q *Queries) GetRawChunkForReplay(ctx context.Context, chunkID string) (GetRawChunkForReplayRow, error) {
	row := q.db.QueryRow(ctx, getRawChunkForReplay, chunkID)
	var i GetRawChunkForReplayRow
	err := row.Scan(
		&i.ChunkID,
		&i.ObjectID,
		&i.Generation,
		&i.Ordinal,
		&i.ByteOffset,
		&i.SizeBytes,
		&i.ChunkAdapterVersion,
		&i.ChunkCapturedAt,
		&i.Final,
		&i.Sha256,
		&i.StorageKey,
		&i.ProjectID,
		&i.SessionID,
		&i.SourceName,
		&i.MediaType,
		&i.AdapterID,
		&i.ClientRedacted,
	)
	return i, err
}

const getRawGenerationForRead = `-- name: GetRawGenerationForRead :one
SELECT object_id, generation, size_bytes, chunk_count, finalized
FROM raw_generations
WHERE object_id = $1 AND generation = $2
`

type GetRawGenerationForReadParams struct {
	ObjectID   string
	Generation int64
}

type GetRawGenerationForReadRow struct {
	ObjectID   string
	Generation int64
	SizeBytes  int64
	ChunkCount int64
	Finalized  bool
}

func (q *Queries) GetRawGenerationForRead(ctx context.Context, arg GetRawGenerationForReadParams) (GetRawGenerationForReadRow, error) {
	row := q.db.QueryRow(ctx, getRawGenerationForRead, arg.ObjectID, arg.Generation)
	var i GetRawGenerationForReadRow
	err := row.Scan(
		&i.ObjectID,
		&i.Generation,
		&i.SizeBytes,
		&i.ChunkCount,
		&i.Finalized,
	)
	return i, err
}

const getRawGenerationForUpdate = `-- name: GetRawGenerationForUpdate :one
SELECT object_id, generation, size_bytes, chunk_count, finalized
FROM raw_generations
WHERE object_id = $1 AND generation = $2
FOR UPDATE
`

type GetRawGenerationForUpdateParams struct {
	ObjectID   string
	Generation int64
}

type GetRawGenerationForUpdateRow struct {
	ObjectID   string
	Generation int64
	SizeBytes  int64
	ChunkCount int64
	Finalized  bool
}

func (q *Queries) GetRawGenerationForUpdate(ctx context.Context, arg GetRawGenerationForUpdateParams) (GetRawGenerationForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getRawGenerationForUpdate, arg.ObjectID, arg.Generation)
	var i GetRawGenerationForUpdateRow
	err := row.Scan(
		&i.ObjectID,
		&i.Generation,
		&i.SizeBytes,
		&i.ChunkCount,
		&i.Finalized,
	)
	return i, err
}

const getRawObjectForRead = `-- name: GetRawObjectForRead :one
SELECT o.id, o.project_id, o.session_id, o.source_name, o.media_type,
       o.adapter_id, o.adapter_version, o.captured_at, o.client_redacted,
       o.current_generation, o.generation_count,
       g.size_bytes AS current_size_bytes, g.finalized AS current_finalized
FROM raw_objects o
JOIN raw_generations g
  ON g.object_id = o.id AND g.generation = o.current_generation
WHERE o.id = $1
`

type GetRawObjectForReadRow struct {
	ID                string
	ProjectID         string
	SessionID         string
	SourceName        string
	MediaType         string
	AdapterID         string
	AdapterVersion    string
	CapturedAt        time.Time
	ClientRedacted    bool
	CurrentGeneration int64
	GenerationCount   int64
	CurrentSizeBytes  int64
	CurrentFinalized  bool
}

func (q *Queries) GetRawObjectForRead(ctx context.Context, id string) (GetRawObjectForReadRow, error) {
	row := q.db.QueryRow(ctx, getRawObjectForRead, id)
	var i GetRawObjectForReadRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SessionID,
		&i.SourceName,
		&i.MediaType,
		&i.AdapterID,
		&i.AdapterVersion,
		&i.CapturedAt,
		&i.ClientRedacted,
		&i.CurrentGeneration,
		&i.GenerationCount,
		&i.CurrentSizeBytes,
		&i.CurrentFinalized,
	)
	return i, err
}

const getRawObjectForUpdate = `-- name: GetRawObjectForUpdate :one
SELECT id, project_id, session_id, source_name, media_type, adapter_id,
       adapter_version, captured_at, client_redacted, current_generation,
       generation_count
FROM raw_objects
WHERE id = $1
FOR UPDATE
`

type GetRawObjectForUpdateRow struct {
	ID                string
	ProjectID         string
	SessionID         string
	SourceName        string
	MediaType         string
	AdapterID         string
	AdapterVersion    string
	CapturedAt        time.Time
	ClientRedacted    bool
	CurrentGeneration int64
	GenerationCount   int64
}

func (q *Queries) GetRawObjectForUpdate(ctx context.Context, id string) (GetRawObjectForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getRawObjectForUpdate, id)
	var i GetRawObjectForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SessionID,
		&i.SourceName,
		&i.MediaType,
		&i.AdapterID,
		&i.AdapterVersion,
		&i.CapturedAt,
		&i.ClientRedacted,
		&i.CurrentGeneration,
		&i.GenerationCount,
	)
	return i, err
}

const insertRawChunk = `-- name: InsertRawChunk :exec
INSERT INTO raw_chunks (
    chunk_id, object_id, generation, ordinal, byte_offset, size_bytes,
    adapter_version, captured_at, final, sha256, storage_key
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertRawChunkParams struct {
	ChunkID        string
	ObjectID       string
	Generation     int64
	Ordinal        int64
	ByteOffset     int64
	SizeBytes      int64
	AdapterVersion string
	CapturedAt     time.Time
	Final          bool
	Sha256         string
	StorageKey     string
}

func (q *Queries) InsertRawChunk(ctx context.Context, arg InsertRawChunkParams) error {
	_, err := q.db.Exec(ctx, insertRawChunk,
		arg.ChunkID,
		arg.ObjectID,
		arg.Generation,
		arg.Ordinal,
		arg.ByteOffset,
		arg.SizeBytes,
		arg.AdapterVersion,
		arg.CapturedAt,
		arg.Final,
		arg.Sha256,
		arg.StorageKey,
	)
	return err
}

const insertRawGeneration = `-- name: InsertRawGeneration :exec
INSERT INTO raw_generations (object_id, generation)
VALUES ($1, $2)
`

type InsertRawGenerationParams struct {
	ObjectID   string
	Generation int64
}

func (q *Queries) InsertRawGeneration(ctx context.Context, arg InsertRawGenerationParams) error {
	_, err := q.db.Exec(ctx, insertRawGeneration, arg.ObjectID, arg.Generation)
	return err
}

const insertRawObject = `-- name: InsertRawObject :exec
INSERT INTO raw_objects (
    id, project_id, session_id, source_name, media_type, adapter_id,
    adapter_version, captured_at, client_redacted,
    current_generation, generation_count
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 1, 1)
`

type InsertRawObjectParams struct {
	ID             string
	ProjectID      string
	SessionID      string
	SourceName     string
	MediaType      string
	AdapterID      string
	AdapterVersion string
	CapturedAt     time.Time
	ClientRedacted bool
}

func (q *Queries) InsertRawObject(ctx context.Context, arg InsertRawObjectParams) error {
	_, err := q.db.Exec(ctx, insertRawObject,
		arg.ID,
		arg.ProjectID,
		arg.SessionID,
		arg.SourceName,
		arg.MediaType,
		arg.AdapterID,
		arg.AdapterVersion,
		arg.CapturedAt,
		arg.ClientRedacted,
	)
	return err
}

const listRawChunksAfter = `-- name: ListRawChunksAfter :many
SELECT chunk_id, object_id, generation, ordinal, byte_offset, size_bytes,
       adapter_version, captured_at, final, sha256, storage_key
FROM raw_chunks
WHERE object_id = $1
  AND generation = $2
  AND ordinal > $3
ORDER BY ordinal
LIMIT $4
`

type ListRawChunksAfterParams struct {
	ObjectID     string
	Generation   int64
	AfterOrdinal int64
	ResultLimit  int32
}

type ListRawChunksAfterRow struct {
	ChunkID        string
	ObjectID       string
	Generation     int64
	Ordinal        int64
	ByteOffset     int64
	SizeBytes      int64
	AdapterVersion string
	CapturedAt     time.Time
	Final          bool
	Sha256         string
	StorageKey     string
}

func (q *Queries) ListRawChunksAfter(ctx context.Context, arg ListRawChunksAfterParams) ([]ListRawChunksAfterRow, error) {
	rows, err := q.db.Query(ctx, listRawChunksAfter,
		arg.ObjectID,
		arg.Generation,
		arg.AfterOrdinal,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRawChunksAfterRow{}
	for rows.Next() {
		var i ListRawChunksAfterRow
		if err := rows.Scan(
			&i.ChunkID,
			&i.ObjectID,
			&i.Generation,
			&i.Ordinal,
			&i.ByteOffset,
			&i.SizeBytes,
			&i.AdapterVersion,
			&i.CapturedAt,
			&i.Final,
			&i.Sha256,
			&i.StorageKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRawSessionObjects = `-- name: ListRawSessionObjects :many
SELECT o.id, o.project_id, o.session_id, o.source_name, o.media_type,
       o.adapter_id, o.adapter_version, o.captured_at, o.client_redacted,
       o.current_generation, o.generation_count,
       g.size_bytes AS current_size_bytes, g.finalized AS current_finalized
FROM raw_objects o
JOIN raw_generations g
  ON g.object_id = o.id AND g.generation = o.current_generation
WHERE o.session_id = $1
ORDER BY o.captured_at DESC, o.id
`

type ListRawSessionObjectsRow struct {
	ID                string
	ProjectID         string
	SessionID         string
	SourceName        string
	MediaType         string
	AdapterID         string
	AdapterVersion    string
	CapturedAt        time.Time
	ClientRedacted    bool
	CurrentGeneration int64
	GenerationCount   int64
	CurrentSizeBytes  int64
	CurrentFinalized  bool
}

func (q *Queries) ListRawSessionObjects(ctx context.Context, sessionID string) ([]ListRawSessionObjectsRow, error) {
	rows, err := q.db.Query(ctx, listRawSessionObjects, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRawSessionObjectsRow{}
	for rows.Next() {
		var i ListRawSessionObjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SessionID,
			&i.SourceName,
			&i.MediaType,
			&i.AdapterID,
			&i.AdapterVersion,
			&i.CapturedAt,
			&i.ClientRedacted,
			&i.CurrentGeneration,
			&i.GenerationCount,
			&i.CurrentSizeBytes,
			&i.CurrentFinalized,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
