// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: search.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const ackProjectionChanges = `-- name: AckProjectionChanges :exec
UPDATE canonical_projection_changes
SET processed_at = clock_timestamp(),
    lease_owner = NULL,
    lease_until = NULL
WHERE id = ANY($1::bigint[])
  AND lease_owner = $2
`

type AckProjectionChangesParams struct {
	ChangeIds  []int64
	LeaseOwner *string
}

func (q *Queries) AckProjectionChanges(ctx context.Context, arg AckProjectionChangesParams) error {
	_, err := q.db.Exec(ctx, ackProjectionChanges, arg.ChangeIds, arg.LeaseOwner)
	return err
}

const advanceSearchCheckpoint = `-- name: AdvanceSearchCheckpoint :exec
INSERT INTO project_search_checkpoints (project_id, indexed_through)
VALUES ($1, $2)
ON CONFLICT (project_id) DO UPDATE
SET indexed_through = GREATEST(
    project_search_checkpoints.indexed_through,
    EXCLUDED.indexed_through
)
`

type AdvanceSearchCheckpointParams struct {
	ProjectID      string
	IndexedThrough time.Time
}

func (q *Queries) AdvanceSearchCheckpoint(ctx context.Context, arg AdvanceSearchCheckpointParams) error {
	_, err := q.db.Exec(ctx, advanceSearchCheckpoint, arg.ProjectID, arg.IndexedThrough)
	return err
}

const claimProjectionChanges = `-- name: ClaimProjectionChanges :many
WITH candidates AS (
    SELECT id
    FROM canonical_projection_changes
    WHERE processed_at IS NULL
      AND (lease_until IS NULL OR lease_until <= clock_timestamp())
    ORDER BY id
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
UPDATE canonical_projection_changes AS changes
SET lease_owner = $1,
    lease_until = $2,
    attempts = attempts + 1
FROM candidates
WHERE changes.id = candidates.id
RETURNING changes.id
`

type ClaimProjectionChangesParams struct {
	LeaseOwner *string
	LeaseUntil pgtype.Timestamptz
	BatchLimit int32
}

func (q *Queries) ClaimProjectionChanges(ctx context.Context, arg ClaimProjectionChangesParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, claimProjectionChanges, arg.LeaseOwner, arg.LeaseUntil, arg.BatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSearchCheckpoint = `-- name: GetSearchCheckpoint :one
SELECT indexed_through
FROM project_search_checkpoints
WHERE project_id = $1
`

func (q *Queries) GetSearchCheckpoint(ctx context.Context, projectID string) (time.Time, error) {
	row := q.db.QueryRow(ctx, getSearchCheckpoint, projectID)
	var indexed_through time.Time
	err := row.Scan(&indexed_through)
	return indexed_through, err
}

const loadProjectionChanges = `-- name: LoadProjectionChanges :many
WITH RECURSIVE requested AS (
    SELECT changes.id AS change_id, events.id AS event_id,
           events.session_id, events.thread_id, events.author,
           events.occurred_at, events.text, events.tool_label,
           events.ingest_seq, events.observed_at,
           sessions.project_id, sessions.title AS session_title,
           sessions.actor_harness AS harness
    FROM canonical_projection_changes changes
    JOIN canonical_events events ON events.id = changes.event_id
    JOIN canonical_sessions sessions ON sessions.id = events.session_id
    WHERE changes.id = ANY($1::bigint[])
      AND changes.lease_owner = $2
), lineage AS (
    SELECT requested.change_id, threads.session_id, threads.id,
           threads.label, threads.parent_thread_id, 0 AS depth
    FROM requested
    JOIN canonical_threads threads
      ON threads.session_id = requested.session_id
     AND threads.id = requested.thread_id
    UNION ALL
    SELECT lineage.change_id, parent.session_id, parent.id,
           parent.label, parent.parent_thread_id, lineage.depth + 1
    FROM lineage
    JOIN canonical_threads parent
      ON parent.session_id = lineage.session_id
     AND parent.id = lineage.parent_thread_id
), paths AS (
    SELECT change_id,
           array_agg(id ORDER BY depth DESC)::text[] AS thread_path_ids,
           array_agg(label ORDER BY depth DESC)::text[] AS thread_path_labels
    FROM lineage
    GROUP BY change_id
)
SELECT requested.change_id, requested.project_id, requested.session_id,
       requested.session_title, requested.thread_id,
       paths.thread_path_ids, paths.thread_path_labels,
       requested.event_id, requested.author, requested.harness,
       requested.occurred_at, requested.text, requested.tool_label,
       requested.ingest_seq, requested.observed_at
FROM requested
JOIN paths ON paths.change_id = requested.change_id
ORDER BY requested.change_id
`

type LoadProjectionChangesParams struct {
	ChangeIds  []int64
	LeaseOwner *string
}

type LoadProjectionChangesRow struct {
	ChangeID         int64
	ProjectID        string
	SessionID        string
	SessionTitle     string
	ThreadID         string
	ThreadPathIds    []string
	ThreadPathLabels []string
	EventID          string
	Author           string
	Harness          string
	OccurredAt       time.Time
	Text             string
	ToolLabel        string
	IngestSeq        int64
	ObservedAt       time.Time
}

func (q *Queries) LoadProjectionChanges(ctx context.Context, arg LoadProjectionChangesParams) ([]LoadProjectionChangesRow, error) {
	rows, err := q.db.Query(ctx, loadProjectionChanges, arg.ChangeIds, arg.LeaseOwner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadProjectionChangesRow{}
	for rows.Next() {
		var i LoadProjectionChangesRow
		if err := rows.Scan(
			&i.ChangeID,
			&i.ProjectID,
			&i.SessionID,
			&i.SessionTitle,
			&i.ThreadID,
			&i.ThreadPathIds,
			&i.ThreadPathLabels,
			&i.EventID,
			&i.Author,
			&i.Harness,
			&i.OccurredAt,
			&i.Text,
			&i.ToolLabel,
			&i.IngestSeq,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDocuments = `-- name: SearchDocuments :many
WITH terms AS (
    SELECT lower($3::text) AS literal,
           websearch_to_tsquery('simple'::regconfig, $3::text) AS parsed
), matches AS (
    SELECT documents.event_id, documents.project_id, documents.session_id,
           documents.session_title, documents.thread_id,
           documents.thread_path_ids, documents.thread_path_labels,
           documents.author, documents.harness, documents.occurred_at,
           documents.text, documents.tool_label, documents.ingest_seq,
           documents.observed_at,
           (strpos(documents.search_text, terms.literal) > 0) AS literal_match,
           ts_rank_cd(documents.search_vector, terms.parsed) AS text_rank
    FROM project_search_documents documents
    CROSS JOIN terms
    WHERE documents.project_id = $4
      AND (
          strpos(documents.search_text, terms.literal) > 0
          OR documents.search_vector @@ terms.parsed
      )
), ranked AS (
    SELECT matches.event_id, matches.project_id, matches.session_id, matches.session_title, matches.thread_id, matches.thread_path_ids, matches.thread_path_labels, matches.author, matches.harness, matches.occurred_at, matches.text, matches.tool_label, matches.ingest_seq, matches.observed_at, matches.literal_match, matches.text_rank, count(*) OVER ()::bigint AS total_count
    FROM matches
)
SELECT event_id, project_id, session_id, session_title, thread_id,
       thread_path_ids, thread_path_labels, author, harness, occurred_at,
       text, tool_label, ingest_seq, observed_at, total_count
FROM ranked
ORDER BY literal_match DESC, text_rank DESC, occurred_at DESC, event_id
LIMIT $2
OFFSET $1
`

type SearchDocumentsParams struct {
	ResultOffset int32
	ResultLimit  int32
	Term         string
	ProjectID    string
}

type SearchDocumentsRow struct {
	EventID          string
	ProjectID        string
	SessionID        string
	SessionTitle     string
	ThreadID         string
	ThreadPathIds    []string
	ThreadPathLabels []string
	Author           string
	Harness          string
	OccurredAt       time.Time
	Text             string
	ToolLabel        string
	IngestSeq        int64
	ObservedAt       time.Time
	TotalCount       int64
}

func (q *Queries) SearchDocuments(ctx context.Context, arg SearchDocumentsParams) ([]SearchDocumentsRow, error) {
	rows, err := q.db.Query(ctx, searchDocuments,
		arg.ResultOffset,
		arg.ResultLimit,
		arg.Term,
		arg.ProjectID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchDocumentsRow{}
	for rows.Next() {
		var i SearchDocumentsRow
		if err := rows.Scan(
			&i.EventID,
			&i.ProjectID,
			&i.SessionID,
			&i.SessionTitle,
			&i.ThreadID,
			&i.ThreadPathIds,
			&i.ThreadPathLabels,
			&i.Author,
			&i.Harness,
			&i.OccurredAt,
			&i.Text,
			&i.ToolLabel,
			&i.IngestSeq,
			&i.ObservedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSearchDocument = `-- name: UpsertSearchDocument :exec
INSERT INTO project_search_documents (
    event_id, project_id, session_id, session_title, thread_id,
    thread_path_ids, thread_path_labels, author, harness, occurred_at,
    text, tool_label, ingest_seq, observed_at, search_text
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12,
    $13, $14,
    lower(
        $4::text || ' ' ||
        array_to_string($7::text[], ' ') || ' ' ||
        $8::text || ' ' || $9::text || ' ' ||
        $11::text || ' ' || $12::text
    )
)
ON CONFLICT (event_id) DO UPDATE
SET project_id = EXCLUDED.project_id,
    session_id = EXCLUDED.session_id,
    session_title = EXCLUDED.session_title,
    thread_id = EXCLUDED.thread_id,
    thread_path_ids = EXCLUDED.thread_path_ids,
    thread_path_labels = EXCLUDED.thread_path_labels,
    author = EXCLUDED.author,
    harness = EXCLUDED.harness,
    occurred_at = EXCLUDED.occurred_at,
    text = EXCLUDED.text,
    tool_label = EXCLUDED.tool_label,
    ingest_seq = EXCLUDED.ingest_seq,
    observed_at = EXCLUDED.observed_at,
    indexed_at = clock_timestamp(),
    search_text = EXCLUDED.search_text
WHERE project_search_documents.ingest_seq <= EXCLUDED.ingest_seq
`

type UpsertSearchDocumentParams struct {
	EventID          string
	ProjectID        string
	SessionID        string
	SessionTitle     string
	ThreadID         string
	ThreadPathIds    []string
	ThreadPathLabels []string
	Author           string
	Harness          string
	OccurredAt       time.Time
	Text             string
	ToolLabel        string
	IngestSeq        int64
	ObservedAt       time.Time
}

func (q *Queries) UpsertSearchDocument(ctx context.Context, arg UpsertSearchDocumentParams) error {
	_, err := q.db.Exec(ctx, upsertSearchDocument,
		arg.EventID,
		arg.ProjectID,
		arg.SessionID,
		arg.SessionTitle,
		arg.ThreadID,
		arg.ThreadPathIds,
		arg.ThreadPathLabels,
		arg.Author,
		arg.Harness,
		arg.OccurredAt,
		arg.Text,
		arg.ToolLabel,
		arg.IngestSeq,
		arg.ObservedAt,
	)
	return err
}
