// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: session_analytics.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const analyticsNativeBytes = `-- name: AnalyticsNativeBytes :one
SELECT COALESCE(sum(octet_length(text)::bigint+octet_length(tool_update_json)+octet_length(tool_label)+256),0)::bigint AS source_bytes
FROM canonical_events WHERE session_id=$1
`

func (q *Queries) AnalyticsNativeBytes(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRow(ctx, analyticsNativeBytes, sessionID)
	var source_bytes int64
	err := row.Scan(&source_bytes)
	return source_bytes, err
}

const analyticsPublicationBytes = `-- name: AnalyticsPublicationBytes :one
SELECT COALESCE(sum(p.stored_bytes),0)::bigint AS stored_bytes
FROM canonical_publication_parts p
WHERE p.attempt_id=$1 AND EXISTS (
 SELECT 1 FROM canonical_publication_members m WHERE m.attempt_id=p.attempt_id AND m.part_ordinal=p.ordinal AND m.kind IN ('event','usage')
)
`

func (q *Queries) AnalyticsPublicationBytes(ctx context.Context, attemptID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, analyticsPublicationBytes, attemptID)
	var stored_bytes int64
	err := row.Scan(&stored_bytes)
	return stored_bytes, err
}

const listAnalyticsNativeEvents = `-- name: ListAnalyticsNativeEvents :many
SELECT id,session_id,thread_id,source_key,revision,projection_revision,
 source_order,event_index,order_fidelity,fidelity,kind,author,occurred_at,tool_label,child_thread_id,
 encode(sha256(convert_to(text,'UTF8')),'hex')::text AS text_digest,
 encode(sha256(convert_to(tool_update_json,'UTF8')),'hex')::text AS tool_digest,
 CASE WHEN tool_update_json='' THEN '' ELSE (tool_update_json::jsonb - 'rawInput' - 'rawOutput')::text END::text AS tool_update_json
FROM canonical_events WHERE session_id=$1 ORDER BY id LIMIT $2
`

type ListAnalyticsNativeEventsParams struct {
	SessionID string
	Limit     int32
}

type ListAnalyticsNativeEventsRow struct {
	ID                 string
	SessionID          string
	ThreadID           string
	SourceKey          string
	Revision           int64
	ProjectionRevision int64
	SourceOrder        int64
	EventIndex         int64
	OrderFidelity      string
	Fidelity           string
	Kind               string
	Author             string
	OccurredAt         *time.Time
	ToolLabel          string
	ChildThreadID      *string
	TextDigest         string
	ToolDigest         string
	ToolUpdateJson     string
}

func (q *Queries) ListAnalyticsNativeEvents(ctx context.Context, arg ListAnalyticsNativeEventsParams) ([]ListAnalyticsNativeEventsRow, error) {
	rows, err := q.db.Query(ctx, listAnalyticsNativeEvents, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnalyticsNativeEventsRow{}
	for rows.Next() {
		var i ListAnalyticsNativeEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ThreadID,
			&i.SourceKey,
			&i.Revision,
			&i.ProjectionRevision,
			&i.SourceOrder,
			&i.EventIndex,
			&i.OrderFidelity,
			&i.Fidelity,
			&i.Kind,
			&i.Author,
			&i.OccurredAt,
			&i.ToolLabel,
			&i.ChildThreadID,
			&i.TextDigest,
			&i.ToolDigest,
			&i.ToolUpdateJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalyticsNativeUsage = `-- name: ListAnalyticsNativeUsage :many
SELECT source_key, session_id, thread_id, revision, digest, occurred_at, model, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens FROM canonical_usage WHERE session_id=$1 ORDER BY source_key LIMIT $2
`

type ListAnalyticsNativeUsageParams struct {
	SessionID string
	Limit     int32
}

func (q *Queries) ListAnalyticsNativeUsage(ctx context.Context, arg ListAnalyticsNativeUsageParams) ([]CanonicalUsage, error) {
	rows, err := q.db.Query(ctx, listAnalyticsNativeUsage, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CanonicalUsage{}
	for rows.Next() {
		var i CanonicalUsage
		if err := rows.Scan(
			&i.SourceKey,
			&i.SessionID,
			&i.ThreadID,
			&i.Revision,
			&i.Digest,
			&i.OccurredAt,
			&i.Model,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalyticsPublicationMembers = `-- name: ListAnalyticsPublicationMembers :many
SELECT kind,record_id,source_key,part_ordinal,entry_index
FROM canonical_publication_members
WHERE attempt_id=$1 AND kind IN ('event','usage')
ORDER BY part_ordinal,kind,entry_index LIMIT $2
`

type ListAnalyticsPublicationMembersParams struct {
	AttemptID pgtype.UUID
	Limit     int32
}

type ListAnalyticsPublicationMembersRow struct {
	Kind        string
	RecordID    string
	SourceKey   string
	PartOrdinal int32
	EntryIndex  int32
}

func (q *Queries) ListAnalyticsPublicationMembers(ctx context.Context, arg ListAnalyticsPublicationMembersParams) ([]ListAnalyticsPublicationMembersRow, error) {
	rows, err := q.db.Query(ctx, listAnalyticsPublicationMembers, arg.AttemptID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnalyticsPublicationMembersRow{}
	for rows.Next() {
		var i ListAnalyticsPublicationMembersRow
		if err := rows.Scan(
			&i.Kind,
			&i.RecordID,
			&i.SourceKey,
			&i.PartOrdinal,
			&i.EntryIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalyticsThreads = `-- name: ListAnalyticsThreads :many
SELECT session_id,id,source_key,revision,digest,label,summary,parent_thread_id,capture_status
FROM visible_canonical_threads WHERE session_id=$1 ORDER BY id LIMIT $2
`

type ListAnalyticsThreadsParams struct {
	SessionID string
	Limit     int32
}

func (q *Queries) ListAnalyticsThreads(ctx context.Context, arg ListAnalyticsThreadsParams) ([]VisibleCanonicalThread, error) {
	rows, err := q.db.Query(ctx, listAnalyticsThreads, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VisibleCanonicalThread{}
	for rows.Next() {
		var i VisibleCanonicalThread
		if err := rows.Scan(
			&i.SessionID,
			&i.ID,
			&i.SourceKey,
			&i.Revision,
			&i.Digest,
			&i.Label,
			&i.Summary,
			&i.ParentThreadID,
			&i.CaptureStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
