// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: usage.sql

package db

import (
	"context"
	"time"
)

const getUsageForUpdate = `-- name: GetUsageForUpdate :one
SELECT source_key, session_id, thread_id, revision, digest, occurred_at, model, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens FROM canonical_usage WHERE source_key = $1 FOR UPDATE
`

func (q *Queries) GetUsageForUpdate(ctx context.Context, sourceKey string) (CanonicalUsage, error) {
	row := q.db.QueryRow(ctx, getUsageForUpdate, sourceKey)
	var i CanonicalUsage
	err := row.Scan(
		&i.SourceKey,
		&i.SessionID,
		&i.ThreadID,
		&i.Revision,
		&i.Digest,
		&i.OccurredAt,
		&i.Model,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
	)
	return i, err
}

const upsertUsage = `-- name: UpsertUsage :exec
INSERT INTO canonical_usage (source_key, session_id, thread_id, revision, digest, occurred_at, model,
    input_tokens, output_tokens, cache_read_tokens, cache_write_tokens)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
ON CONFLICT (source_key) DO UPDATE SET revision=EXCLUDED.revision, digest=EXCLUDED.digest,
    occurred_at=EXCLUDED.occurred_at, model=EXCLUDED.model, input_tokens=EXCLUDED.input_tokens,
    output_tokens=EXCLUDED.output_tokens, cache_read_tokens=EXCLUDED.cache_read_tokens,
    cache_write_tokens=EXCLUDED.cache_write_tokens
WHERE EXCLUDED.revision > canonical_usage.revision
`

type UpsertUsageParams struct {
	SourceKey        string
	SessionID        string
	ThreadID         string
	Revision         int64
	Digest           string
	OccurredAt       time.Time
	Model            string
	InputTokens      *int64
	OutputTokens     *int64
	CacheReadTokens  *int64
	CacheWriteTokens *int64
}

func (q *Queries) UpsertUsage(ctx context.Context, arg UpsertUsageParams) error {
	_, err := q.db.Exec(ctx, upsertUsage,
		arg.SourceKey,
		arg.SessionID,
		arg.ThreadID,
		arg.Revision,
		arg.Digest,
		arg.OccurredAt,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheReadTokens,
		arg.CacheWriteTokens,
	)
	return err
}
