// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: workspace.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const listWorkspaceProjects = `-- name: ListWorkspaceProjects :many
SELECT projects.id, projects.team_id, projects.name, projects.project_type, projects.state,
       projects.captured_through,
       COUNT(sessions.id)::bigint AS session_count,
       COUNT(sessions.id) FILTER (
           WHERE sessions.status = 'active'
             AND sessions.updated_at >= $1::timestamptz
       )::bigint AS active_session_count
FROM canonical_projects projects
JOIN team_memberships membership ON membership.team_id = projects.team_id
LEFT JOIN canonical_sessions sessions
  ON sessions.project_id = projects.id AND sessions.record_state = 'active'
WHERE membership.user_id = $2
  AND membership.status = 'active'
  AND projects.state <> 'deleted'
GROUP BY projects.id
ORDER BY projects.team_id, lower(projects.name), projects.id
`

type ListWorkspaceProjectsParams struct {
	ActiveSince time.Time
	UserID      pgtype.UUID
}

type ListWorkspaceProjectsRow struct {
	ID                 string
	TeamID             string
	Name               string
	ProjectType        string
	State              string
	CapturedThrough    time.Time
	SessionCount       int64
	ActiveSessionCount int64
}

func (q *Queries) ListWorkspaceProjects(ctx context.Context, arg ListWorkspaceProjectsParams) ([]ListWorkspaceProjectsRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceProjects, arg.ActiveSince, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceProjectsRow{}
	for rows.Next() {
		var i ListWorkspaceProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.ProjectType,
			&i.State,
			&i.CapturedThrough,
			&i.SessionCount,
			&i.ActiveSessionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceTeams = `-- name: ListWorkspaceTeams :many
SELECT teams.id, teams.name
FROM workspace_teams teams
JOIN team_memberships membership ON membership.team_id = teams.id
WHERE membership.user_id = $1
  AND membership.status = 'active'
ORDER BY lower(teams.name), teams.id
`

type ListWorkspaceTeamsRow struct {
	ID   string
	Name string
}

func (q *Queries) ListWorkspaceTeams(ctx context.Context, userID pgtype.UUID) ([]ListWorkspaceTeamsRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceTeams, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceTeamsRow{}
	for rows.Next() {
		var i ListWorkspaceTeamsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
