// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: workspace.sql

package db

import (
	"context"
	"time"
)

const listWorkspaceProjects = `-- name: ListWorkspaceProjects :many
SELECT projects.id, projects.team_id, projects.name, projects.project_type,
       projects.captured_through,
       COUNT(sessions.id)::bigint AS session_count,
       COUNT(sessions.id) FILTER (
           WHERE sessions.status = 'active'
             AND sessions.updated_at >= $1::timestamptz
       )::bigint AS active_session_count
FROM canonical_projects projects
LEFT JOIN canonical_sessions sessions ON sessions.project_id = projects.id
GROUP BY projects.id
ORDER BY projects.team_id, lower(projects.name), projects.id
`

type ListWorkspaceProjectsRow struct {
	ID                 string
	TeamID             string
	Name               string
	ProjectType        string
	CapturedThrough    time.Time
	SessionCount       int64
	ActiveSessionCount int64
}

func (q *Queries) ListWorkspaceProjects(ctx context.Context, activeSince time.Time) ([]ListWorkspaceProjectsRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceProjects, activeSince)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceProjectsRow{}
	for rows.Next() {
		var i ListWorkspaceProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.ProjectType,
			&i.CapturedThrough,
			&i.SessionCount,
			&i.ActiveSessionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceTeams = `-- name: ListWorkspaceTeams :many
SELECT id, name
FROM workspace_teams
ORDER BY lower(name), id
`

type ListWorkspaceTeamsRow struct {
	ID   string
	Name string
}

func (q *Queries) ListWorkspaceTeams(ctx context.Context) ([]ListWorkspaceTeamsRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceTeamsRow{}
	for rows.Next() {
		var i ListWorkspaceTeamsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
