// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: authentication.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireAuthenticationLock = `-- name: AcquireAuthenticationLock :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

func (q *Queries) AcquireAuthenticationLock(ctx context.Context, lockKey string) error {
	_, err := q.db.Exec(ctx, acquireAuthenticationLock, lockKey)
	return err
}

const advanceCLIPoll = `-- name: AdvanceCLIPoll :one
UPDATE auth_cli_device_authorizations
SET next_poll_at = clock_timestamp() + $2::integer * interval '1 second',
    poll_interval_seconds = $2::integer
WHERE id = $1 AND status = 'pending'
RETURNING next_poll_at
`

type AdvanceCLIPollParams struct {
	ID              pgtype.UUID
	IntervalSeconds int32
}

func (q *Queries) AdvanceCLIPoll(ctx context.Context, arg AdvanceCLIPollParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, advanceCLIPoll, arg.ID, arg.IntervalSeconds)
	var next_poll_at time.Time
	err := row.Scan(&next_poll_at)
	return next_poll_at, err
}

const approveCLIAuthorization = `-- name: ApproveCLIAuthorization :exec
UPDATE auth_cli_device_authorizations
SET status = 'approved_unclaimed', approving_user_id = $2, decision_at = clock_timestamp()
WHERE id = $1 AND status = 'pending'
`

type ApproveCLIAuthorizationParams struct {
	ID              pgtype.UUID
	ApprovingUserID pgtype.UUID
}

func (q *Queries) ApproveCLIAuthorization(ctx context.Context, arg ApproveCLIAuthorizationParams) error {
	_, err := q.db.Exec(ctx, approveCLIAuthorization, arg.ID, arg.ApprovingUserID)
	return err
}

const bindCLIReviewSession = `-- name: BindCLIReviewSession :one
UPDATE auth_cli_device_authorizations
SET review_web_session_id = $2, reviewed_at = clock_timestamp()
WHERE id = $1 AND status = 'pending' AND review_web_session_id IS NULL
RETURNING reviewed_at
`

type BindCLIReviewSessionParams struct {
	ID                 pgtype.UUID
	ReviewWebSessionID pgtype.UUID
}

func (q *Queries) BindCLIReviewSession(ctx context.Context, arg BindCLIReviewSessionParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, bindCLIReviewSession, arg.ID, arg.ReviewWebSessionID)
	var reviewed_at pgtype.Timestamptz
	err := row.Scan(&reviewed_at)
	return reviewed_at, err
}

const claimCLIAuthorization = `-- name: ClaimCLIAuthorization :exec
UPDATE auth_cli_device_authorizations
SET status = 'claimed', claimed_at = clock_timestamp(), issued_credential_id = $2,
    terminal_at = clock_timestamp()
WHERE id = $1 AND status = 'approved_unclaimed'
`

type ClaimCLIAuthorizationParams struct {
	ID                 pgtype.UUID
	IssuedCredentialID pgtype.UUID
}

func (q *Queries) ClaimCLIAuthorization(ctx context.Context, arg ClaimCLIAuthorizationParams) error {
	_, err := q.db.Exec(ctx, claimCLIAuthorization, arg.ID, arg.IssuedCredentialID)
	return err
}

const claimFederatedLogin = `-- name: ClaimFederatedLogin :one
UPDATE auth_federated_login_transactions
SET status = 'completing'
WHERE id = $1 AND status = 'pending' AND expires_at > clock_timestamp()
RETURNING created_at, expires_at
`

type ClaimFederatedLoginRow struct {
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) ClaimFederatedLogin(ctx context.Context, id pgtype.UUID) (ClaimFederatedLoginRow, error) {
	row := q.db.QueryRow(ctx, claimFederatedLogin, id)
	var i ClaimFederatedLoginRow
	err := row.Scan(&i.CreatedAt, &i.ExpiresAt)
	return i, err
}

const databaseTime = `-- name: DatabaseTime :one
SELECT clock_timestamp()::timestamptz AS now
`

func (q *Queries) DatabaseTime(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, databaseTime)
	var now time.Time
	err := row.Scan(&now)
	return now, err
}

const deleteCLIAuthorizationBatch = `-- name: DeleteCLIAuthorizationBatch :execrows
WITH candidates AS (
    SELECT a.id FROM auth_cli_device_authorizations a
    WHERE a.terminal_at <= clock_timestamp() - $1::integer * interval '1 second'
    ORDER BY a.terminal_at, a.id LIMIT $2::integer
    FOR UPDATE OF a SKIP LOCKED
)
DELETE FROM auth_cli_device_authorizations a USING candidates c WHERE a.id = c.id
`

type DeleteCLIAuthorizationBatchParams struct {
	RetentionSeconds int32
	BatchSize        int32
}

func (q *Queries) DeleteCLIAuthorizationBatch(ctx context.Context, arg DeleteCLIAuthorizationBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCLIAuthorizationBatch, arg.RetentionSeconds, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCLICredentialBatch = `-- name: DeleteCLICredentialBatch :execrows
WITH candidates AS (
    SELECT c.id FROM auth_cli_credentials c
    WHERE c.revoked_at <= clock_timestamp() - $1::integer * interval '1 second'
      AND NOT EXISTS (SELECT 1 FROM auth_cli_device_authorizations a WHERE a.issued_credential_id = c.id)
    ORDER BY c.revoked_at, c.id LIMIT $2::integer
    FOR UPDATE OF c SKIP LOCKED
)
DELETE FROM auth_cli_credentials c USING candidates x WHERE c.id = x.id
`

type DeleteCLICredentialBatchParams struct {
	RetentionSeconds int32
	BatchSize        int32
}

func (q *Queries) DeleteCLICredentialBatch(ctx context.Context, arg DeleteCLICredentialBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCLICredentialBatch, arg.RetentionSeconds, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCodeAttemptWindowBatch = `-- name: DeleteCodeAttemptWindowBatch :execrows
WITH candidates AS (
    SELECT web_session_id, window_start FROM auth_user_code_attempt_windows
    WHERE window_start <= clock_timestamp() - $1::integer * interval '1 second'
    ORDER BY window_start, web_session_id LIMIT $2::integer
    FOR UPDATE SKIP LOCKED
)
DELETE FROM auth_user_code_attempt_windows w USING candidates c
WHERE w.web_session_id = c.web_session_id AND w.window_start = c.window_start
`

type DeleteCodeAttemptWindowBatchParams struct {
	RetentionSeconds int32
	BatchSize        int32
}

func (q *Queries) DeleteCodeAttemptWindowBatch(ctx context.Context, arg DeleteCodeAttemptWindowBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCodeAttemptWindowBatch, arg.RetentionSeconds, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFederatedLoginBatch = `-- name: DeleteFederatedLoginBatch :execrows
WITH candidates AS (
    SELECT id FROM auth_federated_login_transactions
    WHERE terminal_at <= clock_timestamp() - $1::integer * interval '1 second'
    ORDER BY terminal_at, id LIMIT $2::integer
    FOR UPDATE SKIP LOCKED
)
DELETE FROM auth_federated_login_transactions f USING candidates c WHERE f.id = c.id
`

type DeleteFederatedLoginBatchParams struct {
	RetentionSeconds int32
	BatchSize        int32
}

func (q *Queries) DeleteFederatedLoginBatch(ctx context.Context, arg DeleteFederatedLoginBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFederatedLoginBatch, arg.RetentionSeconds, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWebSessionBatch = `-- name: DeleteWebSessionBatch :execrows
WITH candidates AS (
    SELECT s.id FROM auth_web_sessions s
    WHERE s.terminal_at <= clock_timestamp() - $1::integer * interval '1 second'
      AND NOT EXISTS (SELECT 1 FROM auth_web_session_secrets ss WHERE ss.session_id = s.id)
      AND NOT EXISTS (SELECT 1 FROM auth_user_code_attempt_windows w WHERE w.web_session_id = s.id)
      AND NOT EXISTS (SELECT 1 FROM auth_cli_device_authorizations a WHERE a.review_web_session_id = s.id)
      AND NOT EXISTS (SELECT 1 FROM auth_federated_login_transactions f WHERE f.initiating_web_session_id = s.id)
    ORDER BY s.terminal_at, s.id LIMIT $2::integer
    FOR UPDATE OF s SKIP LOCKED
)
DELETE FROM auth_web_sessions s USING candidates c WHERE s.id = c.id
`

type DeleteWebSessionBatchParams struct {
	RetentionSeconds int32
	BatchSize        int32
}

func (q *Queries) DeleteWebSessionBatch(ctx context.Context, arg DeleteWebSessionBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebSessionBatch, arg.RetentionSeconds, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWebSessionSecretBatch = `-- name: DeleteWebSessionSecretBatch :execrows
WITH candidates AS (
    SELECT ss.session_id, ss.generation
    FROM auth_web_session_secrets ss
    JOIN auth_web_sessions s ON s.id = ss.session_id
    WHERE ss.superseded_at <= clock_timestamp() - $1::integer * interval '1 second'
       OR s.terminal_at <= clock_timestamp() - $1::integer * interval '1 second'
    ORDER BY COALESCE(ss.superseded_at, s.terminal_at), ss.session_id, ss.generation
    LIMIT $2::integer
    FOR UPDATE OF ss SKIP LOCKED
)
DELETE FROM auth_web_session_secrets s USING candidates c
WHERE s.session_id = c.session_id AND s.generation = c.generation
`

type DeleteWebSessionSecretBatchParams struct {
	RetentionSeconds int32
	BatchSize        int32
}

func (q *Queries) DeleteWebSessionSecretBatch(ctx context.Context, arg DeleteWebSessionSecretBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebSessionSecretBatch, arg.RetentionSeconds, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const denyCLIAuthorization = `-- name: DenyCLIAuthorization :exec
UPDATE auth_cli_device_authorizations
SET status = 'denied', approving_user_id = $2, decision_at = clock_timestamp(),
    terminal_at = clock_timestamp()
WHERE id = $1 AND status = 'pending'
`

type DenyCLIAuthorizationParams struct {
	ID              pgtype.UUID
	ApprovingUserID pgtype.UUID
}

func (q *Queries) DenyCLIAuthorization(ctx context.Context, arg DenyCLIAuthorizationParams) error {
	_, err := q.db.Exec(ctx, denyCLIAuthorization, arg.ID, arg.ApprovingUserID)
	return err
}

const expireCLIAuthorization = `-- name: ExpireCLIAuthorization :exec
UPDATE auth_cli_device_authorizations
SET status = 'expired', terminal_at = clock_timestamp()
WHERE id = $1 AND status IN ('pending', 'approved_unclaimed')
`

func (q *Queries) ExpireCLIAuthorization(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, expireCLIAuthorization, id)
	return err
}

const expireCLIAuthorizationBatch = `-- name: ExpireCLIAuthorizationBatch :execrows
WITH candidates AS (
    SELECT id FROM auth_cli_device_authorizations
    WHERE status IN ('pending', 'approved_unclaimed') AND expires_at <= clock_timestamp()
    ORDER BY expires_at, id LIMIT $1::integer
    FOR UPDATE SKIP LOCKED
)
UPDATE auth_cli_device_authorizations a
SET status = 'expired', terminal_at = clock_timestamp()
FROM candidates c WHERE a.id = c.id
`

func (q *Queries) ExpireCLIAuthorizationBatch(ctx context.Context, batchSize int32) (int64, error) {
	result, err := q.db.Exec(ctx, expireCLIAuthorizationBatch, batchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireFederatedLogin = `-- name: ExpireFederatedLogin :exec
UPDATE auth_federated_login_transactions
SET status = 'expired', terminal_at = clock_timestamp(), failure_code = 'login_expired',
    private_state_key_id = NULL, private_state_nonce = NULL, private_state_ciphertext = NULL
WHERE id = $1 AND status IN ('pending', 'completing')
`

func (q *Queries) ExpireFederatedLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, expireFederatedLogin, id)
	return err
}

const expireFederatedLoginBatch = `-- name: ExpireFederatedLoginBatch :execrows
WITH candidates AS (
    SELECT id FROM auth_federated_login_transactions
    WHERE status IN ('pending', 'completing') AND expires_at <= clock_timestamp()
    ORDER BY expires_at, id LIMIT $1::integer
    FOR UPDATE SKIP LOCKED
)
UPDATE auth_federated_login_transactions f
SET status = 'expired', terminal_at = clock_timestamp(), failure_code = 'login_expired',
    private_state_key_id = NULL, private_state_nonce = NULL, private_state_ciphertext = NULL
FROM candidates c WHERE f.id = c.id
`

func (q *Queries) ExpireFederatedLoginBatch(ctx context.Context, batchSize int32) (int64, error) {
	result, err := q.db.Exec(ctx, expireFederatedLoginBatch, batchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireWebSessionBatch = `-- name: ExpireWebSessionBatch :many
WITH candidates AS (
    SELECT id,
           CASE WHEN absolute_expires_at <= clock_timestamp()
                THEN 'absolute_expired' ELSE 'idle_expired' END AS expired_status,
           CASE WHEN absolute_expires_at <= clock_timestamp()
                THEN 'absolute_lifetime' ELSE 'idle_timeout' END AS expired_reason
    FROM auth_web_sessions
    WHERE status = 'active'
      AND (absolute_expires_at <= clock_timestamp()
           OR last_used_at + $1::integer * interval '1 second' <= clock_timestamp())
    ORDER BY LEAST(
        absolute_expires_at,
        last_used_at + $1::integer * interval '1 second'
    ), id
    LIMIT $2::integer
    FOR UPDATE SKIP LOCKED
)
UPDATE auth_web_sessions s
SET status = c.expired_status, terminal_at = clock_timestamp(), terminal_reason = c.expired_reason
FROM candidates c WHERE s.id = c.id
RETURNING s.id, s.status, s.terminal_reason
`

type ExpireWebSessionBatchParams struct {
	IdleDeadlineSeconds int32
	BatchSize           int32
}

type ExpireWebSessionBatchRow struct {
	ID             pgtype.UUID
	Status         string
	TerminalReason string
}

func (q *Queries) ExpireWebSessionBatch(ctx context.Context, arg ExpireWebSessionBatchParams) ([]ExpireWebSessionBatchRow, error) {
	rows, err := q.db.Query(ctx, expireWebSessionBatch, arg.IdleDeadlineSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpireWebSessionBatchRow{}
	for rows.Next() {
		var i ExpireWebSessionBatchRow
		if err := rows.Scan(&i.ID, &i.Status, &i.TerminalReason); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishFederatedLogin = `-- name: FinishFederatedLogin :exec
UPDATE auth_federated_login_transactions
SET status = $1, terminal_at = clock_timestamp(), failure_code = $2,
    private_state_key_id = NULL, private_state_nonce = NULL, private_state_ciphertext = NULL
WHERE id = $3 AND status = 'completing'
`

type FinishFederatedLoginParams struct {
	Status      string
	FailureCode string
	ID          pgtype.UUID
}

func (q *Queries) FinishFederatedLogin(ctx context.Context, arg FinishFederatedLoginParams) error {
	_, err := q.db.Exec(ctx, finishFederatedLogin, arg.Status, arg.FailureCode, arg.ID)
	return err
}

const getAuthenticationCutoverStatus = `-- name: GetAuthenticationCutoverStatus :one
SELECT status
FROM auth_cutover_ledger
WHERE protocol_version = 'auth-v1'
`

func (q *Queries) GetAuthenticationCutoverStatus(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getAuthenticationCutoverStatus)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getCLIAuthenticationForUpdate = `-- name: GetCLIAuthenticationForUpdate :one
SELECT c.id, c.user_id, c.status AS credential_status, c.capability_version,
       c.created_at, c.last_used_at, u.status AS user_status,
       u.display_name, u.avatar_url, u.created_at AS user_created_at
FROM auth_cli_credentials c
JOIN auth_users u ON u.id = c.user_id
WHERE c.secret_digest = $1
FOR UPDATE OF c
FOR SHARE OF u
`

type GetCLIAuthenticationForUpdateRow struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	CredentialStatus  string
	CapabilityVersion string
	CreatedAt         time.Time
	LastUsedAt        time.Time
	UserStatus        string
	DisplayName       string
	AvatarUrl         string
	UserCreatedAt     time.Time
}

func (q *Queries) GetCLIAuthenticationForUpdate(ctx context.Context, secretDigest []byte) (GetCLIAuthenticationForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getCLIAuthenticationForUpdate, secretDigest)
	var i GetCLIAuthenticationForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialStatus,
		&i.CapabilityVersion,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.UserStatus,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.UserCreatedAt,
	)
	return i, err
}

const getCLIAuthorizationByDeviceCodeForUpdate = `-- name: GetCLIAuthorizationByDeviceCodeForUpdate :one
SELECT id, status, poll_interval_seconds, next_poll_at, created_at, expires_at,
       approving_user_id, issued_credential_id
FROM auth_cli_device_authorizations
WHERE device_code_digest = $1
FOR UPDATE
`

type GetCLIAuthorizationByDeviceCodeForUpdateRow struct {
	ID                  pgtype.UUID
	Status              string
	PollIntervalSeconds int32
	NextPollAt          time.Time
	CreatedAt           time.Time
	ExpiresAt           time.Time
	ApprovingUserID     pgtype.UUID
	IssuedCredentialID  pgtype.UUID
}

func (q *Queries) GetCLIAuthorizationByDeviceCodeForUpdate(ctx context.Context, deviceCodeDigest []byte) (GetCLIAuthorizationByDeviceCodeForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getCLIAuthorizationByDeviceCodeForUpdate, deviceCodeDigest)
	var i GetCLIAuthorizationByDeviceCodeForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.PollIntervalSeconds,
		&i.NextPollAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ApprovingUserID,
		&i.IssuedCredentialID,
	)
	return i, err
}

const getCLIAuthorizationByUserCodeForUpdate = `-- name: GetCLIAuthorizationByUserCodeForUpdate :one
SELECT id, status, user_code_key_id, expires_at, review_web_session_id,
       approving_user_id, decision_at
FROM auth_cli_device_authorizations
WHERE user_code_key_id = $1 AND user_code_digest = $2
FOR UPDATE
`

type GetCLIAuthorizationByUserCodeForUpdateParams struct {
	UserCodeKeyID  string
	UserCodeDigest []byte
}

type GetCLIAuthorizationByUserCodeForUpdateRow struct {
	ID                 pgtype.UUID
	Status             string
	UserCodeKeyID      string
	ExpiresAt          time.Time
	ReviewWebSessionID pgtype.UUID
	ApprovingUserID    pgtype.UUID
	DecisionAt         pgtype.Timestamptz
}

func (q *Queries) GetCLIAuthorizationByUserCodeForUpdate(ctx context.Context, arg GetCLIAuthorizationByUserCodeForUpdateParams) (GetCLIAuthorizationByUserCodeForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getCLIAuthorizationByUserCodeForUpdate, arg.UserCodeKeyID, arg.UserCodeDigest)
	var i GetCLIAuthorizationByUserCodeForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.UserCodeKeyID,
		&i.ExpiresAt,
		&i.ReviewWebSessionID,
		&i.ApprovingUserID,
		&i.DecisionAt,
	)
	return i, err
}

const getCLIAuthorizationForDecision = `-- name: GetCLIAuthorizationForDecision :one
SELECT id, status, expires_at, review_web_session_id, approving_user_id
FROM auth_cli_device_authorizations
WHERE id = $1
FOR UPDATE
`

type GetCLIAuthorizationForDecisionRow struct {
	ID                 pgtype.UUID
	Status             string
	ExpiresAt          time.Time
	ReviewWebSessionID pgtype.UUID
	ApprovingUserID    pgtype.UUID
}

func (q *Queries) GetCLIAuthorizationForDecision(ctx context.Context, id pgtype.UUID) (GetCLIAuthorizationForDecisionRow, error) {
	row := q.db.QueryRow(ctx, getCLIAuthorizationForDecision, id)
	var i GetCLIAuthorizationForDecisionRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ExpiresAt,
		&i.ReviewWebSessionID,
		&i.ApprovingUserID,
	)
	return i, err
}

const getCLICredentialBySecretForRevoke = `-- name: GetCLICredentialBySecretForRevoke :one
SELECT id, user_id, status
FROM auth_cli_credentials
WHERE secret_digest = $1
FOR UPDATE
`

type GetCLICredentialBySecretForRevokeRow struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
	Status string
}

func (q *Queries) GetCLICredentialBySecretForRevoke(ctx context.Context, secretDigest []byte) (GetCLICredentialBySecretForRevokeRow, error) {
	row := q.db.QueryRow(ctx, getCLICredentialBySecretForRevoke, secretDigest)
	var i GetCLICredentialBySecretForRevokeRow
	err := row.Scan(&i.ID, &i.UserID, &i.Status)
	return i, err
}

const getCLICredentialForPrincipal = `-- name: GetCLICredentialForPrincipal :one
SELECT id, user_id, status
FROM auth_cli_credentials
WHERE id = $1
FOR UPDATE
`

type GetCLICredentialForPrincipalRow struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
	Status string
}

func (q *Queries) GetCLICredentialForPrincipal(ctx context.Context, id pgtype.UUID) (GetCLICredentialForPrincipalRow, error) {
	row := q.db.QueryRow(ctx, getCLICredentialForPrincipal, id)
	var i GetCLICredentialForPrincipalRow
	err := row.Scan(&i.ID, &i.UserID, &i.Status)
	return i, err
}

const getCodeAttemptWindowForUpdate = `-- name: GetCodeAttemptWindowForUpdate :one
SELECT failure_count, blocked_until
FROM auth_user_code_attempt_windows
WHERE web_session_id = $1 AND window_start = $2
FOR UPDATE
`

type GetCodeAttemptWindowForUpdateParams struct {
	WebSessionID pgtype.UUID
	WindowStart  time.Time
}

type GetCodeAttemptWindowForUpdateRow struct {
	FailureCount int32
	BlockedUntil pgtype.Timestamptz
}

func (q *Queries) GetCodeAttemptWindowForUpdate(ctx context.Context, arg GetCodeAttemptWindowForUpdateParams) (GetCodeAttemptWindowForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getCodeAttemptWindowForUpdate, arg.WebSessionID, arg.WindowStart)
	var i GetCodeAttemptWindowForUpdateRow
	err := row.Scan(&i.FailureCount, &i.BlockedUntil)
	return i, err
}

const getCurrentWebSecretGenerationForUpdate = `-- name: GetCurrentWebSecretGenerationForUpdate :one
SELECT generation
FROM auth_web_session_secrets
WHERE session_id = $1 AND superseded_at IS NULL
FOR UPDATE
`

func (q *Queries) GetCurrentWebSecretGenerationForUpdate(ctx context.Context, sessionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getCurrentWebSecretGenerationForUpdate, sessionID)
	var generation int64
	err := row.Scan(&generation)
	return generation, err
}

const getExternalIdentityForUpdate = `-- name: GetExternalIdentityForUpdate :one
SELECT id, user_id, status, display_name, avatar_url, created_at, last_verified_at
FROM auth_external_identities
WHERE issuer = $1 AND subject = $2
FOR UPDATE
`

type GetExternalIdentityForUpdateParams struct {
	Issuer  string
	Subject string
}

type GetExternalIdentityForUpdateRow struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	Status         string
	DisplayName    string
	AvatarUrl      string
	CreatedAt      time.Time
	LastVerifiedAt time.Time
}

func (q *Queries) GetExternalIdentityForUpdate(ctx context.Context, arg GetExternalIdentityForUpdateParams) (GetExternalIdentityForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getExternalIdentityForUpdate, arg.Issuer, arg.Subject)
	var i GetExternalIdentityForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.LastVerifiedAt,
	)
	return i, err
}

const getFederatedLoginByStateForUpdate = `-- name: GetFederatedLoginByStateForUpdate :one
SELECT id, intent, provider_registration_id, provider_registration_revision,
       expected_issuer, callback_uri, return_to, private_state_key_id,
       private_state_nonce, private_state_ciphertext, private_state_schema,
       browser_binding_digest, initiating_user_id, initiating_web_session_id,
       status, created_at, expires_at
FROM auth_federated_login_transactions
WHERE state_digest = $1
FOR UPDATE
`

type GetFederatedLoginByStateForUpdateRow struct {
	ID                           pgtype.UUID
	Intent                       string
	ProviderRegistrationID       string
	ProviderRegistrationRevision string
	ExpectedIssuer               string
	CallbackUri                  string
	ReturnTo                     string
	PrivateStateKeyID            *string
	PrivateStateNonce            []byte
	PrivateStateCiphertext       []byte
	PrivateStateSchema           string
	BrowserBindingDigest         []byte
	InitiatingUserID             pgtype.UUID
	InitiatingWebSessionID       pgtype.UUID
	Status                       string
	CreatedAt                    time.Time
	ExpiresAt                    time.Time
}

func (q *Queries) GetFederatedLoginByStateForUpdate(ctx context.Context, stateDigest []byte) (GetFederatedLoginByStateForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getFederatedLoginByStateForUpdate, stateDigest)
	var i GetFederatedLoginByStateForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Intent,
		&i.ProviderRegistrationID,
		&i.ProviderRegistrationRevision,
		&i.ExpectedIssuer,
		&i.CallbackUri,
		&i.ReturnTo,
		&i.PrivateStateKeyID,
		&i.PrivateStateNonce,
		&i.PrivateStateCiphertext,
		&i.PrivateStateSchema,
		&i.BrowserBindingDigest,
		&i.InitiatingUserID,
		&i.InitiatingWebSessionID,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserForUpdate = `-- name: GetUserForUpdate :one
SELECT id, status, display_name, avatar_url, created_at, updated_at, disabled_at
FROM auth_users
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetUserForUpdate(ctx context.Context, id pgtype.UUID) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserForUpdate, id)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const getWebAuthenticationForUpdate = `-- name: GetWebAuthenticationForUpdate :one
SELECT s.id, s.user_id, s.status AS session_status, s.created_at,
       s.last_used_at, s.reauthenticated_at, s.absolute_expires_at,
       u.status AS user_status, u.display_name, u.avatar_url, u.created_at AS user_created_at,
       ss.generation, ss.csrf_digest
FROM auth_web_session_secrets ss
JOIN auth_web_sessions s ON s.id = ss.session_id
JOIN auth_users u ON u.id = s.user_id
WHERE ss.secret_digest = $1 AND ss.superseded_at IS NULL
FOR UPDATE OF s, ss
FOR SHARE OF u
`

type GetWebAuthenticationForUpdateRow struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	SessionStatus     string
	CreatedAt         time.Time
	LastUsedAt        time.Time
	ReauthenticatedAt time.Time
	AbsoluteExpiresAt time.Time
	UserStatus        string
	DisplayName       string
	AvatarUrl         string
	UserCreatedAt     time.Time
	Generation        int64
	CsrfDigest        []byte
}

func (q *Queries) GetWebAuthenticationForUpdate(ctx context.Context, secretDigest []byte) (GetWebAuthenticationForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getWebAuthenticationForUpdate, secretDigest)
	var i GetWebAuthenticationForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionStatus,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ReauthenticatedAt,
		&i.AbsoluteExpiresAt,
		&i.UserStatus,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.UserCreatedAt,
		&i.Generation,
		&i.CsrfDigest,
	)
	return i, err
}

const getWebSessionForUpdate = `-- name: GetWebSessionForUpdate :one
SELECT s.id, s.user_id, s.status AS session_status, s.created_at,
       s.last_used_at, s.reauthenticated_at, s.absolute_expires_at,
       u.status AS user_status, u.display_name, u.avatar_url, u.created_at AS user_created_at
FROM auth_web_sessions s
JOIN auth_users u ON u.id = s.user_id
WHERE s.id = $1
FOR UPDATE OF s
FOR SHARE OF u
`

type GetWebSessionForUpdateRow struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	SessionStatus     string
	CreatedAt         time.Time
	LastUsedAt        time.Time
	ReauthenticatedAt time.Time
	AbsoluteExpiresAt time.Time
	UserStatus        string
	DisplayName       string
	AvatarUrl         string
	UserCreatedAt     time.Time
}

func (q *Queries) GetWebSessionForUpdate(ctx context.Context, id pgtype.UUID) (GetWebSessionForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getWebSessionForUpdate, id)
	var i GetWebSessionForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionStatus,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ReauthenticatedAt,
		&i.AbsoluteExpiresAt,
		&i.UserStatus,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.UserCreatedAt,
	)
	return i, err
}

const insertCLICredential = `-- name: InsertCLICredential :one
INSERT INTO auth_cli_credentials (
    id, user_id, authorization_id, secret_digest, digest_version,
    capability_version, status
) VALUES ($1, $2, $3, $4, 'sha256-v1', $5, 'active')
RETURNING created_at, last_used_at
`

type InsertCLICredentialParams struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	AuthorizationID   pgtype.UUID
	SecretDigest      []byte
	CapabilityVersion string
}

type InsertCLICredentialRow struct {
	CreatedAt  time.Time
	LastUsedAt time.Time
}

func (q *Queries) InsertCLICredential(ctx context.Context, arg InsertCLICredentialParams) (InsertCLICredentialRow, error) {
	row := q.db.QueryRow(ctx, insertCLICredential,
		arg.ID,
		arg.UserID,
		arg.AuthorizationID,
		arg.SecretDigest,
		arg.CapabilityVersion,
	)
	var i InsertCLICredentialRow
	err := row.Scan(&i.CreatedAt, &i.LastUsedAt)
	return i, err
}

const insertCLIDeviceAuthorization = `-- name: InsertCLIDeviceAuthorization :one
INSERT INTO auth_cli_device_authorizations (
    id, device_code_digest, user_code_key_id, user_code_digest, digest_version,
    status, poll_interval_seconds, next_poll_at, expires_at
) VALUES (
    $1, $2, $3, $4, 'sha256-v1', 'pending', $5,
    clock_timestamp() + $6::integer * interval '1 second',
    clock_timestamp() + $7::integer * interval '1 second'
)
RETURNING created_at, expires_at
`

type InsertCLIDeviceAuthorizationParams struct {
	ID                  pgtype.UUID
	DeviceCodeDigest    []byte
	UserCodeKeyID       string
	UserCodeDigest      []byte
	PollIntervalSeconds int32
	InitialPollSeconds  int32
	TtlSeconds          int32
}

type InsertCLIDeviceAuthorizationRow struct {
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) InsertCLIDeviceAuthorization(ctx context.Context, arg InsertCLIDeviceAuthorizationParams) (InsertCLIDeviceAuthorizationRow, error) {
	row := q.db.QueryRow(ctx, insertCLIDeviceAuthorization,
		arg.ID,
		arg.DeviceCodeDigest,
		arg.UserCodeKeyID,
		arg.UserCodeDigest,
		arg.PollIntervalSeconds,
		arg.InitialPollSeconds,
		arg.TtlSeconds,
	)
	var i InsertCLIDeviceAuthorizationRow
	err := row.Scan(&i.CreatedAt, &i.ExpiresAt)
	return i, err
}

const insertExternalIdentity = `-- name: InsertExternalIdentity :exec
INSERT INTO auth_external_identities (
    id, user_id, issuer, subject, status, display_name, avatar_url
) VALUES ($1, $2, $3, $4, 'active', $5, $6)
`

type InsertExternalIdentityParams struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Issuer      string
	Subject     string
	DisplayName string
	AvatarUrl   string
}

func (q *Queries) InsertExternalIdentity(ctx context.Context, arg InsertExternalIdentityParams) error {
	_, err := q.db.Exec(ctx, insertExternalIdentity,
		arg.ID,
		arg.UserID,
		arg.Issuer,
		arg.Subject,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	return err
}

const insertFederatedLogin = `-- name: InsertFederatedLogin :exec
INSERT INTO auth_federated_login_transactions (
    id, intent, state_digest, browser_binding_digest, digest_version,
    provider_registration_id, provider_registration_revision, expected_issuer,
    callback_uri, return_to, private_state_key_id, private_state_nonce,
    private_state_ciphertext, private_state_schema, initiating_user_id,
    initiating_web_session_id, status, expires_at
) VALUES (
    $1, $2, $3, $4, 'sha256-v1',
    $5, $6, $7, $8, $9, $10, $11, $12, $13,
    $14, $15, 'pending', $16::timestamptz
)
`

type InsertFederatedLoginParams struct {
	ID                           pgtype.UUID
	Intent                       string
	StateDigest                  []byte
	BrowserBindingDigest         []byte
	ProviderRegistrationID       string
	ProviderRegistrationRevision string
	ExpectedIssuer               string
	CallbackUri                  string
	ReturnTo                     string
	PrivateStateKeyID            *string
	PrivateStateNonce            []byte
	PrivateStateCiphertext       []byte
	PrivateStateSchema           string
	InitiatingUserID             pgtype.UUID
	InitiatingWebSessionID       pgtype.UUID
	ExpiresAt                    time.Time
}

func (q *Queries) InsertFederatedLogin(ctx context.Context, arg InsertFederatedLoginParams) error {
	_, err := q.db.Exec(ctx, insertFederatedLogin,
		arg.ID,
		arg.Intent,
		arg.StateDigest,
		arg.BrowserBindingDigest,
		arg.ProviderRegistrationID,
		arg.ProviderRegistrationRevision,
		arg.ExpectedIssuer,
		arg.CallbackUri,
		arg.ReturnTo,
		arg.PrivateStateKeyID,
		arg.PrivateStateNonce,
		arg.PrivateStateCiphertext,
		arg.PrivateStateSchema,
		arg.InitiatingUserID,
		arg.InitiatingWebSessionID,
		arg.ExpiresAt,
	)
	return err
}

const insertSecurityAuditEvent = `-- name: InsertSecurityAuditEvent :exec
INSERT INTO security_audit_events (
    id, initiator_kind, initiator_id, action, target_kind, target_id,
    outcome, reason, request_id, provider_registration_id,
    web_session_id, cli_credential_id, metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type InsertSecurityAuditEventParams struct {
	ID                     pgtype.UUID
	InitiatorKind          string
	InitiatorID            string
	Action                 string
	TargetKind             string
	TargetID               string
	Outcome                string
	Reason                 string
	RequestID              string
	ProviderRegistrationID string
	WebSessionID           pgtype.UUID
	CliCredentialID        pgtype.UUID
	Metadata               []byte
}

func (q *Queries) InsertSecurityAuditEvent(ctx context.Context, arg InsertSecurityAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertSecurityAuditEvent,
		arg.ID,
		arg.InitiatorKind,
		arg.InitiatorID,
		arg.Action,
		arg.TargetKind,
		arg.TargetID,
		arg.Outcome,
		arg.Reason,
		arg.RequestID,
		arg.ProviderRegistrationID,
		arg.WebSessionID,
		arg.CliCredentialID,
		arg.Metadata,
	)
	return err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO auth_users (id, status, display_name, avatar_url)
VALUES ($1, 'active', $2, $3)
RETURNING created_at
`

type InsertUserParams struct {
	ID          pgtype.UUID
	DisplayName string
	AvatarUrl   string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.ID, arg.DisplayName, arg.AvatarUrl)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const insertWebSession = `-- name: InsertWebSession :one
INSERT INTO auth_web_sessions (
    id, user_id, status, absolute_expires_at
) VALUES ($1, $2, 'active', clock_timestamp() + $3::integer * interval '1 second')
RETURNING created_at, last_used_at, reauthenticated_at, absolute_expires_at
`

type InsertWebSessionParams struct {
	ID                 pgtype.UUID
	UserID             pgtype.UUID
	AbsoluteTtlSeconds int32
}

type InsertWebSessionRow struct {
	CreatedAt         time.Time
	LastUsedAt        time.Time
	ReauthenticatedAt time.Time
	AbsoluteExpiresAt time.Time
}

func (q *Queries) InsertWebSession(ctx context.Context, arg InsertWebSessionParams) (InsertWebSessionRow, error) {
	row := q.db.QueryRow(ctx, insertWebSession, arg.ID, arg.UserID, arg.AbsoluteTtlSeconds)
	var i InsertWebSessionRow
	err := row.Scan(
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ReauthenticatedAt,
		&i.AbsoluteExpiresAt,
	)
	return i, err
}

const insertWebSessionSecret = `-- name: InsertWebSessionSecret :one
INSERT INTO auth_web_session_secrets (
    session_id, generation, secret_digest, csrf_digest, digest_version
) VALUES ($1, $2, $3, $4, 'sha256-v1')
RETURNING issued_at
`

type InsertWebSessionSecretParams struct {
	SessionID    pgtype.UUID
	Generation   int64
	SecretDigest []byte
	CsrfDigest   []byte
}

func (q *Queries) InsertWebSessionSecret(ctx context.Context, arg InsertWebSessionSecretParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, insertWebSessionSecret,
		arg.SessionID,
		arg.Generation,
		arg.SecretDigest,
		arg.CsrfDigest,
	)
	var issued_at time.Time
	err := row.Scan(&issued_at)
	return issued_at, err
}

const listActiveCLICredentialsForUser = `-- name: ListActiveCLICredentialsForUser :many
SELECT id, capability_version, created_at, last_used_at
FROM auth_cli_credentials
WHERE user_id = $1 AND status = 'active'
ORDER BY last_used_at DESC, created_at DESC, id DESC
`

type ListActiveCLICredentialsForUserRow struct {
	ID                pgtype.UUID
	CapabilityVersion string
	CreatedAt         time.Time
	LastUsedAt        time.Time
}

func (q *Queries) ListActiveCLICredentialsForUser(ctx context.Context, userID pgtype.UUID) ([]ListActiveCLICredentialsForUserRow, error) {
	rows, err := q.db.Query(ctx, listActiveCLICredentialsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveCLICredentialsForUserRow{}
	for rows.Next() {
		var i ListActiveCLICredentialsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CapabilityVersion,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveWebSessionsForUser = `-- name: ListActiveWebSessionsForUser :many
SELECT id, created_at, last_used_at, reauthenticated_at, absolute_expires_at
FROM auth_web_sessions
WHERE user_id = $1
  AND status = 'active'
  AND absolute_expires_at > clock_timestamp()
  AND last_used_at + $2::integer * interval '1 second' > clock_timestamp()
ORDER BY last_used_at DESC, created_at DESC, id DESC
`

type ListActiveWebSessionsForUserParams struct {
	UserID              pgtype.UUID
	IdleDeadlineSeconds int32
}

type ListActiveWebSessionsForUserRow struct {
	ID                pgtype.UUID
	CreatedAt         time.Time
	LastUsedAt        time.Time
	ReauthenticatedAt time.Time
	AbsoluteExpiresAt time.Time
}

func (q *Queries) ListActiveWebSessionsForUser(ctx context.Context, arg ListActiveWebSessionsForUserParams) ([]ListActiveWebSessionsForUserRow, error) {
	rows, err := q.db.Query(ctx, listActiveWebSessionsForUser, arg.UserID, arg.IdleDeadlineSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveWebSessionsForUserRow{}
	for rows.Next() {
		var i ListActiveWebSessionsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ReauthenticatedAt,
			&i.AbsoluteExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLivePrivateStateKeyIDs = `-- name: ListLivePrivateStateKeyIDs :many
SELECT DISTINCT private_state_key_id
FROM auth_federated_login_transactions
WHERE status IN ('pending', 'completing')
  AND expires_at > clock_timestamp()
  AND private_state_key_id IS NOT NULL
`

func (q *Queries) ListLivePrivateStateKeyIDs(ctx context.Context) ([]*string, error) {
	rows, err := q.db.Query(ctx, listLivePrivateStateKeyIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*string{}
	for rows.Next() {
		var private_state_key_id *string
		if err := rows.Scan(&private_state_key_id); err != nil {
			return nil, err
		}
		items = append(items, private_state_key_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveProviderRegistrations = `-- name: ListLiveProviderRegistrations :many
SELECT DISTINCT provider_registration_id, provider_registration_revision,
       expected_issuer, callback_uri
FROM auth_federated_login_transactions
WHERE status IN ('pending', 'completing')
  AND expires_at > clock_timestamp()
`

type ListLiveProviderRegistrationsRow struct {
	ProviderRegistrationID       string
	ProviderRegistrationRevision string
	ExpectedIssuer               string
	CallbackUri                  string
}

func (q *Queries) ListLiveProviderRegistrations(ctx context.Context) ([]ListLiveProviderRegistrationsRow, error) {
	rows, err := q.db.Query(ctx, listLiveProviderRegistrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLiveProviderRegistrationsRow{}
	for rows.Next() {
		var i ListLiveProviderRegistrationsRow
		if err := rows.Scan(
			&i.ProviderRegistrationID,
			&i.ProviderRegistrationRevision,
			&i.ExpectedIssuer,
			&i.CallbackUri,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveUserCodeKeyIDs = `-- name: ListLiveUserCodeKeyIDs :many
SELECT DISTINCT user_code_key_id
FROM auth_cli_device_authorizations
WHERE status IN ('pending', 'approved_unclaimed')
  AND expires_at > clock_timestamp()
`

func (q *Queries) ListLiveUserCodeKeyIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listLiveUserCodeKeyIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var user_code_key_id string
		if err := rows.Scan(&user_code_key_id); err != nil {
			return nil, err
		}
		items = append(items, user_code_key_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveCLICodeExists = `-- name: LiveCLICodeExists :one
SELECT EXISTS (
    SELECT 1 FROM auth_cli_device_authorizations
    WHERE user_code_key_id = $1 AND user_code_digest = $2
      AND status IN ('pending', 'approved_unclaimed')
) AS found
`

type LiveCLICodeExistsParams struct {
	UserCodeKeyID  string
	UserCodeDigest []byte
}

func (q *Queries) LiveCLICodeExists(ctx context.Context, arg LiveCLICodeExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, liveCLICodeExists, arg.UserCodeKeyID, arg.UserCodeDigest)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const reauthenticateWebSession = `-- name: ReauthenticateWebSession :one
UPDATE auth_web_sessions
SET reauthenticated_at = clock_timestamp(),
    last_used_at = clock_timestamp(),
    absolute_expires_at = clock_timestamp() + $2::integer * interval '1 second'
WHERE id = $1 AND status = 'active'
RETURNING created_at, last_used_at, reauthenticated_at, absolute_expires_at
`

type ReauthenticateWebSessionParams struct {
	ID                 pgtype.UUID
	AbsoluteTtlSeconds int32
}

type ReauthenticateWebSessionRow struct {
	CreatedAt         time.Time
	LastUsedAt        time.Time
	ReauthenticatedAt time.Time
	AbsoluteExpiresAt time.Time
}

func (q *Queries) ReauthenticateWebSession(ctx context.Context, arg ReauthenticateWebSessionParams) (ReauthenticateWebSessionRow, error) {
	row := q.db.QueryRow(ctx, reauthenticateWebSession, arg.ID, arg.AbsoluteTtlSeconds)
	var i ReauthenticateWebSessionRow
	err := row.Scan(
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ReauthenticatedAt,
		&i.AbsoluteExpiresAt,
	)
	return i, err
}

const reconcileCLICredentialClaim = `-- name: ReconcileCLICredentialClaim :one
SELECT c.id, c.secret_digest, c.capability_version, c.created_at,
       u.id AS user_id, u.display_name, u.avatar_url, u.created_at AS user_created_at
FROM auth_cli_device_authorizations a
JOIN auth_cli_credentials c ON c.id = a.issued_credential_id
JOIN auth_users u ON u.id = c.user_id
WHERE a.id = $1 AND a.status = 'claimed' AND c.id = $2
`

type ReconcileCLICredentialClaimParams struct {
	ID   pgtype.UUID
	ID_2 pgtype.UUID
}

type ReconcileCLICredentialClaimRow struct {
	ID                pgtype.UUID
	SecretDigest      []byte
	CapabilityVersion string
	CreatedAt         time.Time
	UserID            pgtype.UUID
	DisplayName       string
	AvatarUrl         string
	UserCreatedAt     time.Time
}

func (q *Queries) ReconcileCLICredentialClaim(ctx context.Context, arg ReconcileCLICredentialClaimParams) (ReconcileCLICredentialClaimRow, error) {
	row := q.db.QueryRow(ctx, reconcileCLICredentialClaim, arg.ID, arg.ID_2)
	var i ReconcileCLICredentialClaimRow
	err := row.Scan(
		&i.ID,
		&i.SecretDigest,
		&i.CapabilityVersion,
		&i.CreatedAt,
		&i.UserID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.UserCreatedAt,
	)
	return i, err
}

const refreshExternalIdentity = `-- name: RefreshExternalIdentity :exec
UPDATE auth_external_identities
SET status = 'active', display_name = $2, avatar_url = $3,
    last_verified_at = clock_timestamp(), unlinked_at = NULL
WHERE id = $1
`

type RefreshExternalIdentityParams struct {
	ID          pgtype.UUID
	DisplayName string
	AvatarUrl   string
}

func (q *Queries) RefreshExternalIdentity(ctx context.Context, arg RefreshExternalIdentityParams) error {
	_, err := q.db.Exec(ctx, refreshExternalIdentity, arg.ID, arg.DisplayName, arg.AvatarUrl)
	return err
}

const revokeAllCLICredentialsForUser = `-- name: RevokeAllCLICredentialsForUser :execrows
UPDATE auth_cli_credentials
SET status = 'revoked', revoked_at = clock_timestamp(), revoke_reason = $2
WHERE user_id = $1 AND status = 'active'
`

type RevokeAllCLICredentialsForUserParams struct {
	UserID       pgtype.UUID
	RevokeReason string
}

func (q *Queries) RevokeAllCLICredentialsForUser(ctx context.Context, arg RevokeAllCLICredentialsForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllCLICredentialsForUser, arg.UserID, arg.RevokeReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAllWebSessionsForUser = `-- name: RevokeAllWebSessionsForUser :execrows
UPDATE auth_web_sessions
SET status = 'revoked', terminal_at = clock_timestamp(), terminal_reason = $2
WHERE user_id = $1 AND status = 'active'
`

type RevokeAllWebSessionsForUserParams struct {
	UserID         pgtype.UUID
	TerminalReason string
}

func (q *Queries) RevokeAllWebSessionsForUser(ctx context.Context, arg RevokeAllWebSessionsForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllWebSessionsForUser, arg.UserID, arg.TerminalReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeCLICredentialForUser = `-- name: RevokeCLICredentialForUser :execrows
UPDATE auth_cli_credentials
SET status = 'revoked', revoked_at = clock_timestamp(), revoke_reason = $3
WHERE id = $1 AND user_id = $2 AND status = 'active'
`

type RevokeCLICredentialForUserParams struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	RevokeReason string
}

func (q *Queries) RevokeCLICredentialForUser(ctx context.Context, arg RevokeCLICredentialForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeCLICredentialForUser, arg.ID, arg.UserID, arg.RevokeReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeWebSessionForUser = `-- name: RevokeWebSessionForUser :execrows
UPDATE auth_web_sessions
SET status = 'revoked', terminal_at = clock_timestamp(), terminal_reason = $3
WHERE id = $1 AND user_id = $2 AND status = 'active'
`

type RevokeWebSessionForUserParams struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	TerminalReason string
}

func (q *Queries) RevokeWebSessionForUser(ctx context.Context, arg RevokeWebSessionForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeWebSessionForUser, arg.ID, arg.UserID, arg.TerminalReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const supersedeWebSessionSecret = `-- name: SupersedeWebSessionSecret :exec
UPDATE auth_web_session_secrets
SET superseded_at = clock_timestamp()
WHERE session_id = $1 AND superseded_at IS NULL
`

func (q *Queries) SupersedeWebSessionSecret(ctx context.Context, sessionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, supersedeWebSessionSecret, sessionID)
	return err
}

const terminalWebSession = `-- name: TerminalWebSession :exec
UPDATE auth_web_sessions
SET status = $2, terminal_at = clock_timestamp(), terminal_reason = $3
WHERE id = $1 AND status = 'active'
`

type TerminalWebSessionParams struct {
	ID             pgtype.UUID
	Status         string
	TerminalReason string
}

func (q *Queries) TerminalWebSession(ctx context.Context, arg TerminalWebSessionParams) error {
	_, err := q.db.Exec(ctx, terminalWebSession, arg.ID, arg.Status, arg.TerminalReason)
	return err
}

const touchCLICredential = `-- name: TouchCLICredential :one
UPDATE auth_cli_credentials
SET last_used_at = clock_timestamp()
WHERE id = $1 AND status = 'active'
  AND last_used_at <= clock_timestamp() - $2::integer * interval '1 second'
RETURNING last_used_at
`

type TouchCLICredentialParams struct {
	ID                   pgtype.UUID
	WriteIntervalSeconds int32
}

func (q *Queries) TouchCLICredential(ctx context.Context, arg TouchCLICredentialParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, touchCLICredential, arg.ID, arg.WriteIntervalSeconds)
	var last_used_at time.Time
	err := row.Scan(&last_used_at)
	return last_used_at, err
}

const touchWebSession = `-- name: TouchWebSession :one
UPDATE auth_web_sessions
SET last_used_at = clock_timestamp()
WHERE id = $1
  AND status = 'active'
  AND last_used_at <= clock_timestamp() - $2::integer * interval '1 second'
RETURNING last_used_at
`

type TouchWebSessionParams struct {
	ID                   pgtype.UUID
	WriteIntervalSeconds int32
}

func (q *Queries) TouchWebSession(ctx context.Context, arg TouchWebSessionParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, touchWebSession, arg.ID, arg.WriteIntervalSeconds)
	var last_used_at time.Time
	err := row.Scan(&last_used_at)
	return last_used_at, err
}

const tryMaintenanceLock = `-- name: TryMaintenanceLock :one
SELECT pg_try_advisory_xact_lock($1::bigint) AS acquired
`

func (q *Queries) TryMaintenanceLock(ctx context.Context, lockID int64) (bool, error) {
	row := q.db.QueryRow(ctx, tryMaintenanceLock, lockID)
	var acquired bool
	err := row.Scan(&acquired)
	return acquired, err
}

const upsertCodeAttemptFailure = `-- name: UpsertCodeAttemptFailure :one
INSERT INTO auth_user_code_attempt_windows (
    web_session_id, window_start, failure_count, blocked_until
) VALUES (
    $1, $2, 1,
    CASE WHEN $3::integer <= 1
         THEN $4::timestamptz ELSE NULL END
)
ON CONFLICT (web_session_id, window_start) DO UPDATE
SET failure_count = auth_user_code_attempt_windows.failure_count + 1,
    blocked_until = CASE
        WHEN auth_user_code_attempt_windows.failure_count + 1 >= $3::integer
        THEN $4::timestamptz
        ELSE auth_user_code_attempt_windows.blocked_until
    END,
    updated_at = clock_timestamp()
RETURNING failure_count, blocked_until
`

type UpsertCodeAttemptFailureParams struct {
	WebSessionID    pgtype.UUID
	WindowStart     time.Time
	MaximumFailures int32
	WindowEnd       time.Time
}

type UpsertCodeAttemptFailureRow struct {
	FailureCount int32
	BlockedUntil pgtype.Timestamptz
}

func (q *Queries) UpsertCodeAttemptFailure(ctx context.Context, arg UpsertCodeAttemptFailureParams) (UpsertCodeAttemptFailureRow, error) {
	row := q.db.QueryRow(ctx, upsertCodeAttemptFailure,
		arg.WebSessionID,
		arg.WindowStart,
		arg.MaximumFailures,
		arg.WindowEnd,
	)
	var i UpsertCodeAttemptFailureRow
	err := row.Scan(&i.FailureCount, &i.BlockedUntil)
	return i, err
}
