// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuthCliCredential struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	AuthorizationID   pgtype.UUID
	SecretDigest      []byte
	DigestVersion     string
	CapabilityVersion string
	Status            string
	CreatedAt         time.Time
	LastUsedAt        time.Time
	RevokedAt         pgtype.Timestamptz
	RevokeReason      string
}

type AuthCliDeviceAuthorization struct {
	ID                  pgtype.UUID
	DeviceCodeDigest    []byte
	UserCodeKeyID       string
	UserCodeDigest      []byte
	DigestVersion       string
	Status              string
	PollIntervalSeconds int32
	NextPollAt          time.Time
	CreatedAt           time.Time
	ExpiresAt           time.Time
	ReviewWebSessionID  pgtype.UUID
	ReviewedAt          pgtype.Timestamptz
	ApprovingUserID     pgtype.UUID
	DecisionAt          pgtype.Timestamptz
	ClaimedAt           pgtype.Timestamptz
	IssuedCredentialID  pgtype.UUID
	TerminalAt          pgtype.Timestamptz
}

type AuthCutoverLedger struct {
	ProtocolVersion string
	Status          string
	UpdatedAt       time.Time
	CompletedAt     pgtype.Timestamptz
}

type AuthExternalIdentity struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	Issuer         string
	Subject        string
	Status         string
	DisplayName    string
	AvatarUrl      string
	CreatedAt      time.Time
	LastVerifiedAt time.Time
	UnlinkedAt     pgtype.Timestamptz
}

type AuthFederatedLoginTransaction struct {
	ID                           pgtype.UUID
	Intent                       string
	StateDigest                  []byte
	BrowserBindingDigest         []byte
	DigestVersion                string
	ProviderRegistrationID       string
	ProviderRegistrationRevision string
	ExpectedIssuer               string
	CallbackUri                  string
	ReturnTo                     string
	PrivateStateKeyID            *string
	PrivateStateNonce            []byte
	PrivateStateCiphertext       []byte
	PrivateStateSchema           string
	InitiatingUserID             pgtype.UUID
	InitiatingWebSessionID       pgtype.UUID
	Status                       string
	CreatedAt                    time.Time
	ExpiresAt                    time.Time
	TerminalAt                   pgtype.Timestamptz
	FailureCode                  string
}

type AuthUser struct {
	ID          pgtype.UUID
	Status      string
	DisplayName string
	AvatarUrl   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DisabledAt  pgtype.Timestamptz
}

type AuthUserCodeAttemptWindow struct {
	WebSessionID pgtype.UUID
	WindowStart  time.Time
	FailureCount int32
	BlockedUntil pgtype.Timestamptz
	UpdatedAt    time.Time
}

type AuthWebSession struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	Status            string
	CreatedAt         time.Time
	LastUsedAt        time.Time
	ReauthenticatedAt time.Time
	AbsoluteExpiresAt time.Time
	TerminalAt        pgtype.Timestamptz
	TerminalReason    string
}

type AuthWebSessionSecret struct {
	SessionID     pgtype.UUID
	Generation    int64
	SecretDigest  []byte
	CsrfDigest    []byte
	DigestVersion string
	IssuedAt      time.Time
	SupersededAt  pgtype.Timestamptz
}

type SecurityAuditEvent struct {
	ID                     pgtype.UUID
	OccurredAt             time.Time
	InitiatorKind          string
	InitiatorID            string
	Action                 string
	TargetKind             string
	TargetID               string
	Outcome                string
	Reason                 string
	RequestID              string
	ProviderRegistrationID string
	WebSessionID           pgtype.UUID
	CliCredentialID        pgtype.UUID
	Metadata               []byte
}
